Repository elonafoobar/elonafoobar, pull requests merged in 2018-09, with the labels that each got.

#838 Fix item_fire() and item_cold()
  src/dmgheal.cpp
  src/elonacore.cpp
  src/item.cpp
  src/item.hpp
Labels: bugfix

#841 Add Japanese translation for config option's description
  runtime/locale/en/config.hcl
  runtime/locale/jp/config.hcl
Labels: I18N, enhancement

#849 Reduce implicit type conversion warnings
  src/ability.cpp
  src/activity.cpp
  src/casino.cpp
  src/elonacore.cpp
  src/enchantment.cpp
  src/food.cpp
  src/initialize_map.cpp
  src/magic.cpp
  src/mapgen.cpp
  src/random.hpp
  src/shop.cpp
  src/spec.cpp
  src/spec.hpp
  src/util.hpp
Labels: refactoring

#852 Define enum class Quality
  src/access_character_info.cpp
  src/access_item_db.cpp
  src/activity.cpp
  src/adventurer.cpp
  src/ai.cpp
  src/buff.cpp
  src/building.cpp
  src/calc.cpp
  src/calc.hpp
  src/casino.cpp
  src/character.cpp
  src/character.hpp
  src/command.cpp
  src/crafting.cpp
  src/ctrl_inventory.cpp
  src/dmgheal.cpp
  src/elonacore.cpp
  src/enchantment.cpp
  src/enums.hpp
  src/equipment.cpp
  src/init.cpp
  src/initialize_map.cpp
  src/item.cpp
  src/item.hpp
  src/itemgen.cpp
  src/lib/enumutil.hpp
  src/magic.cpp
  src/mapgen.cpp
  src/proc_event.cpp
  src/quest.cpp
  src/random_event.cpp
  src/shop.cpp
  src/status_ailment.cpp
  src/talk.cpp
  src/talk_npc.cpp
  src/talk_unique.cpp
  src/tests/lua_api.cpp
  src/tests/lua_handles.cpp
  src/tests/util.cpp
  src/variables.hpp
  src/wish.cpp
Labels: refactoring

#853 Define struct ContinuousAction
  src/activity.cpp
  src/activity.hpp
  src/ai.cpp
  src/blending.cpp
  src/building.cpp
  src/cell_draw.cpp
  src/character.hpp
  src/character_status.cpp
  src/command.cpp
  src/ctrl_inventory.cpp
  src/elonacore.cpp
  src/initialize_map.cpp
  src/item.cpp
  src/magic.cpp
  src/menu.cpp
  src/random_event.cpp
  src/status_ailment.cpp
  src/talk.cpp
  src/turn_sequence.cpp
  src/ui.cpp
Labels: refactoring

#830 Refactor inline formulas in ability.cpp
  src/ability.cpp
  src/ability.hpp
  src/calc.cpp
  src/calc.hpp
  src/elonacore.cpp
Labels: refactoring

#855 Fix i18n errors
  runtime/locale/en/item.hcl
  runtime/locale/en/misc.hcl
  runtime/locale/jp/casino.hcl
  runtime/locale/jp/item.hcl
  runtime/locale/jp/misc.hcl
  src/activity.cpp
  src/elonacore.cpp
  src/text.cpp
Labels: I18N, bugfix

#857 Add GameData and refactor a few parts of gdata
  src/activity.cpp
  src/audio.cpp
  src/building.cpp
  src/calc.cpp
  src/command.cpp
  src/ctrl_file.cpp
  src/dmgheal.cpp
  src/elonacore.cpp
  src/gdata.cpp
  src/gdata.hpp
  src/god.cpp
  src/init.cpp
  src/initialize_map.cpp
  src/itemgen.cpp
  src/lua_env/lua_api/lua_api_chara.cpp
  src/magic.cpp
  src/mapgen.cpp
  src/mef.cpp
  src/proc_event.cpp
  src/random_event.cpp
  src/set_item_info.cpp
  src/shop.cpp
  src/talk_npc.cpp
  src/turn_sequence.cpp
  src/ui.cpp
  src/ui/ui_menu_character_sheet.cpp
Labels: refactoring

#865 Fix special ammo not being added
  src/enchantment.cpp
Labels: bugfix

#866 Fix living weapon not destroying the last enchantment
  src/command.cpp
Labels: bugfix

#872 Fix glitch of wear menu
  src/ui/ui_menu_equipment.cpp
Labels: bugfix

#873 Fix crash of itemname in burning item
  runtime/locale/en/item.hcl
  runtime/locale/jp/item.hcl
  src/i18n.hpp
  src/item.cpp
Labels: bugfix

#876 Fix wrong arguments in quest dialog
  src/quest.cpp
Labels: I18N, bugfix

#875 Fix home rank window
  src/building.cpp
Labels: bugfix

#879 Improve cutscene's shadow
  runtime/graphic/interface_ex4.png
  src/elonacore.cpp
  src/init.cpp
Labels: enhancement

#880 Add `/MT` flag for release build on Windows
  CMakeLists.txt
Labels: bugfix, build

#883 Run CI tests on macOS
  .travis.yml
Labels: bugfix, build

#887 Delete unnecessary return statement
  src/activity.cpp
  src/adventurer.cpp
  src/blending.cpp
  src/building.cpp
  src/casino.cpp
  src/casino_card.cpp
  src/character.cpp
  src/character_making.cpp
  src/draw.cpp
  src/elonacore.cpp
  src/enchantment.cpp
  src/equipment.cpp
  src/event.cpp
  src/food.cpp
  src/god.cpp
  src/item.cpp
  src/itemgen.cpp
  src/map_cell.cpp
  src/mapgen.cpp
  src/mef.cpp
  src/menu.cpp
  src/message.cpp
  src/network.cpp
  src/quest.cpp
  src/shop.cpp
  src/status_ailment.cpp
  src/talk.cpp
  src/tcg.cpp
  src/text.cpp
  src/ui/ui_menu_character_sheet.cpp
  src/ui/ui_menu_game_help.cpp
Labels: refactoring

#886 Delete migration code for vanilla's save
  src/elonacore.cpp
Labels: refactoring

#891 Fix glitch of small map
  src/cell_draw.cpp
Labels: bugfix

#885 Reduce static_cast<int>(MapType) by using a helper function
  src/audio.cpp
  src/cell_draw.cpp
  src/character.cpp
  src/command.cpp
  src/elonacore.cpp
  src/mapgen.cpp
  src/mdata.hpp
  src/text.cpp
Labels: refactoring

#890 Fix black pixels(#000) of portraits being transparent
  src/menu.cpp
  src/talk.cpp
  src/ui/ui_menu_character_sheet.cpp
Labels: bugfix

#854 Define struct AreaData
  CMakeLists.txt
  runtime/locale/en/map.hcl
  runtime/locale/jp/map.hcl
  src/adventurer.cpp
  src/area.cpp
  src/area.hpp
  src/audio.cpp
  src/building.cpp
  src/calc.cpp
  src/cell_draw.cpp
  src/character.cpp
  src/command.cpp
  src/ctrl_file.cpp
  src/dmgheal.cpp
  src/elonacore.cpp
  src/init.cpp
  src/initialize_map.cpp
  src/item.cpp
  src/magic.cpp
  src/mapgen.cpp
  src/mdata.hpp
  src/proc_event.cpp
  src/quest.cpp
  src/talk_npc.cpp
  src/talk_unique.cpp
  src/testing.cpp
  src/tests/lua_serialization.cpp
  src/text.cpp
  src/turn_sequence.cpp
  src/ui/ui_menu_ctrl_ally.cpp
  src/ui/ui_menu_town_chart.cpp
  src/ui/ui_menu_town_economy.cpp
  src/ui/ui_menu_town_politics.cpp
Labels: refactoring

#893 Fix typo
  runtime/lang/en/character.lua
  runtime/lang/en/ui.lua
  runtime/lang/jp/character.lua
  runtime/lang/jp/race.lua
  runtime/locale/en/card_info.hcl
  runtime/locale/en/crafting.hcl
  runtime/locale/en/god.hcl
  runtime/locale/en/quest_journal.hcl
  runtime/locale/en/wish.hcl
  runtime/locale/jp/activity.hcl
  runtime/locale/jp/god.hcl
  runtime/locale/jp/talk_unique.hcl
  runtime/mods/core/locale/jp/item.hcl
  runtime/mods/core/locale/jp/lazy/scene.hsp
Labels: enhancement

#888 Do not play breaking animation if you cannot see there
  src/animation.cpp
Labels: bugfix

#894 Fill minute in message with zeros
  src/message.cpp
Labels: enhancement

#896 Improve serialization portability
  src/defines.hpp
  src/putit.hpp
Labels: enhancement

#900 Fix shadow of selecting save window disappearing once you change page
  src/main_menu.cpp
Labels: bugfix

#899 Overwrite SNAIL_HEADLESS flag if you specify WITH_TESTS=OFF
  CMakeLists.txt
  Makefile
  Makefile.win
Labels: enhancement

#897 Save data versioning
  src/ctrl_file.cpp
  src/elonacore.cpp
  src/gdata.hpp
  src/putit.hpp
  src/tests/data/save/sav_foobar_test/cdata.s1
  src/tests/data/save/sav_foobar_test/cdata_7_101.s2
  src/tests/data/save/sav_foobar_test/evdata1.s1
  src/tests/data/save/sav_foobar_test/evdata2.s1
  src/tests/data/save/sav_foobar_test/filelist.txt
  src/tests/data/save/sav_foobar_test/foobar_data.s1
  src/tests/data/save/sav_foobar_test/gdata.s1
  src/tests/data/save/sav_foobar_test/map_7_101.s2
  src/tests/data/save/sav_foobar_test/sdata.s1
  src/version.cpp.in
  src/version.hpp
Labels: enhancement

#901 Fix being able to unacquirable feats
  src/trait.cpp
Labels: bugfix

#870 Refactor map fields of gdata
  src/ability.cpp
  src/activity.cpp
  src/adventurer.cpp
  src/ai.cpp
  src/audio.cpp
  src/building.cpp
  src/calc.cpp
  src/casino.cpp
  src/character.cpp
  src/command.cpp
  src/ctrl_inventory.cpp
  src/dmgheal.cpp
  src/elonacore.cpp
  src/gdata.cpp
  src/gdata.hpp
  src/god.cpp
  src/init.cpp
  src/initialize_map.cpp
  src/item.cpp
  src/itemgen.cpp
  src/magic.cpp
  src/mapgen.cpp
  src/proc_event.cpp
  src/quest.cpp
  src/shop.cpp
  src/talk.cpp
  src/talk_npc.cpp
  src/talk_unique.cpp
  src/testing.cpp
  src/text.cpp
  src/turn_sequence.cpp
  src/ui.cpp
  src/ui/ui_menu_character_sheet.cpp
  src/ui/ui_menu_ctrl_ally.cpp
  src/ui/ui_menu_hire.cpp
  src/ui/ui_menu_quest_board.cpp
  src/ui/ui_menu_town_chart.cpp
  src/ui/ui_menu_town_economy.cpp
  src/ui/ui_menu_town_politics.cpp
  src/wish.cpp
Labels: refactoring

#871 Refactor various fields of gdata (1)
  src/ability.cpp
  src/activity.cpp
  src/ai.cpp
  src/audio.cpp
  src/building.cpp
  src/calc.cpp
  src/cell_draw.cpp
  src/character.cpp
  src/character_making.cpp
  src/character_status.cpp
  src/command.cpp
  src/ctrl_file.cpp
  src/ctrl_inventory.cpp
  src/dmgheal.cpp
  src/elonacore.cpp
  src/gdata.cpp
  src/gdata.hpp
  src/init.cpp
  src/initialize_map.cpp
  src/item.cpp
  src/magic.cpp
  src/mapgen.cpp
  src/network.cpp
  src/proc_event.cpp
  src/quest.cpp
  src/talk_house_visitor.cpp
  src/talk_npc.cpp
  src/talk_unique.cpp
  src/text.cpp
  src/trait.cpp
  src/turn_sequence.cpp
  src/ui.cpp
  src/ui/ui_menu_character_sheet.cpp
  src/ui/ui_menu_feats.cpp
  src/ui/ui_menu_journal.cpp
  src/ui/ui_menu_quest_board.cpp
  src/ui/ui_menu_scene.cpp
Labels: refactoring

#907 Refactor gdata subquest flags
  src/activity.cpp
  src/command.cpp
  src/dmgheal.cpp
  src/elonacore.cpp
  src/gdata.cpp
  src/gdata.hpp
  src/init.cpp
  src/initialize_map.cpp
  src/proc_event.cpp
  src/quest.cpp
  src/talk_npc.cpp
  src/talk_unique.cpp
  src/text.cpp
Labels: refactoring

#908 Fix typo
  runtime/lang/jp/ability.lua
  runtime/locale/en/map.hcl
Labels: enhancement

#909 Delete noa_debug option
  runtime/config.hcl
  runtime/mods/core/config/config_def.hcl
  src/config.cpp
  src/config.hpp
  src/init.cpp
Labels: refactoring

#906 Allow writing Lua functions to be used in translation files
  CMakeLists.txt
  doc/api/rand.luadoc
  runtime/data/lua/handle.lua
  runtime/data/lua/init.lua
  runtime/locale/en/item.hcl
  runtime/mods/core/i18n/functions.lua
  runtime/mods/core/i18n/init.lua
  runtime/mods/core/i18n/jp_endings.lua
  runtime/mods/core/init.lua
  src/bench/ai.cpp
  src/bench/lion.cpp
  src/bench/magic.cpp
  src/character.cpp
  src/i18n.cpp
  src/i18n.hpp
  src/lion.hpp
  src/lua_env/handle_manager.hpp
  src/lua_env/i18n_function_manager.cpp
  src/lua_env/i18n_function_manager.hpp
  src/lua_env/lua_api/lua_api_i18n.cpp
  src/lua_env/lua_api/lua_api_i18n.hpp
  src/lua_env/lua_api/lua_api_item.cpp
  src/lua_env/lua_api/lua_api_item.hpp
  src/lua_env/lua_api/lua_api_rand.cpp
  src/lua_env/lua_api/lua_api_rand.hpp
  src/lua_env/lua_class/lua_class_character.cpp
  src/lua_env/lua_class/lua_class_item.cpp
  src/lua_env/lua_env.cpp
  src/lua_env/lua_env.hpp
  src/lua_env/registry_manager.cpp
  src/lua_env/registry_manager.hpp
  src/testing.cpp
  src/tests/i18n.cpp
  src/tests/i18n_builtins.cpp
  src/tests/lua/i18n.lua
  src/tests/lua_api.cpp
  src/tests/lua_handles.cpp
  src/tests/util.cpp
Labels: I18N, enhancement, lua

#922 Refactor gdata guild fields
  src/calc.cpp
  src/ctrl_inventory.cpp
  src/elonacore.cpp
  src/gdata.cpp
  src/gdata.hpp
  src/initialize_map.cpp
  src/shop.cpp
  src/talk_house_visitor.cpp
  src/talk_npc.cpp
  src/talk_unique.cpp
  src/text.cpp
Labels: refactoring

#923 Refactor remaining gdata field macros
  src/ai.cpp
  src/blending.cpp
  src/calc.cpp
  src/casino.cpp
  src/character.cpp
  src/character_status.cpp
  src/command.cpp
  src/ctrl_file.cpp
  src/ctrl_inventory.cpp
  src/dmgheal.cpp
  src/draw.cpp
  src/elonacore.cpp
  src/food.cpp
  src/fov.cpp
  src/gdata.cpp
  src/gdata.hpp
  src/god.cpp
  src/init.cpp
  src/initialize_map.cpp
  src/item.cpp
  src/magic.cpp
  src/main_menu.cpp
  src/map_cell.cpp
  src/mapgen.cpp
  src/menu.cpp
  src/network.cpp
  src/proc_event.cpp
  src/talk.cpp
  src/talk_house_visitor.cpp
  src/talk_npc.cpp
  src/talk_unique.cpp
  src/text.cpp
  src/trait.cpp
  src/turn_sequence.cpp
  src/ui.cpp
  src/ui/ui_menu_character_sheet.cpp
  src/ui/ui_menu_charamake_alias.cpp
  src/ui/ui_menu_journal.cpp
  src/wish.cpp
Labels: refactoring

#925 Go to the previous menu by pressing Ctrl+Tab
  src/ctrl_inventory.cpp
  src/input.cpp
  src/ui/ui_menu_composite.hpp
Labels: enhancement

#926 Reload autopick file by pressing Shift+Backspace
  runtime/locale/en/action.hcl
  runtime/locale/jp/action.hcl
  src/turn_sequence.cpp
Labels: enhancement

#927 Do not show "Make up who?" prompt if there are no pet around you
  src/command.cpp
Labels: enhancement

#928 Insert a line break to change ammo message
  src/command.cpp
Labels: enhancement

#929 Show adventurer's name in news
  runtime/locale/en/adventurer.hcl
  runtime/locale/jp/adventurer.hcl
  src/adventurer.cpp
Labels: enhancement

#930 Prevent gene machine from destroying your precious ally
  runtime/locale/en/action_use.hcl
  runtime/locale/jp/action_use.hcl
  src/command.cpp
Labels: enhancement

#931 Do not show message "something falls down" if the item is on the ground
  src/item.cpp
Labels: bugfix

#932 Fix aspect ratio of full-scale PCC in change apperance menu
  src/menu.cpp
Labels: bug

#924 Refactor all other raw usages of gdata(n)
  src/activity.cpp
  src/building.cpp
  src/casino.cpp
  src/cell_draw.cpp
  src/character.cpp
  src/character_status.cpp
  src/command.cpp
  src/ctrl_inventory.cpp
  src/dmgheal.cpp
  src/draw.cpp
  src/elonacore.cpp
  src/gdata.cpp
  src/gdata.hpp
  src/init.cpp
  src/initialize_map.cpp
  src/magic.cpp
  src/mapgen.cpp
  src/menu.cpp
  src/menu.hpp
  src/proc_event.cpp
  src/quest.cpp
  src/talk.cpp
  src/talk_npc.cpp
  src/talk_unique.cpp
  src/tcg.cpp
  src/turn_sequence.cpp
  src/ui.cpp
  src/ui/ui_menu_character_sheet.cpp
  src/ui/ui_menu_charamake_gender.cpp
  src/ui/ui_menu_equipment.cpp
  src/ui/ui_menu_journal.cpp
  src/ui/ui_menu_skills.cpp
  src/ui/ui_menu_spells.cpp
  src/ui/ui_menu_town_economy.cpp
  src/ui/ui_menu_town_politics.cpp
Labels: refactoring

#934 Structure qdata into QuestData
  src/calc.cpp
  src/character.cpp
  src/ctrl_file.cpp
  src/ctrl_inventory.cpp
  src/elonacore.cpp
  src/init.cpp
  src/initialize_map.cpp
  src/mapgen.cpp
  src/menu.cpp
  src/proc_event.cpp
  src/quest.cpp
  src/quest.hpp
  src/talk.cpp
  src/talk_npc.cpp
  src/ui/ui_menu_journal.cpp
  src/ui/ui_menu_quest_board.cpp
Labels: refactoring

#935 Structure map() into CellData
  src/activity.cpp
  src/ai.cpp
  src/building.cpp
  src/cell_draw.cpp
  src/character.cpp
  src/command.cpp
  src/ctrl_file.cpp
  src/ctrl_inventory.cpp
  src/elonacore.cpp
  src/fov.cpp
  src/initialize_map.cpp
  src/item.cpp
  src/itemgen.cpp
  src/lua_env/lua_api/lua_api_map.cpp
  src/magic.cpp
  src/map.cpp
  src/map.hpp
  src/map_cell.cpp
  src/mapgen.cpp
  src/mef.cpp
  src/proc_event.cpp
  src/talk_npc.cpp
  src/turn_sequence.cpp
  src/ui.cpp
Labels: refactoring

#938 Refactor rest of mdata fields
  src/activity.cpp
  src/adventurer.cpp
  src/ai.cpp
  src/audio.cpp
  src/building.cpp
  src/calc.cpp
  src/casino.cpp
  src/cell_draw.cpp
  src/character.cpp
  src/character_status.cpp
  src/command.cpp
  src/ctrl_file.cpp
  src/ctrl_inventory.cpp
  src/dmgheal.cpp
  src/draw.cpp
  src/elonacore.cpp
  src/food.cpp
  src/init.cpp
  src/initialize_map.cpp
  src/item.cpp
  src/lua_env/lua_api/lua_api_map.cpp
  src/magic.cpp
  src/map.cpp
  src/map.hpp
  src/mapgen.cpp
  src/mdata.hpp
  src/mef.cpp
  src/proc_event.cpp
  src/random_event.cpp
  src/talk.cpp
  src/talk_unique.cpp
  src/text.cpp
  src/turn_sequence.cpp
  src/ui.cpp
  src/ui/ui_menu_town_politics.cpp
Labels: refactoring

#939 Refactor initialize_map
  CMakeLists.txt
  src/character.cpp
  src/character.hpp
  src/elonacore.cpp
  src/initialize_map.cpp
  src/initialize_map_types.cpp
  src/mapgen.cpp
  src/proc_event.cpp
  src/quest.cpp
  src/quest.hpp
  src/variables.hpp
Labels: refactoring

#940 Refactor parts of code that have map-specific behavior
  CMakeLists.txt
  src/activity.cpp
  src/ai.cpp
  src/area.cpp
  src/area.hpp
  src/character.cpp
  src/character.hpp
  src/command.cpp
  src/elonacore.cpp
  src/initialize_map.cpp
  src/magic.cpp
  src/map.cpp
  src/map.hpp
  src/map_chara_filter.cpp
  src/map_special_events.cpp
  src/map_trainer_skills.cpp
  src/mapgen.cpp
  src/mapgen.hpp
  src/proc_event.cpp
  src/shop.cpp
  src/shop.hpp
  src/talk_npc.cpp
  src/text.cpp
  src/turn_sequence.cpp
  src/ui/ui_menu_character_sheet.cpp
  src/variables.hpp
Labels: refactoring

#944 Refactor config-specific parts of code
  CMakeLists.txt
  src/activity.cpp
  src/animation.cpp
  src/audio.cpp
  src/blending.cpp
  src/building.cpp
  src/card.cpp
  src/casino.cpp
  src/cell_draw.cpp
  src/character_making.cpp
  src/character_status.cpp
  src/command.cpp
  src/config/config.cpp
  src/config/config.hpp
  src/config/config_def.cpp
  src/config/config_def.hpp
  src/config/config_menu.hpp
  src/config/create_config_screen.cpp
  src/config/create_config_screen.hpp
  src/config/set_option.cpp
  src/crafting.cpp
  src/ctrl_inventory.cpp
  src/dmgheal.cpp
  src/draw.cpp
  src/elonacore.cpp
  src/god.cpp
  src/i18n.cpp
  src/init.cpp
  src/initialize_map.cpp
  src/input.cpp
  src/lua_env/handle_manager.cpp
  src/lua_env/i18n_function_manager.cpp
  src/lua_env/lua_env.cpp
  src/magic.cpp
  src/main_menu.cpp
  src/menu.cpp
  src/message.cpp
  src/network.cpp
  src/proc_event.cpp
  src/random_event.cpp
  src/set_option.cpp
  src/shop.cpp
  src/spec.cpp
  src/spec_load.cpp
  src/std.cpp
  src/talk.cpp
  src/talk_house_visitor.cpp
  src/tcg.cpp
  src/testing.cpp
  src/tests/config.cpp
  src/tests/config_def.cpp
  src/tests/util.cpp
  src/turn_sequence.cpp
  src/ui.cpp
  src/ui/ui_menu.hpp
  src/ui/ui_menu_config.cpp
  src/ui/ui_menu_config.hpp
Labels: refactoring

#946 Fix trainer_skills_vernis
  src/map_trainer_skills.cpp
Labels: bugfix
