Repository elonafoobar/elonafoobar, pull requests merged in 2018-06, with the labels that each got.

#448 Fix broken link to AppVeyor's status badge in README.md
  README-jp.md
  README.md
Labels: bug

#449 Fix AppVeyor failure
  appveyor.yml
Labels: bug

#460 Add -y option(answer yes to all prompt) to 7z in appveyor.yml
  appveyor.yml
Labels: bug

#461 Fix not being able to quit in the casino
  casino.cpp
Labels: bug

#465 Use omake's formula for casino cure corruption potion reward
  casino.cpp
Labels: bug

#468 Fix out-of-range access to fovlist
  fov.cpp
  fov.hpp
  ui.cpp
Labels: bug

#463 Rework name splitting algorithm
  CMakeLists.txt
  elonacore.cpp
  tests/elonacore.cpp
Labels: bug

#462 Add story files
  data/scene1.hsp
  data/scene2.hsp
  elonacore.cpp
  menu.cpp
Labels: bug

#466 Preallocate memory for damage popups
  draw.cpp
  draw.hpp
  init.cpp
Labels: bug

#469 Fix loot of loads of Chaos Castles
  elonacore.cpp
Labels: bug

#470 Check generation count of certain unique monsters
  get_random_npc_id.cpp
Labels: bug

#478 Fix PC dying in main scenario
  character.cpp
Labels: bug

#464 Improve handling of numpad with shift/allow usage of numpad enter
  config.cpp
  message.cpp
  snail/hsp/sdl.cpp
  snail/input.cpp
  std.cpp
Labels: bug

#488 Fix being unable to wish items/skills in wizard mode
  wish.cpp
Labels: bug

#489 Fix bone file mojibake
  CMakeLists.txt
  runtime/original/lastwords-e.txt
  runtime/original/lastwords.txt
Labels: bug

#490 Fix crash in using deck
  card.cpp
Labels: bug

#491 Fix fishing failing more often than vanilla
  elonacore.cpp
Labels: bug

#487 [WIP] Fix living weapon not gaining enchantments
  command.cpp
  enchantment.cpp
  enchantment.hpp
Labels: bug

#493 Fix talk_guide_quest_client()
  talk.cpp
  talk.hpp
Labels: bug

#494 Fix typo in japanese
  command.cpp
  crafting.cpp
  data/item.lua
  lang/jp/buff.lua
  menu.cpp
  talk_npc.cpp
  trait.cpp
Labels: bug

#495 Adjust PC's weight
  food.cpp
Labels: bug

#500 Hide stair positions in minimap unless using Voldemort
  ui.cpp
  ui.hpp
Labels: enhancement

#498 Add length limiting option to message box input
  input.cpp
  input.hpp
Labels: bug

#499 Add generation count to deck
  card.cpp
Labels: enhancement

#497 Don't copy files over if they exist on build
  CMakeLists.txt
  cmake/copy_nonexisting.cmake
Labels: bug

#512 Decrease animation deray
  animation.cpp
  blending.cpp
  building.cpp
  character_making.cpp
  command.cpp
  elonacore.cpp
  god.cpp
  input.cpp
  magic.cpp
  main_menu.cpp
  message.cpp
  proc_event.cpp
  talk.cpp
  turn_sequence.cpp
  ui.cpp
  variables.hpp
Labels: enhancement

#510 Fix PCC editor in chara making
  character_making.cpp
Labels: bug

#501 Add missing portraits
  data/character.lua
Labels: enhancement

#514 Fix enter key not working sometimes
  snail/input.cpp
Labels: bug

#515 Fix infinite loop when entering map
  character.cpp
Labels: bug

#513 Adjust key sensitivity
  card.cpp
  casino.cpp
  config.cpp
  config.hpp
  crafting.cpp
  ctrl_inventory.cpp
  elona.hpp
  elonacore.cpp
  init.cpp
  input.cpp
  input.hpp
  magic.cpp
  message.cpp
  proc_event.cpp
  set_option.cpp
  snail/hsp/sdl.cpp
  snail/input.cpp
  snail/input.hpp
  std.cpp
  talk.cpp
  tcg.cpp
  turn_sequence.cpp
  variables.hpp
Labels: enhancement

#516 Set the relocated character's index value
  character.cpp
Labels: bug

#517 Check if there is the file whose name is the same as playerid
  character_making.cpp
  input.cpp
  input.hpp
Labels: bug

#524 Add GitHub pages
  Makefile
  docs/classes/LuaCharacter.html
  docs/classes/LuaItem.html
  docs/classes/LuaPosition.html
  docs/examples/life.lua
  docs/examples/life.lua.html
  docs/index.html
  docs/ldoc.css
  docs/modules/Chara.html
  docs/modules/Debug.html
  docs/modules/Enums.html
  docs/modules/Event.EventKind.html
  docs/modules/Event.html
  docs/modules/FOV.html
  docs/modules/GUI.html
  docs/modules/Item.html
  docs/modules/Iter.html
  docs/modules/Magic.html
  docs/modules/Map.html
  docs/modules/Pos.html
  docs/modules/Rand.html
  docs/modules/Skill.html
  docs/modules/World.html
  docs/readme.md
  docs/red_putit.png
  docs/topics/readme.md.html
  docs/uikit.min.css
Labels: enhancement

#518 Fix contradiction of item index
  item.cpp
Labels: bug

#530 Improve shadow rendering
  init.cpp
  runtime/graphic/interface_ex1.png
  runtime/graphic/interface_ex2.png
  runtime/graphic/interface_ex3.png
  snail/hsp/sdl.cpp
Labels: enhancement

#529 Polish key sensitivity more
  config.cpp
  config.hpp
  elona.hpp
  elonacore.cpp
  input.cpp
  set_option.cpp
  snail/hsp.hpp
  snail/hsp/headless.cpp
  snail/hsp/sdl.cpp
  snail/input.cpp
  snail/input.hpp
  std.cpp
Labels: enhancement

#539 Fix errors in SDL to be caught
  config.cpp
  i18n.cpp
  init.cpp
  lua_env/lua_api.cpp
  lua_env/lua_env.cpp
  lua_env/lua_env.hpp
  main.cpp
  snail/application/sdl.cpp
  snail/hsp/sdl.cpp
Labels: bug

#540 Add note to avoid overwriting files in README
  README.md
Labels: bug

#552 Fix exp overflow
  ability.cpp
  random.hpp
Labels: bug

#559 Validate integer options
  config.cpp
Labels: bug

#561 Implement autonumlock/Add "Clear" as wait key
  elonacore.cpp
  init.cpp
  input.cpp
  main_menu.cpp
  snail/input.cpp
  snail/input.hpp
Labels: bug

#577 Fix criminal being unable to have business in Derphy
  talk_npc.cpp
Labels: bug

#569 Implement extra number prompt functions
  input.cpp
Labels: enhancement

#567 Fine tune the repeat delay of enter/backspace
  elonacore.cpp
  enums.hpp
  input.cpp
  snail/hsp/sdl.cpp
  talk.cpp
Labels: bug

#570 Add save screen pagination beyond 5 savefiles
  main_menu.cpp
  std.cpp
  ui.cpp
  ui.hpp
Labels: enhancement

#565 Move message print position up by one
  message.cpp
Labels: bug

#557 Add copy statement for runtime/ folder in Appveyor
  appveyor.yml
Labels: bug

#568 Add alias lock and other character making conveniences
  building.cpp
  character_making.cpp
  character_making.hpp
  input.cpp
  input.hpp
  main_menu.cpp
  main_menu.hpp
  menu.cpp
  network.cpp
  set_option.cpp
  snail/hsp/sdl.cpp
  ui.cpp
  ui.hpp
Labels: enhancement

#579 Stack goods at shop after generating
  shop.cpp
Labels: bug

#581 Fix removal of item info
  item.cpp
Labels: bug

#590 Save foobar version and add migration code
  ctrl_file.cpp
  elonacore.cpp
  gdata.cpp
  gdata.hpp
  init.cpp
  testing.cpp
  tests/serialization.cpp
  turn_sequence.cpp
  ui.cpp
Labels: bug

#584 Patch Lua to support UTF-16 filenames on Windows
  .gitignore
  CMakeLists.txt
  README.md
  appveyor.yml
  cat.cpp
  cmake/lua/CMakeLists.txt
  cmake/lua/lua_wstring_5.3.4.patch
  deps/install.bat
  i18n.cpp
  snail/font.cpp
  tests/lua/Windowsファイル名.lua
  tests/lua/support/テスト.lua
  tests/lua_api.cpp
Labels: bug

#583 Fix minor charamake issues
  character_making.cpp
Labels: bug

#591 Change naming convention of save
  character_making.cpp
  filesystem.cpp
  filesystem.hpp
  init.cpp
Labels: bug

#594 Fix broken map
  ctrl_file.cpp
  elonacore.cpp
  map.cpp
  map.hpp
  variables.hpp
Labels: bug

#564 Report success of chara_create properly based on chara_place
  character.cpp
  character.hpp
  mods/core/iter.lua
Labels: bug

#596 API: Add LuaCharacter.experience
  doc/api/classes/LuaCharacter.luadoc
  lua_env/lua_api.cpp
Labels: enhancement

#597 Re-calculate distance between 2 npcs when switching the opponent
  ai.cpp
Labels: bug

#599 Move tests/lua/* to src/tests/lua/
  src/tests/lua/Windowsファイル名.lua
  src/tests/lua/support/テスト.lua
Labels: bug

#600 Change autopick "to save" mark from "*" to "%"
  src/autopick.cpp
Labels: bug

#608 Fix filepath handling
  src/cat.cpp
  src/filesystem.cpp
  src/filesystem.hpp
  src/snail/font.cpp
  src/snail/hsp.hpp
  src/snail/hsp/headless.cpp
  src/snail/hsp/sdl.cpp
  src/std.cpp
Labels: bug

#606 Add itemname/itembasename as I18N functions
  src/i18n.cpp
  src/tests/i18n.cpp
  src/tests/i18n_builtins.cpp
  src/thirdparty/microhil/hil.hpp
Labels: enhancement

#563 Add Event.unregister/Event.clear
  .luacheckrc
  CMakeLists.txt
  doc/api/event.luadoc
  src/lua_env/event_manager.cpp
  src/lua_env/event_manager.hpp
  src/lua_env/lua_api.cpp
  src/lua_env/lua_api.hpp
  src/lua_env/lua_env.cpp
  src/lua_env/lua_env.hpp
  src/tests/lua_api.cpp
  src/tests/lua_callbacks.cpp
  src/tests/lua_events.cpp
  src/tests/lua_handles.cpp
  src/tests/lua_mods.cpp
  src/tests/lua_serialization.cpp
  src/tests/lua_store.cpp
Labels: enhancement

#544 Add a script loaded callback
  doc/api/event_eventkind.luadoc
  doc/api/map.luadoc
  doc/api/world.luadoc
  runtime/data/script/all_magic.lua
  runtime/data/script/iter.lua
  src/init.cpp
  src/lua_env/event_manager.cpp
  src/lua_env/event_manager.hpp
Labels: enhancement

#588 I18N: Externalize building-related text
  runtime/locale/en/building.hcl
  runtime/locale/jp/building.hcl
  src/building.cpp
  src/building.hpp
  src/elonacore.cpp
  src/lua_env/lua_api.cpp
  src/turn_sequence.cpp
  src/variables.hpp
Labels: I18N, enhancement

#613 Add dungeon name translation
  runtime/locale/en/map.hcl
  runtime/locale/jp/map.hcl
Labels: I18N

#586 I18N: Externalize quest-related strings
  runtime/locale/en/common.hcl
  runtime/locale/en/quest.hcl
  runtime/locale/jp/common.hcl
  runtime/locale/jp/quest.hcl
  src/command.cpp
  src/dmgheal.cpp
  src/elonacore.cpp
  src/god.cpp
  src/i18n.cpp
  src/magic.cpp
  src/proc_event.cpp
  src/quest.cpp
  src/talk_unique.cpp
  src/turn_sequence.cpp
  src/wish.cpp
Labels: I18N, enhancement

#545 I18N: Externalize damage strings
  runtime/locale/en/damage.hcl
  runtime/locale/en/death.hcl
  runtime/locale/en/status_ailment.hcl
  runtime/locale/jp/damage.hcl
  runtime/locale/jp/death.hcl
  runtime/locale/jp/status_ailment.hcl
  src/dmgheal.cpp
  src/dmgheal.hpp
  src/element.cpp
  src/elonacore.cpp
  src/i18n.hpp
  src/status_ailment.cpp
Labels: I18N, enhancement

#556 Add I18N Lua API
  .luacheckrc
  Makefile
  doc/api/i18n.luadoc
  doc/config.ld
  doc/ldoc.css
  doc/topics/i18n.md
  doc/topics/i18n_functions.md
  src/dmgheal.cpp
  src/element.cpp
  src/elonacore.cpp
  src/i18n.cpp
  src/i18n.hpp
  src/lua_env/lua_api.cpp
  src/lua_env/lua_api.hpp
  src/lua_env/lua_env.cpp
  src/testing.cpp
  src/tests/i18n.cpp
  src/tests/lua/i18n.lua
  src/tests/lua_api.cpp
  src/text.cpp
Labels: I18N, enhancement, lua

#505 Refactor cell_draw()
  src/cell_draw.cpp
  src/dmgheal.cpp
  src/draw.cpp
  src/elonacore.cpp
  src/init.cpp
  src/variables.hpp
Labels: refactoring

#609 Adjust keywait for numpad wait/enter and shortcut key
  src/elonacore.cpp
  src/enums.hpp
  src/input.cpp
  src/input.hpp
  src/menu.cpp
  src/turn_sequence.cpp
Labels: bug

#617 Delete unused prototype declarations
  src/ctrl_file.cpp
  src/elona.hpp
  src/elonacore.cpp
  src/init.cpp
  src/input.cpp
  src/item.cpp
  src/network.cpp
  src/std.cpp
  src/tcg.cpp
  src/testing.cpp
  src/text.cpp
  src/variables.hpp
Labels: refactoring

#619 clang-format
  Makefile
  src/building.cpp
  src/dmgheal.cpp
  src/element.cpp
  src/elonacore.cpp
  src/enums.hpp
  src/god.cpp
  src/i18n.cpp
  src/i18n.hpp
  src/init.cpp
  src/lua_env/event_manager.cpp
  src/lua_env/event_manager.hpp
  src/lua_env/lua_api.cpp
  src/lua_env/lua_api.hpp
  src/lua_env/lua_env.cpp
  src/lua_env/lua_env.hpp
  src/proc_event.cpp
  src/quest.cpp
  src/status_ailment.cpp
  src/talk_unique.cpp
  src/testing.cpp
  src/tests/i18n.cpp
  src/tests/i18n_builtins.cpp
  src/tests/lua_api.cpp
  src/tests/lua_events.cpp
  src/tests/lua_handles.cpp
  src/tests/lua_mods.cpp
  src/tests/lua_serialization.cpp
  src/text.cpp
Labels: refactoring

#618 Refactor chipi and chipc
  src/blending.cpp
  src/building.cpp
  src/cell_draw.cpp
  src/character_making.cpp
  src/crafting.cpp
  src/ctrl_inventory.cpp
  src/draw.cpp
  src/draw.hpp
  src/elonacore.cpp
  src/menu.cpp
  src/talk.cpp
  src/tcg.cpp
  src/variables.hpp
Labels: refactoring

#614 I18N: Externalize food-related strings
  CMakeLists.txt
  runtime/locale/en/food.hcl
  runtime/locale/jp/food.hcl
  src/elonacore.cpp
  src/food.cpp
  src/food.hpp
  src/lua_env/lua_api.cpp
  src/quest.cpp
  src/tests/i18n_regressions.cpp
  src/tests/util.hpp
  src/text.cpp
  src/variables.hpp
Labels: I18N

#621 Emulate subtractive/additive blending
  src/animation.cpp
  src/blending.cpp
  src/casino.cpp
  src/cell_draw.cpp
  src/crafting.cpp
  src/ctrl_inventory.cpp
  src/draw.cpp
  src/elona.hpp
  src/elonacore.cpp
  src/input.cpp
  src/menu.cpp
  src/network.cpp
  src/snail/hsp/sdl.cpp
  src/std.cpp
  src/turn_sequence.cpp
  src/ui.cpp
Labels: bug

#624 I18N: Externalize card info strings
  runtime/locale/en/card_info.hcl
  runtime/locale/jp/card_info.hcl
  src/get_card_info.cpp
Labels: I18N

#628 Delay enter if key_enter is already detected as key pressed
  src/input.cpp
Labels: bugfix

#631 Clear input keys during cards are dealt
  src/casino.cpp
Labels: bugfix

#635 Fix death cause message/refactor dmghp()
  src/character.hpp
  src/dmgheal.cpp
  src/dmgheal.hpp
  src/main.hpp
  src/variables.hpp
Labels: I18N, bugfix, refactoring

#637 Add Trait API
  .luacheckrc
  doc/api/trait.luadoc
  src/lua_env/lua_api.cpp
  src/tests/lua/Windowsファイル名.lua
  src/tests/lua/chara.lua
  src/tests/lua/fov.lua
  src/tests/lua/i18n.lua
  src/tests/lua/item.lua
  src/tests/lua/map.lua
  src/tests/lua/readonly.lua
  src/tests/lua/trait.lua
  src/tests/lua_api.cpp
Labels: lua

#634 Use enum property for death_by.other
  src/dmgheal.cpp
Labels: I18N, bugfix

#620 Refactor HSP functions
  src/access_item_db.cpp
  src/adventurer.cpp
  src/ai.cpp
  src/animation.cpp
  src/blending.cpp
  src/building.cpp
  src/casino.cpp
  src/casino_card.cpp
  src/cell_draw.cpp
  src/character_making.cpp
  src/character_status.cpp
  src/crafting.cpp
  src/ctrl_inventory.cpp
  src/elona.hpp
  src/elonacore.cpp
  src/enchantment.cpp
  src/input.cpp
  src/item.cpp
  src/itemgen.cpp
  src/main_menu.cpp
  src/mapgen.cpp
  src/menu.cpp
  src/network.cpp
  src/proc_event.cpp
  src/quest.cpp
  src/set_option.cpp
  src/shop.cpp
  src/snail/hsp.hpp
  src/snail/hsp/headless.cpp
  src/snail/hsp/sdl.cpp
  src/std.cpp
  src/talk.cpp
  src/tcg.cpp
  src/text.cpp
  src/ui.cpp
  src/util.hpp
  src/variables.hpp
Labels: refactoring

#638 Refactor sprite rendering
  src/blending.cpp
  src/building.cpp
  src/casino_card.cpp
  src/cell_draw.cpp
  src/character_making.cpp
  src/character_making.hpp
  src/ctrl_inventory.cpp
  src/draw.cpp
  src/draw.hpp
  src/elona.hpp
  src/elonacore.cpp
  src/init.cpp
  src/input.cpp
  src/magic.cpp
  src/main.hpp
  src/main_menu.cpp
  src/menu.cpp
  src/message.cpp
  src/set_option.cpp
  src/snail/hsp.hpp
  src/snail/hsp/headless.cpp
  src/snail/hsp/sdl.cpp
  src/std.cpp
  src/talk.cpp
  src/tcg.cpp
  src/ui.cpp
  src/variables.hpp
Labels: refactoring

#639 Add Input API
  .luacheckrc
  doc/api/input.luadoc
  src/lua_env/lua_api.cpp
  src/tests/lua/input.lua
  src/tests/lua_api.cpp
Labels: lua

#641 Refactor UI functions
  src/blending.cpp
  src/card.cpp
  src/ctrl_inventory.cpp
  src/draw.cpp
  src/draw.hpp
  src/elonacore.cpp
  src/init.cpp
  src/magic.cpp
  src/menu.cpp
  src/ui.cpp
  src/ui.hpp
  src/variables.hpp
Labels: refactoring
