Repository elonafoobar/elonafoobar, pull requests merged in 2018-10, with the labels that each got.

#943 Fix impression modify I18N error
  src/dmgheal.cpp
Labels: I18N, bugfix

#942 Use raw cdatan instead of character when adding quality parens
  runtime/locale/en/chara.hcl
  runtime/locale/jp/chara.hcl
  src/character.cpp
Labels: bugfix

#947 Add base keybinding code
  CMakeLists.txt
  src/dialog/dialog_decoder.hpp
  src/hcl.hpp
  src/init.cpp
  src/input.hpp
  src/keybind/key_names.cpp
  src/keybind/keybind.cpp
  src/keybind/keybind.hpp
  src/keybind/keybind_actions.cpp
  src/keybind/keybind_deserializer.cpp
  src/keybind/keybind_deserializer.hpp
  src/keybind/keybind_serializer.cpp
  src/keybind/keybind_serializer.hpp
  src/snail/input.cpp
  src/snail/input.hpp
  src/spec.cpp
  src/spec_load.cpp
  src/tests/keybind_deserializer.cpp
  src/tests/keybind_key_names.cpp
  src/tests/keybind_manager.cpp
  src/tests/keybind_serializer.cpp
  src/turn_sequence.cpp
  src/ui/ui_menu.hpp
  src/ui/ui_menu_keybindings.cpp
  src/ui/ui_menu_keybindings.hpp
Labels: enhancement

#952 Add Android 21 compatibility for latest build
  CMakeLists.txt
  android/app/build.gradle
  android/app/src/main/java/xyz/ki/elonafoobar/SplashScreen.java
  runtime/locale/en/config.hcl
  runtime/locale/jp/config.hcl
  runtime/mods/core/config/config_def.hcl
  src/config/config.cpp
  src/input.cpp
  src/keybind/input_context.cpp
  src/keybind/input_context.hpp
  src/keybind/keybind_manager.cpp
  src/menu.cpp
  src/menu.hpp
  src/menu_quick_menu.cpp
  src/snail/input.cpp
  src/snail/input.hpp
  src/snail/touch_input.hpp
  src/snail/touch_input/sdl.cpp
  src/turn_sequence_pc_actions.cpp
  src/ui/ui_menu.hpp
Labels: android, bugfix, refactoring

#953 Fix scene fade out
  src/elonacore.cpp
Labels: bugfix

#954 Fix switch_mode_2 action in inventory being duplicated
  src/ctrl_inventory.cpp
Labels: bugfix

#956 Speed up incremental build time on Linux/macOS
  CMakeLists.txt
  Makefile
  Makefile.win
Labels: build, enhancement

#955 Add Show FPS option
  CMakeLists.txt
  runtime/locale/en/config.hcl
  runtime/locale/jp/config.hcl
  runtime/mods/core/config/config_def.hcl
  src/config/config.cpp
  src/lib/fps_counter.cpp
  src/lib/fps_counter.hpp
  src/lib/profiler.cpp
  src/lib/profiler.hpp
  src/std.cpp
  src/turn_sequence.cpp
Labels: enhancement

#960 Fix various pic_loader issues
  runtime/mods/core/data/chara_chip.hcl
  src/db_chara_chip.cpp
  src/db_item_chip.cpp
  src/draw.cpp
  src/draw.hpp
  src/pic_loader/pic_loader.cpp
  src/pic_loader/pic_loader.hpp
Labels: bugfix

#965 Fix boundary check of pic_loader
  runtime/mods/core/data/chara_chip.lua
  runtime/mods/core/data/item_chip.lua
  src/pic_loader/pic_loader.hpp
Labels: bugfix

#967 Fix typo in README.md
  README.md
Labels: enhancement

#969 Adjust position of skill tracked potential
  src/ui.cpp
Labels: bugfix

#970 Externalize item drop behavior
  doc/api/classes/LuaCharacter.luadoc
  doc/api/enums.luadoc
  doc/api/event_eventkind.luadoc
  doc/api/iter.luadoc
  doc/api/magic.luadoc
  runtime/mods/core/data.lua
  runtime/mods/core/data/chara.lua
  runtime/mods/core/data/chara_drop.lua
  runtime/mods/core/exports/impl.lua
  runtime/mods/core/exports/impl/README.md
  runtime/mods/core/exports/impl/chara_drop.lua
  runtime/mods/core/init.lua
  src/access_character_info.cpp
  src/command.cpp
  src/dmgheal.cpp
  src/elonacore.cpp
  src/init.cpp
  src/lua_env/enums/enums.cpp
  src/lua_env/enums/enums.hpp
  src/lua_env/handle_manager.hpp
  src/lua_env/interface.hpp
  src/lua_env/lua_api/lua_api_chara.cpp
  src/lua_env/lua_api/lua_api_chara.hpp
  src/lua_env/lua_api/lua_api_item.cpp
  src/lua_env/lua_api/lua_api_item.hpp
  src/lua_env/lua_api/lua_api_map.cpp
  src/lua_env/lua_api/lua_api_map.hpp
  src/lua_env/lua_class/lua_class_character.cpp
  src/lua_env/lua_class/lua_class_item.cpp
  src/lua_env/lua_console.cpp
  src/lua_env/lua_console.hpp
  src/tests/lua/chara.lua
  src/tests/lua/classes/LuaCharacter.lua
  src/tests/lua/fov.lua
  src/tests/lua/i18n.lua
  src/tests/lua/item.lua
  src/tests/lua_callbacks.cpp
  src/tests/lua_handles.cpp
Labels: customization, lua

#975 Change sprite of happy bed/double bed to that of luxury bed
  runtime/mods/core/data/item.lua
  runtime/mods/core/data/item_chip.lua
Labels: bugfix

#976 Fix item names in crafting menu being colored wrong
  src/ui/ui_menu_crafting.cpp
Labels: bugfix

#977 Remove graphics garbage of selection keys
  src/input_prompt.cpp
Labels: bugfix

#973 Remove full qualification of default music IDs
  src/audio.cpp
Labels: bugfix

#981 Fix forward declaration to fit actual definition: class -> struct
  src/lua_env/data_manager.hpp
Labels: refactoring

#985 Improve blackjack drawing
  runtime/graphic/interface_ex5.png
  runtime/graphic/interface_ex6.png
  runtime/graphic/interface_ex7.png
  runtime/graphic/interface_ex8.png
  src/casino_card.cpp
  src/casino_card.hpp
  src/init.cpp
Labels: enhancement

#979 Port EN translation of cutscenes from E+C
  CREDITS
  appveyor.yml
  runtime/mods/core/locale/en/lazy/scene.hsp
  runtime/mods/core/locale/jp/lazy/scene.hsp
  src/elonacore.cpp
  src/main_menu.cpp
Labels: I18N, enhancement

#974 Externalize shop inventory behavior
  CMakeLists.txt
  runtime/data/lua/data.lua
  runtime/data/lua/private/scan_exports.lua
  runtime/data/script/test_item_chip.lua
  runtime/data/script/test_menus.lua
  runtime/data/script/test_shop.lua
  runtime/mods/core/data.lua
  runtime/mods/core/data/chara_drop.lua
  runtime/mods/core/data/shop_inventory.lua
  runtime/mods/core/exports/impl.lua
  runtime/mods/core/exports/impl/chara_drop.lua
  runtime/mods/core/exports/impl/shop_inventory.lua
  src/elonacore.cpp
  src/lua_env/enums/enums.cpp
  src/lua_env/interface.cpp
  src/lua_env/interface.hpp
  src/lua_env/lua_api/lua_api_item.cpp
  src/lua_env/lua_api/lua_api_item.hpp
  src/lua_env/lua_api/lua_api_world.cpp
  src/lua_env/lua_api/lua_api_world.hpp
  src/lua_env/lua_class/lua_class_character.cpp
  src/lua_env/lua_class/lua_class_item.cpp
  src/lua_env/mod_manager.cpp
  src/shop.cpp
  src/shop.hpp
  src/tests/lua_data.cpp
  src/ui/ui_menu_game_help.hpp
  src/variables.hpp
Labels: customization, lua

#992 Suppress unused variable warning due to Boost.Flyweight
  src/shared_id.hpp
Labels: refactoring
