Repository elonafoobar/elonafoobar, pull requests merged in 2018-05, with the labels that each got.

#215 Add missing include directive(<bitset>)
  character.hpp
Labels: bug

#217 Fix size of bit flags
  character.cpp
  character.hpp
  elonacore.cpp
Labels: bug

#216 Add missing encoding conversion
  elonacore.cpp
Labels: bug

#226 Fix selected text at the prompt filled black
  std.cpp
Labels: bug

#229 Add _UNICODE flag for Visual Studio
  CMakeLists.txt
Labels: bug

#230 Delete unnecessary executable directory
  elonacore.cpp
Labels: bug

#232 Feature/fix employees vanishing
  ctrl_file.cpp
Labels: bug

#234 Fix infinite loop at casino
  elonacore.cpp
Labels: bug

#236 Delete support for vanilla's custom file format
  ctrl_file.cpp
  elonacore.cpp
  init.cpp
  initialize_map.cpp
  talk_npc.cpp
  variables.hpp
Labels: enhancement

#237 Fix filepath handling on windows
  access_item_db.cpp
  animation.cpp
  autopick.cpp
  card.cpp
  config.cpp
  ctrl_file.cpp
  ctrl_file.hpp
  ctrl_inventory.cpp
  elona.hpp
  elonacore.cpp
  filesystem.cpp
  filesystem.hpp
  foobar_save.cpp
  init.cpp
  initialize_map.cpp
  log.cpp
  magic.cpp
  proc_event.cpp
  set_option.cpp
  snail/font.cpp
  snail/image.cpp
  std.cpp
  talk_unique.cpp
  tcg.cpp
  text.cpp
  variables.hpp
Labels: bug

#249 Disable autosave
  config.cpp
  config.hpp
  elonacore.cpp
  set_option.cpp
Labels: enhancement

#252 Feature/update readme
  README-jp.md
  README.md
Labels: enhancement

#253 Add empty check of the_ability_db
  elonacore.cpp
  magic.cpp
Labels: bug

#255 Fix default value of key_close
  config.cpp
Labels: bug

#260 clang-format
  ability.cpp
  calc.cpp
  cat.cpp
  ctrl_file.cpp
  elona.hpp
  elonacore.cpp
  init.cpp
  initialize_map.cpp
  magic.cpp
  main.cpp
  proc_event.cpp
  putit.hpp
  snail/font.cpp
  std.cpp
  util.hpp
Labels: refactoring

#263 Fix English language option
  cat.cpp
  lang/en/buff.lua
  runtime/config.json
Labels: bug

#272 Specify clone_folder in appveyor.yml
  appveyor.yml
Labels: bug

#273 Restore disabling autosave feature
  config.cpp
  config.hpp
  elonacore.cpp
  set_option.cpp
Labels: bug

#274 Fix strange performance skill
  elonacore.cpp
  variables.hpp
Labels: bug

#276 Skip BOM at the beginning of text files
  config.cpp
  util.hpp
Labels: bug

#277 Fix performance hit by many damage popup
  draw.cpp
  draw.hpp
  initialize_map.cpp
Labels: bug

#278 Fix sound library
  CMakeLists.txt
  animation.cpp
  audio.cpp
  audio.hpp
  card.cpp
  ctrl_inventory.cpp
  elona.hpp
  elonacore.cpp
  init.cpp
  initialize_map.cpp
  input.cpp
  magic.cpp
  message.cpp
  proc_event.cpp
  set_option.cpp
  std.cpp
  talk_npc.cpp
  talk_unique.cpp
  tcg.cpp
  variables.hpp
  wish.cpp
Labels: bug

#280 Feature/fix number of channels
  audio.cpp
Labels: bug

#269 [WIP] Fix stack overflows in main game loop
  .gitignore
  CMakeLists.txt
  Makefile.win
  ctrl_inventory.cpp
  elonacore.cpp
  enums.hpp
  init.cpp
  initialize_map.cpp
  macro.hpp
  magic.cpp
  main.hpp
  set_option.cpp
  std.cpp
  talk.hpp
  talk_npc.cpp
  talk_unique.cpp
  variables.hpp
Labels: bug

#286 Refactor: Move methods to casino.cpp/casino_card.cpp
  CMakeLists.txt
  casino.cpp
  casino.hpp
  casino_card.cpp
  casino_card.hpp
  elonacore.cpp
  variables.hpp
Labels: refactoring

#287 Refactor: Move methods to fov.cpp
  CMakeLists.txt
  animation.cpp
  calc.cpp
  cell_draw.cpp
  draw.cpp
  elonacore.cpp
  fov.cpp
  fov.hpp
  magic.cpp
  map.cpp
  map.hpp
  message.cpp
  variables.hpp
Labels: refactoring

#288 Refactor: Move methods to ui.cpp/menu.cpp/main_menu.cpp/character_making.cpp
  CMakeLists.txt
  animation.cpp
  card.cpp
  character_making.cpp
  character_making.hpp
  ctrl_inventory.cpp
  draw.cpp
  draw.hpp
  elonacore.cpp
  enums.hpp
  init.cpp
  initialize_map.cpp
  magic.cpp
  main.hpp
  main_menu.cpp
  main_menu.hpp
  menu.cpp
  menu.hpp
  message.cpp
  proc_event.cpp
  set_option.cpp
  talk_npc.cpp
  talk_unique.cpp
  ui.cpp
  ui.hpp
  variables.hpp
Labels: refactoring

#289 Refactor: Move methods to blending.cpp/crafting.cpp
  CMakeLists.txt
  blending.cpp
  blending.hpp
  crafting.cpp
  crafting.hpp
  elonacore.cpp
  init.cpp
  input.cpp
  item.cpp
  main.hpp
  talk_unique.cpp
  variables.hpp
Labels: refactoring

#290 Refactor: Move methods to map.cpp and mapgen.cpp
  CMakeLists.txt
  elonacore.cpp
  initialize_map.cpp
  main.hpp
  map.cpp
  map.hpp
  mapgen.cpp
  mapgen.hpp
  variables.hpp
Labels: refactoring

#297 Refactor: Move methods to quest.cpp
  CMakeLists.txt
  elonacore.cpp
  initialize_map.cpp
  item.cpp
  magic.cpp
  menu.cpp
  proc_event.cpp
  quest.cpp
  quest.hpp
  talk_npc.cpp
  text.cpp
  variables.hpp
Labels: refactoring

#301 Refactor: Move methods into character.cpp/character_status.cpp/adventurer.cpp
  CMakeLists.txt
  ability.cpp
  adventurer.cpp
  adventurer.hpp
  ai.cpp
  blending.cpp
  building.cpp
  calc.cpp
  casino.cpp
  character.cpp
  character.hpp
  character_making.cpp
  character_status.cpp
  character_status.hpp
  crafting.cpp
  ctrl_inventory.cpp
  draw.cpp
  elonacore.cpp
  equipment.cpp
  equipment.hpp
  food.cpp
  init.cpp
  initialize_map.cpp
  item.cpp
  itemgen.cpp
  magic.cpp
  mapgen.cpp
  menu.cpp
  proc_event.cpp
  talk_npc.cpp
  talk_unique.cpp
  text.cpp
  variables.hpp
  wish.cpp
Labels: refactoring

#302 Refactor: move methods to buff.cpp
  buff.cpp
  buff.hpp
  command.cpp
  elonacore.cpp
  food.cpp
  magic.cpp
  variables.hpp
Labels: refactoring

#303 Refactor: move methods to ability.cpp
  ability.cpp
  ability.hpp
  crafting.cpp
  elonacore.cpp
  talk.cpp
  variables.hpp
Labels: refactoring

#285 Validate input used for filename more strictly
  character_making.cpp
  elonacore.cpp
  filesystem.cpp
  filesystem.hpp
  input.cpp
  input.hpp
  menu.cpp
  std.cpp
  util.hpp
  variables.hpp
  wish.cpp
Labels: bug

#306 Refactor: move methods to ui.cpp
  elonacore.cpp
  input.cpp
  ui.cpp
  ui.hpp
  variables.hpp
Labels: refactoring

#307 Refactor: move methods to element.cpp
  CMakeLists.txt
  element.cpp
  element.hpp
  elonacore.cpp
Labels: refactoring

#309 Refactor: move methods to ctrl_file.cpp
  ctrl_file.cpp
  ctrl_file.hpp
  elonacore.cpp
  variables.hpp
Labels: refactoring

#312 Fix infinite loop in inv_compress()
  item.cpp
  item.hpp
Labels: refactoring

#314 Fix DLL loading error
  deps/install.bat
Labels: bug

#316 Fix typo in Japanese
  buff.hpp
  data/book.txt
  data/item.lua
  god.cpp
  lang/jp/buff.lua
  magic.cpp
  trait.cpp
Labels: enhancement

#319 Refactor: move methods to draw.cpp
  character_making.cpp
  command.cpp
  draw.cpp
  draw.hpp
  elonacore.cpp
  init.cpp
  talk.cpp
  tcg.cpp
  variables.hpp
Labels: refactoring

#320 Refactor: move methods to turn_sequence.cpp
  CMakeLists.txt
  elonacore.cpp
  main.hpp
  menu.cpp
  menu.hpp
  turn_sequence.cpp
  turn_sequence.hpp
  variables.hpp
Labels: refactoring

#321 Refactor: move methods to network.cpp
  CMakeLists.txt
  command.cpp
  elonacore.cpp
  init.cpp
  menu.cpp
  network.cpp
  network.hpp
  set_option.cpp
  turn_sequence.cpp
  variables.hpp
  wish.cpp
Labels: refactoring

#325 Fix bad allocation when opening journal
  menu.cpp
Labels: bug

#327 Fix too many blank lines in journal
  std.cpp
Labels: bug

#329 Fix being unable to cancel number prompt
  input.cpp
Labels: bug

#330 Replace gfdec/gfdec2() with set_color_mod()
  animation.cpp
  draw.cpp
Labels: bug

#334 Delete unnecessary await()
  building.cpp
  character_status.cpp
  command.cpp
  elona.hpp
  elonacore.cpp
  initialize_map.cpp
  magic.cpp
  main_menu.cpp
  mapgen.cpp
  message.cpp
  text.cpp
Labels: bug

#336 Fix text color in feat menu
  menu.cpp
Labels: bug

#339 Add data/manual_{ENG,JP}.txt
  data/manual_ENG.txt
  data/manual_JP.txt
Labels: bug

#344 Fix glitch at PC's shop
  menu.cpp
Labels: bug

#345 Fix being unable to dig wall
  elonacore.cpp
Labels: bug

#347 Add options in game
  set_option.cpp
  std.cpp
Labels: enhancement

#352 Do not compress save data
  ctrl_file.cpp
  putit.hpp
Labels: bug

#353 Fix feat text color
  menu.cpp
  ui.cpp
Labels: bug

#354 Improve apppveyor.yml
  appveyor.yml
Labels: enhancement

#438 Add benchmark feature
  .travis.yml
  CMakeLists.txt
  Makefile
  Makefile.win
  appveyor.yml
  bench/ai.cpp
  bench/magic.cpp
  bench/util.cpp
  bench/util.hpp
  message.cpp
  snail/hsp/headless.cpp
  thirdparty/hayai/CMakeLists.txt
  thirdparty/hayai/hayai.hpp
  thirdparty/hayai/hayai_benchmarker.hpp
  thirdparty/hayai/hayai_clock.hpp
  thirdparty/hayai/hayai_compatibility.hpp
  thirdparty/hayai/hayai_console.hpp
  thirdparty/hayai/hayai_console_outputter.hpp
  thirdparty/hayai/hayai_default_test_factory.hpp
  thirdparty/hayai/hayai_fixture.hpp
  thirdparty/hayai/hayai_json_outputter.hpp
  thirdparty/hayai/hayai_junit_xml_outputter.hpp
  thirdparty/hayai/hayai_main.hpp
  thirdparty/hayai/hayai_outputter.hpp
  thirdparty/hayai/hayai_posix_main.cpp
  thirdparty/hayai/hayai_test.hpp
  thirdparty/hayai/hayai_test_descriptor.hpp
  thirdparty/hayai/hayai_test_factory.hpp
  thirdparty/hayai/hayai_test_result.hpp
Labels: enhancement
