Repository elonafoobar/elonafoobar, pull requests merged in 2018-12, with the labels that each got.

#1047 Fix not being able to choose correct ally
  src/ui/ui_menu_ctrl_ally.cpp
Labels: bugfix

#1037 Implement mod load order using dependencies
  CMakeLists.txt
  runtime/mods/core/mod.hcl
  runtime/mods/kiroku/mod.hcl
  src/filesystem.cpp
  src/init.cpp
  src/lib/topological_sorter.hpp
  src/lua_env/data_manager.cpp
  src/lua_env/mod_manager.cpp
  src/lua_env/mod_manager.hpp
  src/lua_env/mod_manifest.cpp
  src/lua_env/mod_manifest.hpp
  src/tests/data/mods/test_export_keys/mod.hcl
  src/tests/data/mods/test_i18n_a/mod.hcl
  src/tests/data/mods/test_i18n_b/mod.hcl
  src/tests/data/mods/test_require/mod.hcl
  src/tests/data/mods/test_require_chunks/mod.hcl
  src/tests/data/registry/chara/mod.hcl
  src/tests/data/registry/chara_defaults/mod.hcl
  src/tests/data/registry/chara_duplicate_key/mod.hcl
  src/tests/data/registry/chara_invalid_enum/mod.hcl
  src/tests/data/registry/invalid/mod.hcl
  src/tests/data/registry/item/mod.hcl
  src/tests/data/registry/putit/mod.hcl
  src/tests/data/registry/putit_b/mod.hcl
  src/tests/lua_mods.cpp
Labels: lua

#1036 Migrate usages of lang/ui.lua
  CMakeLists.txt
  android/app/src/main/java/xyz/ki/elonafoobar/SplashScreen.java
  runtime/__init__.lua
  runtime/lang/en/ui.lua
  runtime/lang/jp/ui.lua
  runtime/locale/en/chara.hcl
  runtime/locale/en/rank.hcl
  runtime/locale/en/status_ailment.hcl
  runtime/locale/en/ui.hcl
  runtime/locale/jp/chara.hcl
  runtime/locale/jp/rank.hcl
  runtime/locale/jp/status_ailment.hcl
  runtime/locale/jp/ui.hcl
  src/ability.cpp
  src/access_character_info.cpp
  src/activity.cpp
  src/buff.cpp
  src/cat.cpp
  src/cat.hpp
  src/character.cpp
  src/character_status.cpp
  src/command.cpp
  src/ctrl_inventory.cpp
  src/elonacore.cpp
  src/i18n.cpp
  src/i18n.hpp
  src/init.cpp
  src/init.hpp
  src/input.cpp
  src/item.cpp
  src/lua_env/lua_class/lua_class_character.cpp
  src/magic.cpp
  src/quest.cpp
  src/race.cpp
  src/set_item_info.cpp
  src/status_ailment.cpp
  src/talk.cpp
  src/talk_house_visitor.cpp
  src/talk_npc.cpp
  src/talk_unique.cpp
  src/testing.cpp
  src/text.cpp
  src/trait.cpp
  src/turn_sequence_pc_actions.cpp
  src/ui.cpp
  src/ui/ui_menu_character_sheet.cpp
  src/ui/ui_menu_charamake_gender.cpp
  src/ui/ui_menu_ctrl_ally.cpp
  src/ui/ui_menu_equipment.cpp
  src/ui/ui_menu_hire.cpp
  src/wish.cpp
Labels: I18N, refactoring

#1051 Fix crash from using Cat's Cradle
  src/character.cpp
  src/item.cpp
  src/tests/lua_handles.cpp
Labels: bugfix

#1049 Fix skyline packing algorithm
  src/pic_loader/pic_loader.hpp
Labels: bugfix

#1053 Split update_save_data() into each function handling only one version
  src/elona/Android.mk
  src/elona/CMakeLists.txt
  src/elona/command.cpp
  src/elona/elonacore.cpp
  src/elona/init.cpp
  src/elona/save.cpp
  src/elona/save.hpp
  src/elona/save_update.cpp
  src/elona/save_update.hpp
  src/elona/std.cpp
  src/elona/testing.cpp
  src/elona/turn_sequence.cpp
  src/elona/turn_sequence_pc_actions.cpp
  src/elona/variables.hpp
Labels: refactoring

#828 Improve portrait system
  runtime/mods/core/data.lua
  runtime/mods/core/data/chara.lua
  runtime/mods/core/data/portrait.lua
  runtime/mods/core/locale/en/lazy/scene.hsp
  runtime/mods/core/locale/jp/lazy/scene.hsp
  src/elona/access_character_info.cpp
  src/elona/character.cpp
  src/elona/character.hpp
  src/elona/character_making.cpp
  src/elona/command.cpp
  src/elona/data/init.cpp
  src/elona/data/types.cpp
  src/elona/data/types.hpp
  src/elona/data/types/type_character.cpp
  src/elona/data/types/type_character.hpp
  src/elona/data/types/type_portrait.cpp
  src/elona/data/types/type_portrait.hpp
  src/elona/draw.cpp
  src/elona/draw.hpp
  src/elona/elonacore.cpp
  src/elona/init.cpp
  src/elona/initialize_map.cpp
  src/elona/menu.cpp
  src/elona/pic_loader/pic_loader.cpp
  src/elona/pic_loader/pic_loader.hpp
  src/elona/save_update.cpp
  src/elona/talk.cpp
  src/elona/talk_unique.cpp
  src/elona/ui/ui_menu_character_sheet.cpp
  src/elona/variables.hpp
  src/elona/version.cpp.in
  src/tests/data/registry/chara/data.lua
  src/tests/data/registry/chara_portrait/data.lua
  src/tests/data/registry/chara_portrait/init.lua
  src/tests/data/registry/chara_portrait/mod.hcl
  src/tests/lua_data_character.cpp
  src/util/natural_order_comparator.hpp
Labels: bugfix, enhancement

#1057 Fix Unknown I18N ID: core.locale.rank._7._N
  src/elona/elonacore.cpp
Labels: bugfix

#1059 Add is_cancelable to DialogData, the flag whether you can cancel a talk
  src/elona/dialog/dialog_data.cpp
  src/elona/dialog/dialog_data.hpp
  src/elona/dialog/dialog_decoder.cpp
Labels: bugfix

#1069 Fix regenerated map not being rebuilt
  src/elona/ctrl_file.cpp
Labels: bugfix

#1067 Enhance message log
  src/elona/Android.mk
  src/elona/CMakeLists.txt
  src/elona/elonacore.cpp
  src/elona/init.cpp
  src/elona/initialize_map.cpp
  src/elona/message.cpp
  src/elona/message.hpp
  src/elona/message_log.cpp
  src/elona/message_log.hpp
  src/elona/ui/ui_menu_message_log.cpp
  src/elona/ui/ui_menu_message_log.hpp
Labels: enhancement

#1070 Fix selection key can select out-of-range choice
  src/elona/input.cpp
  src/elona/input.hpp
Labels: bugfix

#1068 Fix typo
  runtime/locale/jp/talk_npc.hcl
  runtime/locale/jp/talk_unique.hcl
  runtime/mods/core/locale/en/item.hcl
Labels: I18N, bugfix

#1071 Measure the elapsed time on testing in CI
  .travis.yml
  appveyor.yml
Labels: enhancement

#1060 Fix crash when you try to execute invalid lua snippet
  src/elona/character.cpp
  src/elona/ctrl_file.cpp
  src/elona/dialog/dialog_data.cpp
  src/elona/dialog/dialog_decoder.cpp
  src/elona/elonacore.cpp
  src/elona/i18n.hpp
  src/elona/init.cpp
  src/elona/lua_env/api_manager.cpp
  src/elona/lua_env/data_manager.cpp
  src/elona/lua_env/event_manager.cpp
  src/elona/lua_env/export_manager.cpp
  src/elona/lua_env/handle_manager.cpp
  src/elona/lua_env/interface.cpp
  src/elona/lua_env/interface.hpp
  src/elona/lua_env/lua_api/lua_api_common.hpp
  src/elona/lua_env/lua_api/lua_api_debug.cpp
  src/elona/lua_env/lua_api/lua_api_fov.cpp
  src/elona/lua_env/lua_api/lua_api_item.cpp
  src/elona/lua_env/lua_api/lua_api_magic.cpp
  src/elona/lua_env/lua_api/lua_api_skill.cpp
  src/elona/lua_env/lua_api/lua_api_trait.cpp
  src/elona/lua_env/lua_class/lua_class_ability.hpp
  src/elona/lua_env/lua_console.cpp
  src/elona/lua_env/lua_console.hpp
  src/elona/lua_env/lua_env.cpp
  src/elona/lua_env/lua_env.hpp
  src/elona/lua_env/mod_manager.cpp
  src/elona/testing.cpp
  src/elona/turn_sequence.cpp
  src/elona/turn_sequence_pc_actions.cpp
  src/elona/ui.cpp
  src/tests/lua_api.cpp
  src/tests/lua_callbacks.cpp
  src/tests/lua_data.cpp
  src/tests/lua_data_character.cpp
  src/tests/lua_data_item.cpp
  src/tests/lua_events.cpp
  src/tests/lua_exports.cpp
  src/tests/lua_handles.cpp
  src/tests/lua_mods.cpp
  src/tests/lua_serialization.cpp
  src/tests/util.cpp
Labels: bugfix

#1072 Add application icon for Windows
  CMakeLists.txt
  resources/icon.ico
  resources/icon128x128.png
  resources/icon16x16.png
  resources/icon192x192.png
  resources/icon24x24.png
  resources/icon256x256.png
  resources/icon32x32.png
  resources/icon40x40.png
  resources/icon48x48.png
  resources/icon64x64.png
  resources/icon96x96.png
  resources/icon_windows.rc
Labels: enhancement

#1076 Hotfix/0.3.1
  CHANGELOG-jp.md
  CHANGELOG.md
  CMakeLists.txt
  src/elona/audio.cpp
  src/elona/building.cpp
  src/elona/character.cpp
  src/elona/character_making.cpp
  src/elona/command.cpp
  src/elona/config/config.cpp
  src/elona/ctrl_file.cpp
  src/elona/draw.cpp
  src/elona/elonacore.cpp
  src/elona/filesystem.cpp
  src/elona/filesystem.hpp
  src/elona/hcl.hpp
  src/elona/i18n.cpp
  src/elona/init.cpp
  src/elona/initialize_map.cpp
  src/elona/keybind/keybind_manager.cpp
  src/elona/lua_env/api_manager.cpp
  src/elona/lua_env/data_manager.cpp
  src/elona/lua_env/loaded_chunk_cache.hpp
  src/elona/lua_env/lua_console.cpp
  src/elona/lua_env/lua_env.cpp
  src/elona/lua_env/mod_manager.cpp
  src/elona/magic.cpp
  src/elona/main_menu.cpp
  src/elona/save.cpp
  src/elona/save_update.cpp
  src/elona/spec.cpp
  src/elona/std.cpp
  src/elona/tcg.cpp
  src/elona/ui/ui_menu_npc_tone.cpp
  src/elona/util.hpp
  src/snail/Android.mk
  src/snail/filesystem.hpp
  src/snail/font.cpp
  src/snail/image.cpp
  src/util/Android.mk
  src/util/CMakeLists.txt
  src/util/filepathutil.cpp
  src/util/filepathutil.hpp
Labels: bugfix

#1087 Fix continent border being regarded as indoor
  runtime/mods/core/data/map.lua
  src/elona/save_update.cpp
  src/elona/version.cpp.in
Labels: bugfix

#1089 Fix Christmas festival items in Noyel not being removed completely
  src/elona/ctrl_file.cpp
  src/elona/initialize_map.cpp
  src/elona/map.cpp
  src/elona/map.hpp
  src/elona/talk_unique.cpp
Labels: bugfix

#1090 Fix map up/downstairs position
  src/elona/ctrl_file.cpp
  src/elona/map.cpp
  src/elona/map.hpp
  src/elona/save_update.cpp
  src/elona/version.cpp.in
Labels: bugfix

#1088 Fix wrong item name after trading items for "I want it!" quest
  runtime/data/lua/handle.lua
  src/tests/lua_handles.cpp
Labels: bugfix

#1095 Add missing map data of player-owned buildings
  runtime/mods/core/data/map.lua
  src/elona/area.cpp
Labels: bugfix

#1100 Fix diagonal move keys being bound wrong keys
  src/elona/keybind/keybind_actions.cpp
Labels: bug

#1101 Remove `auto_action` action and use `enter` instead
  runtime/locale/en/keybindings.hcl
  runtime/locale/jp/keybindings.hcl
  src/elona/keybind/keybind_actions.cpp
  src/elona/turn_sequence_pc_actions.cpp
Labels: bugfix

#1096 Enhance autopick feature
  runtime/locale/en/autopick.hcl
  runtime/locale/en/meta.hcl
  runtime/locale/jp/autopick.hcl
  runtime/locale/jp/meta.hcl
  src/elona/autopick.cpp
  src/elona/autopick.hpp
  src/elona/command.cpp
  src/elona/command.hpp
  src/elona/elonacore.cpp
  src/elona/turn_sequence.cpp
  src/elona/variables.hpp
Labels: enhancement

#1106 Make methods for each ibit() and ibitmod() calls
  src/elona/access_item_db.cpp
  src/elona/activity.cpp
  src/elona/blending.cpp
  src/elona/calc.cpp
  src/elona/command.cpp
  src/elona/ctrl_inventory.cpp
  src/elona/elonacore.cpp
  src/elona/enchantment.cpp
  src/elona/equipment.cpp
  src/elona/food.cpp
  src/elona/item.cpp
  src/elona/item.hpp
  src/elona/item_load_desc.cpp
  src/elona/itemgen.cpp
  src/elona/magic.cpp
  src/elona/quest.cpp
  src/elona/talk_npc.cpp
  src/elona/turn_sequence.cpp
  src/elona/ui.cpp
  src/elona/wish.cpp
  src/tests/serialization.cpp
Labels: refactoring

#1102 Use "key" global for some edge cases difficult to handle in keybinds
  src/elona/init.cpp
  src/elona/input.cpp
  src/elona/input.hpp
  src/elona/keybind/input_context.cpp
  src/elona/turn_sequence.cpp
  src/elona/turn_sequence_pc_actions.cpp
  src/elona/ui/ui_menu_character_sheet.cpp
Labels: bugfix

#1107 Fix broken build: replace ibit() with new methods
  src/elona/autopick.cpp
Labels: bugfix, build
