Repository elonafoobar/elonafoobar, pull requests merged in 2018-07, with the labels that each got.

#650 Refactor gmode()
  src/animation.cpp
  src/blending.cpp
  src/building.cpp
  src/casino.cpp
  src/casino_card.cpp
  src/cell_draw.cpp
  src/character_making.cpp
  src/crafting.cpp
  src/ctrl_inventory.cpp
  src/draw.cpp
  src/elona.hpp
  src/elonacore.cpp
  src/input.cpp
  src/magic.cpp
  src/main_menu.cpp
  src/menu.cpp
  src/message.cpp
  src/network.cpp
  src/proc_event.cpp
  src/set_option.cpp
  src/snail/hsp.hpp
  src/snail/hsp/headless.cpp
  src/snail/hsp/sdl.cpp
  src/std.cpp
  src/talk.cpp
  src/tcg.cpp
  src/ui.cpp
Labels: refactoring

#644 Asset system
  runtime/assets.hcl
  src/blending.cpp
  src/cell_draw.cpp
  src/ctrl_inventory.cpp
  src/draw.cpp
  src/draw.hpp
  src/elonacore.cpp
  src/init.cpp
  src/input.cpp
  src/menu.cpp
  src/message.cpp
  src/talk.cpp
  src/testing.cpp
  src/ui.cpp
Labels: customization, enhancement

#652 Fix grotate()
  src/animation.cpp
Labels: bug

#653 Add translation static analyzer
  .gitignore
  Makefile
  doc/README.md
  doc/config.ld
  doc/ldoc.ltp
  docs/classes/LuaCharacter.html
  docs/classes/LuaItem.html
  docs/classes/LuaPosition.html
  docs/examples/life.lua.html
  docs/index.html
  docs/modules/Chara.html
  docs/modules/Debug.html
  docs/modules/Enums.html
  docs/modules/Event.EventKind.html
  docs/modules/Event.html
  docs/modules/FOV.html
  docs/modules/GUI.html
  docs/modules/Item.html
  docs/modules/Iter.html
  docs/modules/Magic.html
  docs/modules/Map.html
  docs/modules/Pos.html
  docs/modules/Rand.html
  docs/modules/Skill.html
  docs/modules/World.html
  docs/readme.md
  docs/topics/readme.md.html
  src/building.cpp
  src/dmgheal.cpp
  src/elonacore.cpp
  src/quest.cpp
  tools/i18n_checker/spec/scanner_spec.lua
  tools/i18n_checker/src/hclua.lua
  tools/i18n_checker/src/hclua/decoder.lua
  tools/i18n_checker/src/hclua/lexer.lua
  tools/i18n_checker/src/hclua/parser.lua
  tools/i18n_checker/src/hclua/util.lua
  tools/i18n_checker/src/i18n_checker/argparse.lua
  tools/i18n_checker/src/i18n_checker/checker.lua
  tools/i18n_checker/src/i18n_checker/format.lua
  tools/i18n_checker/src/i18n_checker/fs.lua
  tools/i18n_checker/src/i18n_checker/locale.lua
  tools/i18n_checker/src/i18n_checker/main.lua
  tools/i18n_checker/src/i18n_checker/runner.lua
  tools/i18n_checker/src/i18n_checker/scanner.lua
  tools/i18n_checker/src/i18n_checker/utils.lua
  tools/i18n_checker/src/inspect.lua
Labels: I18N, customization, enhancement

#629 I18N: Externalize character making strings
  runtime/locale/en/chara_making.hcl
  runtime/locale/jp/chara_making.hcl
  src/character_making.cpp
Labels: I18N

#627 I18N: Externalize strings in text.cpp
  doc/topics/i18n_functions.md
  runtime/locale/en/chara.hcl
  runtime/locale/en/item.hcl
  runtime/locale/en/map.hcl
  runtime/locale/en/scenario.hcl
  runtime/locale/en/skill.hcl
  runtime/locale/en/ui.hcl
  runtime/locale/jp/chara.hcl
  runtime/locale/jp/item.hcl
  runtime/locale/jp/map.hcl
  runtime/locale/jp/scenario.hcl
  runtime/locale/jp/skill.hcl
  runtime/locale/jp/ui.hcl
  src/access_character_info.cpp
  src/character.cpp
  src/elonacore.cpp
  src/i18n.cpp
  src/i18n.hpp
  src/initialize_map.cpp
  src/text.cpp
Labels: I18N

#623 I18N: Externalize event/random event strings
  CMakeLists.txt
  runtime/locale/en/common.hcl
  runtime/locale/en/event.hcl
  runtime/locale/jp/common.hcl
  runtime/locale/jp/event.hcl
  src/elonacore.cpp
  src/proc_event.cpp
  src/proc_random_event.cpp
  src/variables.hpp
Labels: I18N, refactoring

#647 I18N: Externalize other god related strings
  runtime/locale/en/god.hcl
  runtime/locale/jp/god.hcl
  src/god.cpp
  src/god.hpp
  src/menu.cpp
Labels: I18N

#626 I18N: Externalize enchantment/item description strings
  runtime/locale/en/enchantment.hcl
  runtime/locale/en/item.hcl
  runtime/locale/jp/enchantment.hcl
  runtime/locale/jp/item.hcl
  src/card.cpp
  src/ctrl_inventory.cpp
  src/elonacore.cpp
  src/enchantment.cpp
  src/enchantment.hpp
  src/main.hpp
  src/menu.cpp
  src/menu.hpp
  src/text.cpp
  src/variables.hpp
Labels: I18N

#642 I18N: Externalize NPC dialog strings
  runtime/locale/en/talk_npc.hcl
  runtime/locale/en/talk_visitor.hcl
  runtime/locale/jp/talk_npc.hcl
  runtime/locale/jp/talk_visitor.hcl
  src/talk.cpp
  src/talk.hpp
  src/talk_npc.cpp
Labels: I18N, refactoring

#656 Separate Lua Store into map-local and global and add map loading callbacks
  .luacheckrc
  CMakeLists.txt
  doc/README.md
  doc/api/event_eventkind.luadoc
  doc/examples/life.lua
  runtime/data/script/all_magic.lua
  src/elonacore.cpp
  src/initialize_map.cpp
  src/lua_env/event_manager.cpp
  src/lua_env/event_manager.hpp
  src/lua_env/lua_env.cpp
  src/lua_env/lua_env.hpp
  src/lua_env/lua_store.cpp
  src/lua_env/lua_store.hpp
  src/testing.cpp
  src/testing.hpp
  src/tests/lua_callbacks.cpp
  src/tests/lua_events.cpp
  src/tests/lua_handles.cpp
  src/tests/lua_mods.cpp
  src/tests/lua_serialization.cpp
  src/tests/lua_store.cpp
Labels: enhancement, lua

#636 I18N: Externalize trait data
  runtime/locale/en/trait.hcl
  runtime/locale/jp/trait.hcl
  src/character.cpp
  src/character_status.cpp
  src/food.cpp
  src/lua_env/lua_api.cpp
  src/magic.cpp
  src/menu.cpp
  src/tests/i18n.cpp
  src/thirdparty/microhil/hil.hpp
  src/trait.cpp
  src/trait.hpp
Labels: I18N, refactoring

#622 I18N: Externalize magic-related strings
  runtime/locale/en/common.hcl
  runtime/locale/en/magic.hcl
  runtime/locale/jp/common.hcl
  runtime/locale/jp/magic.hcl
  src/i18n.cpp
  src/i18n.hpp
  src/magic.cpp
  src/thirdparty/microhcl/hcl.hpp
Labels: I18N

#648 I18N: Externalize strings in ctrl_inventory
  runtime/locale/en/ctrl_inventory.hcl
  runtime/locale/jp/ctrl_inventory.hcl
  src/ctrl_inventory.cpp
Labels: I18N

#658 Prepend functions in inline lua with "local"
  src/lua_env/lua_env.cpp
Labels: bug, bugfix, lua

#615 I18N: Externalize crafting-related strings
  runtime/locale/en/crafting.hcl
  runtime/locale/en/material.hcl
  runtime/locale/jp/crafting.hcl
  runtime/locale/jp/material.hcl
  src/crafting.cpp
Labels: I18N

#587 I18N: Externalize blending-related strings
  doc/api/classes/LuaItem.luadoc
  runtime/locale/en/blending.hcl
  runtime/locale/jp/blending.hcl
  src/blending.cpp
  src/lua_env/lua_api.cpp
Labels: I18N, enhancement

#640 I18N: Externalize continuous action strings
  CMakeLists.txt
  runtime/locale/en/action.hcl
  runtime/locale/en/activity.hcl
  runtime/locale/en/quest.hcl
  runtime/locale/jp/action.hcl
  runtime/locale/jp/activity.hcl
  runtime/locale/jp/quest.hcl
  src/activity.cpp
  src/activity.hpp
  src/ai.cpp
  src/blending.cpp
  src/building.cpp
  src/character.cpp
  src/command.cpp
  src/dmgheal.cpp
  src/elonacore.cpp
  src/food.cpp
  src/food.hpp
  src/i18n.cpp
  src/i18n.hpp
  src/item.cpp
  src/magic.cpp
  src/quest.cpp
  src/status_ailment.cpp
  src/talk.cpp
  src/talk_npc.cpp
  src/tests/i18n_builtins.cpp
  src/turn_sequence.cpp
  src/variables.hpp
Labels: I18N, refactoring

#659 I18N: Externalize menu strings
  runtime/locale/en/ui.hcl
  runtime/locale/jp/ctrl_inventory.hcl
  runtime/locale/jp/ui.hcl
  src/menu.cpp
  src/ui.cpp
Labels: I18N

#661 I18N: Externalize action strings
  runtime/locale/en/action.hcl
  runtime/locale/en/action_use.hcl
  runtime/locale/en/activity.hcl
  runtime/locale/en/blending.hcl
  runtime/locale/en/ctrl_inventory.hcl
  runtime/locale/jp/action.hcl
  runtime/locale/jp/action_use.hcl
  runtime/locale/jp/activity.hcl
  runtime/locale/jp/blending.hcl
  runtime/locale/jp/ctrl_inventory.hcl
  src/activity.cpp
  src/blending.cpp
  src/command.cpp
  src/ctrl_inventory.cpp
  src/dmgheal.cpp
  src/elonacore.cpp
  src/menu.cpp
  src/turn_sequence.cpp
Labels: I18N, bugfix

#662 I18N: Externalize TCG-related strings
  runtime/locale/en/tcg.hcl
  runtime/locale/jp/tcg.hcl
  src/tcg.cpp
Labels: I18N

#643 I18N: Externalize unique NPC dialog strings
  runtime/locale/en/quest.hcl
  runtime/locale/en/talk_unique.hcl
  runtime/locale/jp/quest.hcl
  runtime/locale/jp/talk_unique.hcl
  src/dmgheal.cpp
  src/talk.cpp
  src/talk.hpp
  src/talk_npc.cpp
  src/talk_unique.cpp
Labels: I18N, refactoring

#655 Add executable directory to package.path
  src/bench/lua_callbacks.cpp
  src/building.cpp
  src/character.cpp
  src/character_making.cpp
  src/ctrl_file.cpp
  src/dmgheal.cpp
  src/elonacore.cpp
  src/filesystem.cpp
  src/filesystem.hpp
  src/init.cpp
  src/initialize_map.cpp
  src/item.cpp
  src/itemgen.cpp
  src/lua_env/lua_api.cpp
  src/lua_env/lua_env.cpp
  src/lua_env/lua_env.hpp
  src/testing.cpp
  src/tests/lua_api.cpp
  src/tests/lua_callbacks.cpp
  src/tests/lua_handles.cpp
  src/tests/lua_serialization.cpp
  src/turn_sequence.cpp
Labels: bugfix, lua

#676 Use tsl::ordered_map instead of std::unordered_map in HCL objects
  README-jp.md
  README.md
  runtime/locale/en/config.hcl
  runtime/locale/jp/config.hcl
  runtime/mods/core/config/config_def.hcl
  src/config.cpp
  src/config.hpp
  src/config_def.cpp
  src/config_def.hpp
  src/draw.cpp
  src/hcl.hpp
  src/i18n.cpp
  src/i18n.hpp
  src/set_option.cpp
  src/spec.cpp
  src/spec.hpp
  src/tests/spec.cpp
  src/thirdparty/microhcl/hcl.hpp
  src/thirdparty/ordered_map/LICENSE
  src/thirdparty/ordered_map/ordered_hash.h
  src/thirdparty/ordered_map/ordered_map.h
  src/thirdparty/ordered_map/ordered_set.h
  src/ui.cpp
Labels: bugfix

#669 Allow number rollover in number input prompt
  src/ctrl_inventory.cpp
  src/input.cpp
  src/lua_env/lua_api.cpp
Labels: bugfix

#670 Replace message mark widthwise instead of bytewise
  doc/api/gui.luadoc
  src/lua_env/lua_api.cpp
  src/message.cpp
  src/util.hpp
Labels: bugfix

#671 [WIP] Load mods besides "core"
  doc/api/event_eventkind.luadoc
  runtime/mods/kiroku/init.lua
  src/init.cpp
  src/lua_env/event_manager.cpp
  src/lua_env/event_manager.hpp
  src/lua_env/lua_api.cpp
  src/lua_env/lua_api.hpp
  src/lua_env/lua_env.cpp
  src/lua_env/lua_env.hpp
  src/testing.cpp
  src/tests/data/mods/test/init.lua
  src/tests/lua_api.cpp
Labels: customization, enhancement, lua

#677 Create new data storage format and registry
  .travis.yml
  CMakeLists.txt
  doc/api/enums.luadoc
  runtime/data/character.lua
  runtime/data/lua/enums.lua
  runtime/data/lua/handle.lua
  runtime/data/lua/hclua.lua
  runtime/data/lua/hclua/decoder.lua
  runtime/data/lua/hclua/lexer.lua
  runtime/data/lua/hclua/parser.lua
  runtime/data/lua/hclua/util.lua
  runtime/data/lua/init.lua
  runtime/data/lua/inspect.lua
  runtime/data/lua/iter.lua
  runtime/data/lua/readonly.lua
  runtime/data/lua/table.lua
  runtime/mods/core/data/chara.hcl
  runtime/mods/core/init.lua
  src/bench/lion.cpp
  src/character.cpp
  src/character.hpp
  src/config.cpp
  src/config.hpp
  src/enums.hpp
  src/init.cpp
  src/init.hpp
  src/lion.hpp
  src/lua_env/handle_manager.cpp
  src/lua_env/lua_api.cpp
  src/lua_env/lua_api.hpp
  src/lua_env/lua_env.cpp
  src/lua_env/lua_env.hpp
  src/lua_env/lua_registry.cpp
  src/lua_env/lua_registry.hpp
  src/map_cell.hpp
  src/spec_load.cpp
  src/testing.cpp
  src/tests/data/registry/chara.hcl
  src/tests/data/registry/chara_defaults.hcl
  src/tests/data/registry/chara_duplicate_key.hcl
  src/tests/data/registry/chara_invalid_enum.hcl
  src/tests/data/registry/invalid.hcl
  src/tests/data/registry/putit.hcl
  src/tests/lua/chara.lua
  src/tests/lua_api.cpp
  src/tests/lua_registry.cpp
  src/tests/lua_registry_character.cpp
  tools/i18n_checker/src/hclua
  tools/i18n_checker/src/hclua.lua
Labels: customization, enhancement

#654 Refactor animation
  runtime/assets.hcl
  src/activity.cpp
  src/ai.cpp
  src/animation.cpp
  src/animation.hpp
  src/command.cpp
  src/dmgheal.cpp
  src/draw.cpp
  src/draw.hpp
  src/elonacore.cpp
  src/god.cpp
  src/magic.cpp
  src/proc_event.cpp
  src/talk.cpp
Labels: refactoring

#681 Fix wrong condition checking if all mods have been scanned
  src/lua_env/lua_env.cpp
Labels: bugfix

#683 Delete verbose log to stderr
  src/draw.cpp
  src/initialize_map.cpp
  src/std.cpp
  src/turn_sequence.cpp
Labels: refactoring

#684 Fix wrong macro name(gdata_pc_[xy]_in_world_map)
  src/building.cpp
  src/elonacore.cpp
  src/gdata.hpp
  src/init.cpp
  src/initialize_map.cpp
  src/mapgen.cpp
  src/talk_npc.cpp
Labels: refactoring

#686 Fix save directory
  src/init.cpp
Labels: bugfix

#685 Add sprite packer for loading many individual sprites
  CMakeLists.txt
  runtime/mods/core/data/chara_chip.hcl
  src/building.cpp
  src/casino_card.cpp
  src/cell_draw.cpp
  src/character_making.cpp
  src/draw.cpp
  src/draw.hpp
  src/elonacore.cpp
  src/hcl.hpp
  src/init.cpp
  src/item.cpp
  src/lion.hpp
  src/menu.cpp
  src/pic_loader/extent.hpp
  src/pic_loader/pic_loader.cpp
  src/pic_loader/pic_loader.hpp
  src/shared_id.hpp
  src/snail/Android.mk
  src/snail/application/headless.cpp
  src/snail/application/headless.hpp
  src/snail/hsp/headless.cpp
  src/snail/renderer.hpp
  src/snail/renderer/headless.cpp
  src/snail/renderer/sdl.cpp
  src/snail/window.cpp
  src/snail/window.hpp
  src/snail/window/headless.cpp
  src/snail/window/headless.hpp
  src/snail/window/sdl.cpp
  src/snail/window/sdl.hpp
  src/spec_load.cpp
  src/talk.cpp
  src/tcg.cpp
  src/turn_sequence.cpp
  src/turn_sequence.hpp
  src/variables.hpp
Labels: customization, enhancement

#690 Add positional audio/sound file definition
  CMakeLists.txt
  runtime/data/lua/private/register_data.lua
  runtime/locale/en/config.hcl
  runtime/locale/jp/config.hcl
  runtime/mods/core/config/config_def.hcl
  runtime/mods/core/data/sound.hcl
  src/animation.cpp
  src/audio.cpp
  src/audio.hpp
  src/character.hpp
  src/db_sound.cpp
  src/db_sound.hpp
  src/dmgheal.cpp
  src/elonacore.cpp
  src/filesystem.cpp
  src/filesystem.hpp
  src/init.cpp
  src/lion.hpp
  src/magic.cpp
  src/optional.hpp
  src/snail/audio.hpp
  src/snail/audio/headless.cpp
  src/snail/audio/sdl.cpp
  src/tests/lua_registry.cpp
Labels: bugfix, customization, enhancement

#692 Externalize music as definition files
  CMakeLists.txt
  runtime/data/scene1.hsp
  runtime/data/scene2.hsp
  runtime/mods/core/data/music.hcl
  src/audio.cpp
  src/audio.hpp
  src/casino.cpp
  src/command.cpp
  src/db_music.cpp
  src/db_music.hpp
  src/dmgheal.cpp
  src/elonacore.cpp
  src/init.cpp
  src/lion.hpp
  src/main_menu.cpp
  src/proc_event.cpp
  src/quest.cpp
  src/snail/detail/sdl_impl.cpp
  src/testing.cpp
  src/variables.hpp
Labels: customization, enhancement

#695 Refactor lua_env to have clearer separation of responsibility
  CMakeLists.txt
  src/access_character_info.cpp
  src/bench/lion.cpp
  src/bench/lua_callbacks.cpp
  src/building.cpp
  src/cat.hpp
  src/character.cpp
  src/character_making.cpp
  src/ctrl_file.cpp
  src/elonacore.cpp
  src/i18n.hpp
  src/init.cpp
  src/initialize_map.cpp
  src/item.cpp
  src/itemgen.cpp
  src/lion.hpp
  src/lua_env/api_manager.cpp
  src/lua_env/api_manager.hpp
  src/lua_env/event_manager.cpp
  src/lua_env/event_manager.hpp
  src/lua_env/export_manager.cpp
  src/lua_env/export_manager.hpp
  src/lua_env/handle_manager.cpp
  src/lua_env/handle_manager.hpp
  src/lua_env/lua_env.cpp
  src/lua_env/lua_env.hpp
  src/lua_env/mod_manager.cpp
  src/lua_env/mod_manager.hpp
  src/lua_env/registry_manager.cpp
  src/lua_env/registry_manager.hpp
  src/testing.cpp
  src/tests/data/mods/test_export_keys/init.lua
  src/tests/data/mods/test_require/init.lua
  src/tests/lua_api.cpp
  src/tests/lua_callbacks.cpp
  src/tests/lua_events.cpp
  src/tests/lua_handles.cpp
  src/tests/lua_mods.cpp
  src/tests/lua_registry.cpp
  src/tests/lua_registry_character.cpp
  src/tests/lua_serialization.cpp
Labels: lua, refactoring

#702 Fix gold/platinum overflow
  src/activity.cpp
  src/ai.cpp
  src/character_status.cpp
  src/character_status.hpp
  src/command.cpp
  src/ctrl_file.cpp
  src/ctrl_inventory.cpp
  src/elonacore.cpp
  src/init.cpp
  src/itemgen.cpp
  src/magic.cpp
  src/proc_random_event.cpp
  src/talk.cpp
  src/talk_npc.cpp
Labels: bugfix

#704 Implement house board
  src/building.cpp
  src/building.hpp
  src/elonacore.cpp
  src/snail/application/sdl.cpp
  src/snail/input.cpp
  src/snail/input.hpp
  src/std.cpp
  src/variables.hpp
Labels: enhancement

#708 Adjust JP translation for change material
  runtime/locale/jp/magic.hcl
Labels: bugfix

#707 Add growth of luck buff
  runtime/data/buff.lua
  runtime/graphic/bufficon.png
  runtime/lang/en/buff.lua
  runtime/lang/jp/buff.lua
  src/ability.cpp
  src/buff.hpp
  src/character.cpp
  src/init.cpp
Labels: bugfix
