Repository elonafoobar/elonafoobar, pull requests merged in 2018-11, with the labels that each got.

#997 Restore behavior of Shift when running into NPCs
  src/command.cpp
  src/elonacore.cpp
  src/input.cpp
  src/input.hpp
  src/variables.hpp
Labels: bugfix

#995 Add option to skip confirm at shop
  runtime/config.hcl
  runtime/locale/en/config.hcl
  runtime/locale/jp/config.hcl
  runtime/mods/core/config/config_def.hcl
  src/config/config.cpp
  src/config/config.hpp
  src/ctrl_inventory.cpp
Labels: enhancement

#994 Copy boost::random::uniform_int_distribution and use it instead of std's
  README-jp.md
  README.md
  src/random.hpp
  src/thirdparty/boostrandom/LICENSE_1_0.txt
  src/thirdparty/boostrandom/detail/signed_unsigned_tools.hpp
  src/thirdparty/boostrandom/traits.hpp
  src/thirdparty/boostrandom/uniform_int_distribution.hpp
Labels: bugfix

#993 Fix shortcut representation for players
  runtime/locale/en/ctrl_inventory.hcl
  runtime/locale/jp/ctrl_inventory.hcl
  src/ctrl_inventory.cpp
  src/keybind/keybind.cpp
  src/keybind/keybind.hpp
  src/ui/ui_menu_keybindings.cpp
  src/ui/ui_menu_skills.cpp
  src/ui/ui_menu_spells.cpp
Labels: bugfix

#998 Add #if directive to suppress warnings
  src/defines.hpp
  src/shared_id.hpp
Labels: refactoring

#999 Translate or fix typo
  runtime/lang/en/character.lua
  runtime/locale/en/card_info.hcl
  runtime/locale/en/chara.hcl
  runtime/locale/en/enchantment.hcl
  runtime/locale/en/keybindings.hcl
  runtime/locale/en/map.hcl
  runtime/locale/en/misc.hcl
  runtime/locale/en/win.hcl
  runtime/locale/jp/item.hcl
  runtime/locale/jp/keybindings.hcl
  runtime/locale/jp/map.hcl
  runtime/locale/jp/misc.hcl
  runtime/locale/jp/win.hcl
  runtime/mods/core/data/chara.lua
  runtime/mods/core/data/chara_chip.lua
  src/elonacore.cpp
  src/mapgen.cpp
Labels: I18N

#1001 Adjust chain mail's stack height
  runtime/mods/core/data/item_chip.lua
Labels: bugfix

#1002 Fix food not getting rotten sometimes if you believe in Kumiromi
  src/elonacore.cpp
  src/food.cpp
  src/food.hpp
  src/initialize_map.cpp
  src/variables.hpp
Labels: bugfix

#1004 Improve shadow graphics
  runtime/graphic/interface_ex1.png
  runtime/graphic/interface_ex2.png
  runtime/graphic/interface_ex3.png
Labels: enhancement

#1003 Clean up unused code
  src/ai.cpp
  src/calc.cpp
  src/casino.cpp
  src/casino_card.cpp
  src/character.cpp
  src/command.cpp
  src/elonacore.cpp
  src/food.cpp
  src/init.cpp
  src/initialize_map.cpp
  src/input.cpp
  src/menu.cpp
  src/menu.hpp
  src/network.cpp
  src/network.hpp
  src/turn_sequence.cpp
  src/ui/ui_menu_character_sheet.cpp
  src/ui/ui_menu_chat_history.cpp
  src/ui/ui_menu_config.cpp
  src/ui/ui_menu_equipment.cpp
  src/ui/ui_menu_feats.cpp
  src/ui/ui_menu_journal.cpp
  src/ui/ui_menu_materials.cpp
  src/ui/ui_menu_message_log.cpp
  src/ui/ui_menu_skills.cpp
  src/ui/ui_menu_spells.cpp
  src/ui/ui_menu_town_chart.cpp
  src/ui/ui_menu_town_economy.cpp
  src/ui/ui_menu_town_politics.cpp
  src/variables.hpp
  src/wish.cpp
Labels: refactoring

#1007 Fix textbox input behavior
  src/snail/hsp/sdl.cpp
  src/snail/input.cpp
Labels: bugfix

#1009 Delete src/get_random_item_id.cpp, no longer used
  CMakeLists.txt
  src/get_random_item_id.cpp
Labels: refactoring

#1008 Reduce compiler warnings
  src/config/config_menu.hpp
  src/keybind/input_context.hpp
  src/keybind/keybind.cpp
  src/snail/application/sdl.cpp
  src/snail/touch_input/headless.cpp
  src/snail/window/headless.cpp
  src/tests/lua_callbacks.cpp
  src/tests/lua_handles.cpp
  src/ui/ui_menu_crafting.cpp
Labels: refactoring

#1011 Migrate CatDB to LuaLazyCache
  runtime/data/ability.lua
  runtime/data/fish.lua
  runtime/data/item_material.lua
  runtime/data/trait.lua
  runtime/mods/core/data.lua
  runtime/mods/core/data/ability.lua
  runtime/mods/core/data/fish.lua
  runtime/mods/core/data/god.lua
  runtime/mods/core/data/item_material.lua
  runtime/mods/core/data/trait.lua
  src/ability.cpp
  src/ability.hpp
  src/activity.cpp
  src/activity.hpp
  src/calc.cpp
  src/cell_draw.cpp
  src/data/init.cpp
  src/data/lua_lazy_cache.hpp
  src/data/types.cpp
  src/data/types.hpp
  src/data/types/type_ability.cpp
  src/data/types/type_ability.hpp
  src/data/types/type_fish.cpp
  src/data/types/type_fish.hpp
  src/data/types/type_god.cpp
  src/data/types/type_god.hpp
  src/data/types/type_item_material.cpp
  src/data/types/type_item_material.hpp
  src/data/types/type_trait.cpp
  src/data/types/type_trait.hpp
  src/element.cpp
  src/elonacore.cpp
  src/fish.cpp
  src/fish.hpp
  src/god.cpp
  src/god.hpp
  src/init.cpp
  src/item_material.cpp
  src/item_material.hpp
  src/itemgen.cpp
  src/lua_env/config_table.hpp
  src/lua_env/enums/enums.cpp
  src/lua_env/enums/enums.hpp
  src/magic.cpp
  src/menu.cpp
  src/trait.cpp
  src/trait.hpp
Labels: customization, refactoring

#1012 Migrate RaceDB to LuaLazyCache
  runtime/data/race.lua
  runtime/mods/core/data.lua
  runtime/mods/core/data/chara.lua
  runtime/mods/core/data/race.lua
  src/ai.cpp
  src/building.cpp
  src/character.cpp
  src/character.hpp
  src/character_status.cpp
  src/data/init.cpp
  src/data/types.cpp
  src/data/types.hpp
  src/data/types/type_race.cpp
  src/data/types/type_race.hpp
  src/elonacore.cpp
  src/equipment.cpp
  src/god.cpp
  src/init.cpp
  src/magic.cpp
  src/mef.cpp
  src/proc_event.cpp
  src/race.cpp
  src/race.hpp
  src/ui/ui_menu_character_sheet.cpp
  src/ui/ui_menu_charamake_race.cpp
  src/ui/ui_menu_ctrl_ally.cpp
  src/variables.hpp
  src/version.cpp.in
Labels: customization, refactoring

#1013 Migrate ClassDB to LuaLazyCache
  runtime/data/class.lua
  runtime/mods/core/data.lua
  runtime/mods/core/data/chara.lua
  runtime/mods/core/data/class.lua
  src/class.cpp
  src/class.hpp
  src/data/init.cpp
  src/data/types.cpp
  src/data/types.hpp
  src/data/types/type_class.cpp
  src/data/types/type_class.hpp
  src/elonacore.cpp
  src/init.cpp
  src/ui/ui_menu_charamake_class.cpp
  src/version.cpp.in
Labels: customization, refactoring

#1024 Fix ether disease progress advancing too much
  src/character_status.cpp
Labels: bugfix

#1022 Fix crash caused by missing bed graphics
  runtime/mods/core/data/item_chip.lua
  src/elonacore.cpp
  src/version.cpp.in
Labels: bugfix

#1026 Add option "foobar.skip_overcasting_warning"
  runtime/config.hcl
  runtime/locale/en/config.hcl
  runtime/locale/jp/config.hcl
  runtime/mods/core/config/config_def.hcl
  src/config/config.cpp
  src/config/config.hpp
  src/elonacore.cpp
Labels: enhancement

#1027 Fix inner ID of item chip and character chip
  src/data/types/type_chara_chip.cpp
  src/data/types/type_item_chip.cpp
Labels: bugfix

#1028 Check whether the save is compatible with the running Elona
  src/elonacore.cpp
Labels: bugfix

#1029 Do not output meaningless keybind error when no input is passed
  src/keybind/keybind.cpp
Labels: bugfix

#1033 Fix wrong sound when you kill someone or pick up something
  src/audio.cpp
Labels: bugfix

#1032 Fix various typo and l10n error
  runtime/locale/en/config.hcl
  runtime/locale/en/trait.hcl
  runtime/locale/jp/adventurer.hcl
  runtime/locale/jp/keybindings.hcl
  runtime/mods/core/locale/en/chara.hcl
  runtime/mods/core/locale/en/class.hcl
  runtime/mods/core/locale/en/item.hcl
  src/food.cpp
  src/input.cpp
  src/talk_unique.cpp
Labels: I18N, bugfix

#1042 Move the position of the crypt of the damned right
  runtime/mods/core/data/map.lua
Labels: bugfix

#1041 Add more option descriptions in Japanese
  runtime/locale/en/config.hcl
  runtime/locale/jp/config.hcl
Labels: I18N, enhancement
