Repository elonafoobar/elonafoobar, pull requests merged in 2018-08, with the labels that each got.

#712 Apply color modifier to source buffer managed by pic_loader
  src/draw.cpp
Labels: bugfix

#717 Fix various I18N errors
  runtime/locale/en/ctrl_inventory.hcl
  runtime/locale/en/food.hcl
  runtime/locale/jp/adventurer.hcl
  runtime/locale/jp/ctrl_inventory.hcl
  runtime/locale/jp/food.hcl
  src/elonacore.cpp
Labels: I18N, bugfix

#720 Fix glitch in [w]ear menu
  src/ui.cpp
Labels: bugfix, refactoring

#724 Fix check for home departure being of wrong type
  src/elonacore.cpp
Labels: bugfix

#735 Implement translation loading across mods
  runtime/mods/kiroku/init.lua
  runtime/mods/kiroku/locale/en/kiroku.hcl
  runtime/mods/kiroku/locale/jp/kiroku.hcl
  src/i18n.cpp
  src/i18n.hpp
  src/init.cpp
  src/lua_env/mod_manager.hpp
  src/testing.cpp
  src/testing.hpp
  src/tests/data/mods/test_i18n_a/locale/jp/test.hcl
  src/tests/data/mods/test_i18n_b/locale/jp/test.hcl
  src/tests/i18n.cpp
  src/tests/i18n_regressions.cpp
  src/tests/lua/i18n.lua
  src/tests/util.cpp
Labels: I18N, customization, lua

#739 Fix text color at material spot
  runtime/locale/jp/activity.hcl
  src/activity.cpp
Labels: bugfix

#737 Fix random event's title being empty
  CMakeLists.txt
  src/elonacore.cpp
  src/proc_event.cpp
  src/random_event.cpp
  src/random_event.hpp
  src/variables.hpp
Labels: bugfix

#741 Fix eating effect
  doc/api/classes/LuaCharacter.luadoc
  runtime/data/lua/enums.lua
  runtime/mods/core/exports/eating_effect.lua
  src/lua_env/api_manager.cpp
  src/tests/lua/classes/LuaCharacter.lua
Labels: bugfix

#742 Add item.hcl
  CMakeLists.txt
  runtime/data/item.lua
  runtime/data/lua/private/register_data.lua
  runtime/mods/core/data.hcl
  runtime/mods/core/data/item.hcl
  src/access_item_db.cpp
  src/adventurer.cpp
  src/ai.cpp
  src/animation.cpp
  src/blending.cpp
  src/building.cpp
  src/calc.cpp
  src/character.cpp
  src/command.cpp
  src/ctrl_inventory.cpp
  src/db_item.cpp
  src/db_item.hpp
  src/draw.cpp
  src/elonacore.cpp
  src/enchantment.cpp
  src/equipment.cpp
  src/food.cpp
  src/init.cpp
  src/item.cpp
  src/item_db.cpp
  src/itemgen.cpp
  src/lion.cpp
  src/lion.hpp
  src/magic.cpp
  src/map.cpp
  src/menu.cpp
  src/set_item_info.cpp
  src/shop.cpp
  src/talk_npc.cpp
  src/talk_unique.cpp
  src/testing.cpp
  src/tests/data/registry/chara_defaults/data/chara_defaults.hcl
  src/tests/data/registry/item/data.hcl
  src/tests/data/registry/item/data/item.hcl
  src/tests/lua_registry_character.cpp
  src/tests/lua_registry_item.cpp
  src/turn_sequence.cpp
  src/wish.cpp
Labels: customization, lua, refactoring

#745 Refactor set_item_info and item translations
  runtime/data/lua/enums.lua
  runtime/data/script/test_item_chip.lua
  runtime/mods/core/data/item.hcl
  runtime/mods/core/locale/en/item.hcl
  runtime/mods/core/locale/jp/item.hcl
  src/access_character_info.cpp
  src/access_item_db.cpp
  src/calc.cpp
  src/calc.hpp
  src/character.cpp
  src/character.hpp
  src/db_item.cpp
  src/db_item.hpp
  src/enums.hpp
  src/init.cpp
  src/init.hpp
  src/itemgen.cpp
  src/menu.cpp
  src/message.cpp
  src/set_item_info.cpp
  src/testing.cpp
  src/tests/data/registry/item/data/item.hcl
  src/tests/lua_registry_character.cpp
  src/tests/util.cpp
  src/thirdparty/microhil/hil.hpp
  src/variables.hpp
Labels: I18N, customization, refactoring

#747 Structure item description text
  runtime/mods/core/locale/en/item.hcl
  runtime/mods/core/locale/jp/item.hcl
  src/db_item.hpp
  src/elonacore.cpp
  src/menu.cpp
  src/menu.hpp
  src/set_item_info.cpp
  src/text.cpp
  src/variables.hpp
Labels: I18N, refactoring

#748 Implement item on use callback
  CMakeLists.txt
  doc/api/input.luadoc
  runtime/data/lua/handle.lua
  runtime/data/lua/private/scan_exports.lua
  runtime/data/script/test_on_use.lua
  runtime/mods/core/data/chara.hcl
  runtime/mods/kiroku/data.hcl
  runtime/mods/kiroku/data/item.hcl
  runtime/mods/kiroku/init.lua
  runtime/mods/kiroku/locale/en/item.hcl
  runtime/mods/kiroku/locale/jp/item.hcl
  src/access_character_info.cpp
  src/character.cpp
  src/character.hpp
  src/command.cpp
  src/ctrl_inventory.cpp
  src/db_item.cpp
  src/db_item.hpp
  src/elonacore.cpp
  src/item.cpp
  src/lua_env/api_manager.cpp
  src/lua_env/export_manager.hpp
  src/lua_env/exported_function.hpp
  src/lua_env/handle_manager.cpp
  src/lua_env/handle_manager.hpp
  src/std.cpp
  src/tests/data/registry/chara_invalid_callback/data/chara_invalid_callback.hcl
  src/tests/data/registry/item/data/item.hcl
  src/tests/lua_exports.cpp
  src/tests/lua_handles.cpp
  src/tests/lua_registry.cpp
Labels: customization, enhancement, lua

#751 Implement per-mod require and loaded chunk cache
  src/lua_env/loaded_chunk_cache.hpp
  src/lua_env/mod_manager.cpp
  src/lua_env/mod_manager.hpp
  src/tests/data/mods/test_require_chunks/data/script.lua
  src/tests/data/mods/test_require_chunks/init.lua
  src/tests/lua_mods.cpp
Labels: lua

#754 Port omake/oo translation
  runtime/data/talk.txt
  runtime/lang/en/buff.lua
  runtime/lang/en/ui.lua
  runtime/lang/jp/ui.lua
  runtime/locale/en/action.hcl
  runtime/locale/en/activity.hcl
  runtime/locale/en/blending.hcl
  runtime/locale/en/config.hcl
  runtime/locale/en/crafting.hcl
  runtime/locale/en/ctrl_inventory.hcl
  runtime/locale/en/damage.hcl
  runtime/locale/en/enchantment.hcl
  runtime/locale/en/event.hcl
  runtime/locale/en/god.hcl
  runtime/locale/en/map.hcl
  runtime/locale/en/talk_unique.hcl
  runtime/locale/en/talk_visitor.hcl
  runtime/locale/en/trait.hcl
  runtime/locale/en/ui.hcl
  runtime/locale/jp/action.hcl
  runtime/locale/jp/blending.hcl
  runtime/locale/jp/crafting.hcl
  runtime/mods/core/locale/en/item.hcl
  src/blending.cpp
  src/crafting.cpp
  src/elonacore.cpp
  src/main_menu.cpp
  src/menu.cpp
Labels: I18N, enhancement

#756 Fix keys not working after using house board
  src/input.cpp
Labels: bugfix

#755 Refactor animation parameter/Add Animation API
  .luacheckrc
  doc/api/animation.luadoc
  doc/api/classes/LuaPosition.luadoc
  runtime/data/script/test_animation.lua
  src/activity.cpp
  src/animation.cpp
  src/animation.hpp
  src/command.cpp
  src/elonacore.cpp
  src/lua_env/api_manager.cpp
  src/lua_env/api_manager.hpp
  src/magic.cpp
  src/proc_event.cpp
  src/talk.cpp
  src/tests/lua/chara.lua
  src/variables.hpp
Labels: lua, refactoring

#758 Split api_manager into Lua API/classes
  CMakeLists.txt
  src/command.cpp
  src/lua_env/api_manager.cpp
  src/lua_env/api_manager.hpp
  src/lua_env/lua_api/lua_api.cpp
  src/lua_env/lua_api/lua_api.hpp
  src/lua_env/lua_api/lua_api_animation.cpp
  src/lua_env/lua_api/lua_api_animation.hpp
  src/lua_env/lua_api/lua_api_chara.cpp
  src/lua_env/lua_api/lua_api_chara.hpp
  src/lua_env/lua_api/lua_api_common.hpp
  src/lua_env/lua_api/lua_api_debug.cpp
  src/lua_env/lua_api/lua_api_debug.hpp
  src/lua_env/lua_api/lua_api_fov.cpp
  src/lua_env/lua_api/lua_api_fov.hpp
  src/lua_env/lua_api/lua_api_gui.cpp
  src/lua_env/lua_api/lua_api_gui.hpp
  src/lua_env/lua_api/lua_api_i18n.cpp
  src/lua_env/lua_api/lua_api_i18n.hpp
  src/lua_env/lua_api/lua_api_input.cpp
  src/lua_env/lua_api/lua_api_input.hpp
  src/lua_env/lua_api/lua_api_item.cpp
  src/lua_env/lua_api/lua_api_item.hpp
  src/lua_env/lua_api/lua_api_magic.cpp
  src/lua_env/lua_api/lua_api_magic.hpp
  src/lua_env/lua_api/lua_api_map.cpp
  src/lua_env/lua_api/lua_api_map.hpp
  src/lua_env/lua_api/lua_api_math.cpp
  src/lua_env/lua_api/lua_api_math.hpp
  src/lua_env/lua_api/lua_api_pos.cpp
  src/lua_env/lua_api/lua_api_pos.hpp
  src/lua_env/lua_api/lua_api_rand.cpp
  src/lua_env/lua_api/lua_api_rand.hpp
  src/lua_env/lua_api/lua_api_skill.cpp
  src/lua_env/lua_api/lua_api_skill.hpp
  src/lua_env/lua_api/lua_api_trait.cpp
  src/lua_env/lua_api/lua_api_trait.hpp
  src/lua_env/lua_api/lua_api_world.cpp
  src/lua_env/lua_api/lua_api_world.hpp
  src/lua_env/lua_class/lua_class.cpp
  src/lua_env/lua_class/lua_class.hpp
  src/lua_env/lua_class/lua_class_character.cpp
  src/lua_env/lua_class/lua_class_character.hpp
  src/lua_env/lua_class/lua_class_item.cpp
  src/lua_env/lua_class/lua_class_item.hpp
  src/lua_env/lua_class/lua_class_position.cpp
  src/lua_env/lua_class/lua_class_position.hpp
  src/variables.hpp
Labels: lua, refactoring

#763 Add Lua object reference changes from serialization change
  CMakeLists.txt
  runtime/data/lua/handle.lua
  src/building.cpp
  src/character.cpp
  src/character.hpp
  src/character_making.cpp
  src/dmgheal.cpp
  src/elonacore.cpp
  src/initialize_map.cpp
  src/item.cpp
  src/lua_env/handle_manager.cpp
  src/lua_env/handle_manager.hpp
  src/lua_env/lua_api/lua_api_chara.cpp
  src/tests/item.cpp
  src/tests/lua_handles.cpp
Labels: lua, refactoring

#769 Add start_in_debug_map to certain tests that need it
  src/tests/lua_handles.cpp
Labels: bugfix

#764 Fix crash when you drop item
  src/elonacore.cpp
Labels: bugfix

#765 Fix random item color like potions
  src/calc.cpp
Labels: bugfix

#772 Fix default item color
  runtime/mods/core/data/item.hcl
  src/db_item.cpp
Labels: bugfix

#768 Rename all remaining label_xyz functions
  src/activity.cpp
  src/adventurer.cpp
  src/adventurer.hpp
  src/ai.cpp
  src/blending.cpp
  src/building.cpp
  src/casino.cpp
  src/casino.hpp
  src/command.cpp
  src/elonacore.cpp
  src/god.cpp
  src/god.hpp
  src/initialize_map.cpp
  src/lua_env/lua_api/lua_api_fov.cpp
  src/magic.cpp
  src/mapgen.cpp
  src/menu.cpp
  src/menu.hpp
  src/proc_event.cpp
  src/quest.cpp
  src/talk.cpp
  src/tcg.cpp
  src/turn_sequence.cpp
  src/ui.cpp
  src/ui.hpp
  src/variables.hpp
Labels: refactoring

#762 Refactor names of ctrl_file operations
  src/building.cpp
  src/command.cpp
  src/ctrl_file.cpp
  src/ctrl_file.hpp
  src/elonacore.cpp
  src/init.cpp
  src/initialize_map.cpp
  src/magic.cpp
  src/main_menu.cpp
  src/map.cpp
  src/mapgen.cpp
  src/shop.cpp
  src/tcg.cpp
  src/turn_sequence.cpp
Labels: refactoring

#771 Begin refactoring menus using class
  CMakeLists.txt
  src/elonacore.cpp
  src/enchantment.cpp
  src/item.cpp
  src/item.hpp
  src/item_load_desc.cpp
  src/menu.cpp
  src/ui/ui_menu.hpp
  src/ui/ui_menu_book.cpp
  src/ui/ui_menu_book.hpp
  src/ui/ui_menu_item_desc.cpp
  src/ui/ui_menu_item_desc.hpp
Labels: refactoring

#774 Fix case of Lua reference relocation during "change" mode
  runtime/data/lua/handle.lua
  src/character.cpp
  src/tests/lua_handles.cpp
Labels: bugfix, lua

#770 Organize functions in variables.hpp and remove duplicate declarations
  src/access_item_db.cpp
  src/animation.cpp
  src/building.cpp
  src/character_status.cpp
  src/command.cpp
  src/dmgheal.cpp
  src/enchantment.cpp
  src/init.cpp
  src/initialize_map.cpp
  src/lua_env/lua_class/lua_class_character.cpp
  src/magic.cpp
  src/mapgen.hpp
  src/menu.cpp
  src/menu.hpp
  src/status_ailment.hpp
  src/variables.hpp
  src/wish.cpp
Labels: refactoring

#776 Add missing functions needed by exports/eating_effect.lua
  doc/api/classes/LuaCharacter.luadoc
  doc/api/math.luadoc
  runtime/data/lua/init.lua
  runtime/data/lua/math_ext.lua
  runtime/mods/core/exports/eating_effect.lua
  src/lua_env/lua_class/lua_class_character.cpp
  src/lua_env/lua_class/lua_class_character.hpp
  src/tests/lua/exports/eating_effect.lua
  src/tests/lua_api.cpp
Labels: bugfix, lua

#777 Refactor NPC tone/ctrl_ally windows
  CMakeLists.txt
  runtime/data/script/test_menus.lua
  src/building.cpp
  src/command.cpp
  src/menu.cpp
  src/menu.hpp
  src/talk_npc.cpp
  src/talk_unique.cpp
  src/ui/ui_menu.hpp
  src/ui/ui_menu_ctrl_ally.cpp
  src/ui/ui_menu_ctrl_ally.hpp
  src/ui/ui_menu_npc_tone.cpp
  src/ui/ui_menu_npc_tone.hpp
Labels: refactoring

#760 Refactor Enums API into string maps
  CMakeLists.txt
  doc/README.md
  doc/api/enums.luadoc
  doc/api/skill.luadoc
  runtime/data/lua/enums.lua
  runtime/data/lua/init.lua
  src/character.cpp
  src/db_item.cpp
  src/element.hpp
  src/enums.hpp
  src/lion.hpp
  src/lua_env/api_manager.cpp
  src/lua_env/api_manager.hpp
  src/lua_env/lua_api/lua_api_animation.cpp
  src/lua_env/lua_api/lua_api_animation.hpp
  src/lua_env/lua_api/lua_api_chara.cpp
  src/lua_env/lua_api/lua_api_chara.hpp
  src/lua_env/lua_api/lua_api_common.hpp
  src/lua_env/lua_api/lua_api_gui.cpp
  src/lua_env/lua_api/lua_api_gui.hpp
  src/lua_env/lua_api/lua_api_map.cpp
  src/lua_env/lua_api/lua_api_map.hpp
  src/lua_env/lua_api/lua_api_skill.cpp
  src/lua_env/lua_api/lua_api_skill.hpp
  src/lua_env/lua_class/lua_class_character.cpp
  src/lua_env/lua_class/lua_class_character.hpp
  src/lua_env/lua_class/lua_class_item.cpp
  src/lua_env/lua_enums.cpp
  src/lua_env/lua_enums.hpp
  src/tests/lua/classes/LuaCharacter.lua
Labels: lua, refactoring

#786 Fix incorrect character colors
  runtime/mods/core/data/chara.hcl
Labels: bugfix

#787 Fix overlap of generated card image
  src/draw.cpp
Labels: bugfix

#791 Prevent aliasing of "chatval" global by argument "int chatval"
  src/talk_npc.cpp
Labels: bugfix

#796 Fix incorrect forward declaration in ui/ (again)
  src/ui/ui_menu_ctrl_ally.hpp
Labels: bugfix

#780 Fix I18N errors in JP (3)
  runtime/mods/core/locale/en/item.hcl
  runtime/mods/core/locale/jp/item.hcl
  src/character.cpp
  src/talk_npc.cpp
Labels: I18N, bugfix

#793 Remove global "chatval"
  src/init.cpp
  src/talk.cpp
  src/talk.hpp
  src/talk_npc.cpp
  src/talk_unique.cpp
  src/variables.hpp
Labels: refactoring

#798 Refactor scene and crafting menus
  CMakeLists.txt
  src/ability.cpp
  src/ability.hpp
  src/crafting.cpp
  src/crafting.hpp
  src/init.cpp
  src/menu.cpp
  src/ui/ui_menu_crafting.cpp
  src/ui/ui_menu_crafting.hpp
  src/ui/ui_menu_scene.cpp
  src/ui/ui_menu_scene.hpp
  src/variables.hpp
Labels: refactoring

#799 Extract talk_house_visitor() from talk.cpp and refactor
  CMakeLists.txt
  runtime/locale/jp/talk_visitor.hcl
  src/talk.cpp
  src/talk_house_visitor.cpp
Labels: refactoring

#801 Refactor journal updated message into function
  src/dmgheal.cpp
  src/elonacore.cpp
  src/proc_event.cpp
  src/quest.cpp
  src/quest.hpp
  src/talk.cpp
  src/talk_unique.cpp
Labels: refactoring

#802 Refactor out most inline functions in talk_unique.cpp
  src/talk_unique.cpp
Labels: refactoring

#782 Refactor character chip/item chip to use lion db
  CMakeLists.txt
  runtime/mods/core/data.hcl
  runtime/mods/core/data/chara_chip.hcl
  runtime/mods/core/data/item_chip.hcl
  runtime/mods/kiroku/data.hcl
  runtime/mods/kiroku/data/item.hcl
  runtime/mods/kiroku/data/item_chip.hcl
  runtime/mods/kiroku/graphic/item_counter.png
  src/character.cpp
  src/character.hpp
  src/db_chara_chip.cpp
  src/db_chara_chip.hpp
  src/db_character.cpp
  src/db_character.hpp
  src/db_item.cpp
  src/db_item.hpp
  src/db_item_chip.cpp
  src/db_item_chip.hpp
  src/db_music.hpp
  src/db_sound.hpp
  src/draw.cpp
  src/draw.hpp
  src/i18n.hpp
  src/init.cpp
  src/lion.hpp
  src/lua_env/handle_manager.hpp
  src/testing.cpp
Labels: customization, refactoring

#807 Fix out of range access
  src/pic_loader/extent.hpp
  src/pic_loader/pic_loader.cpp
  src/pic_loader/pic_loader.hpp
Labels: bugfix

#809 Fix cursed food not being removed
  src/activity.cpp
Labels: bugfix

#810 Delete debug code(random event)
  src/random_event.cpp
Labels: bugfix

#805 Add 'make format' command for Windows
  .github/CODE_STYLE.md
  .github/CONTRIBUTING.md
  Makefile.win
Labels: build

#808 Fix JP damage text
  runtime/locale/en/damage.hcl
  runtime/locale/jp/damage.hcl
  src/elonacore.cpp
Labels: I18N, bugfix

#803 Refactor spell and skill menus
  CMakeLists.txt
  runtime/data/lua/init.lua
  runtime/data/lua/table_ext.lua
  runtime/data/script/all_magic.lua
  src/menu.cpp
  src/menu.hpp
  src/turn_sequence.cpp
  src/ui/ui_menu.hpp
  src/ui/ui_menu_composite.hpp
  src/ui/ui_menu_composite_skills.cpp
  src/ui/ui_menu_composite_skills.hpp
  src/ui/ui_menu_skills.cpp
  src/ui/ui_menu_skills.hpp
  src/ui/ui_menu_spells.cpp
  src/ui/ui_menu_spells.hpp
Labels: refactoring

#816 Fix not being able to pickpocket
  src/menu.cpp
Labels: bugfix

#814 Refactor history, journal and message log menus
  CMakeLists.txt
  src/elonacore.cpp
  src/enums.hpp
  src/menu.cpp
  src/menu.hpp
  src/turn_sequence.cpp
  src/ui/ui_menu_chat_history.cpp
  src/ui/ui_menu_chat_history.hpp
  src/ui/ui_menu_composite.hpp
  src/ui/ui_menu_composite_message.cpp
  src/ui/ui_menu_composite_message.hpp
  src/ui/ui_menu_journal.cpp
  src/ui/ui_menu_journal.hpp
  src/ui/ui_menu_message_log.cpp
  src/ui/ui_menu_message_log.hpp
  src/ui/ui_menu_skills.cpp
Labels: refactoring

#811 Add 7 more tracked skills and potential tinted according to value.
  runtime/locale/en/config.hcl
  runtime/locale/jp/config.hcl
  runtime/mods/core/config/config_def.hcl
  src/config.cpp
  src/config.hpp
  src/menu.cpp
  src/ui.cpp
Labels: enhancement

#819 Fix corner case of parsing single '$' in HIL
  runtime/locale/en/ui.hcl
  runtime/locale/jp/ui.hcl
  src/hcl.hpp
  src/i18n.cpp
  src/thirdparty/microhcl/hcl.hpp
  src/thirdparty/microhil/hil.hpp
  src/ui/ui_menu_quest_board.cpp
Labels: bugfix

#813 Refactor character sheet, equipment, feat and material menus
  CMakeLists.txt
  src/character_making.cpp
  src/command.cpp
  src/elonacore.cpp
  src/menu.cpp
  src/menu.hpp
  src/talk_house_visitor.cpp
  src/talk_npc.cpp
  src/trait.cpp
  src/trait.hpp
  src/turn_sequence.cpp
  src/ui.cpp
  src/ui/ui_menu.hpp
  src/ui/ui_menu_character_sheet.cpp
  src/ui/ui_menu_character_sheet.hpp
  src/ui/ui_menu_chat_history.cpp
  src/ui/ui_menu_composite.hpp
  src/ui/ui_menu_composite_character.cpp
  src/ui/ui_menu_composite_character.hpp
  src/ui/ui_menu_equipment.cpp
  src/ui/ui_menu_equipment.hpp
  src/ui/ui_menu_feats.cpp
  src/ui/ui_menu_feats.hpp
  src/ui/ui_menu_journal.cpp
  src/ui/ui_menu_materials.cpp
  src/ui/ui_menu_materials.hpp
  src/ui/ui_menu_message_log.cpp
  src/variables.hpp
Labels: refactoring

#822 Add option to run script over existing save data
  runtime/config.hcl
  runtime/mods/core/config/config_def.hcl
  src/init.cpp
Labels: lua

#818 Modify build system to always overwrite all files except config
  CMakeLists.txt
Labels: build

#820 Implement config item description for English
  runtime/locale/en/config.hcl
  runtime/locale/en/ui.hcl
  runtime/locale/jp/config.hcl
  runtime/locale/jp/ui.hcl
  src/set_option.cpp
Labels: enhancement

#826 Refactor character making menus
  CMakeLists.txt
  src/character_making.cpp
  src/character_making.hpp
  src/ui/ui_menu_charamake_alias.cpp
  src/ui/ui_menu_charamake_alias.hpp
  src/ui/ui_menu_charamake_attributes.cpp
  src/ui/ui_menu_charamake_attributes.hpp
  src/ui/ui_menu_charamake_class.cpp
  src/ui/ui_menu_charamake_class.hpp
  src/ui/ui_menu_charamake_gender.cpp
  src/ui/ui_menu_charamake_gender.hpp
  src/ui/ui_menu_charamake_race.cpp
  src/ui/ui_menu_charamake_race.hpp
Labels: refactoring

#827 Refactor town board menus
  CMakeLists.txt
  runtime/locale/en/ui.hcl
  runtime/locale/jp/ui.hcl
  src/menu.cpp
  src/menu.hpp
  src/ui.cpp
  src/ui.hpp
  src/ui/ui_menu_composite_town.cpp
  src/ui/ui_menu_composite_town.hpp
  src/ui/ui_menu_town_chart.cpp
  src/ui/ui_menu_town_chart.hpp
  src/ui/ui_menu_town_economy.cpp
  src/ui/ui_menu_town_economy.hpp
  src/ui/ui_menu_town_politics.cpp
  src/ui/ui_menu_town_politics.hpp
  src/variables.hpp
Labels: refactoring

#821 Add list syntax to translation files
  runtime/locale/en/action.hcl
  runtime/locale/en/activity.hcl
  runtime/locale/en/ai.hcl
  runtime/locale/en/blending.hcl
  runtime/locale/en/chara.hcl
  runtime/locale/en/ctrl_inventory.hcl
  runtime/locale/en/event.hcl
  runtime/locale/en/food.hcl
  runtime/locale/en/magic.hcl
  runtime/locale/en/talk_npc.hcl
  runtime/locale/jp/action.hcl
  runtime/locale/jp/activity.hcl
  runtime/locale/jp/ai.hcl
  runtime/locale/jp/blending.hcl
  runtime/locale/jp/chara.hcl
  runtime/locale/jp/ctrl_inventory.hcl
  runtime/locale/jp/event.hcl
  runtime/locale/jp/food.hcl
  runtime/locale/jp/magic.hcl
  runtime/locale/jp/talk_npc.hcl
  src/activity.cpp
  src/ai.cpp
  src/blending.cpp
  src/command.cpp
  src/ctrl_inventory.cpp
  src/elonacore.cpp
  src/food.cpp
  src/i18n.cpp
  src/i18n.hpp
  src/magic.cpp
  src/proc_event.cpp
  src/random_event.cpp
  src/talk_house_visitor.cpp
  src/talk_npc.cpp
  src/tests/i18n.cpp
  src/thirdparty/microhil/hil.hpp
  src/turn_sequence.cpp
Labels: I18N, enhancement, refactoring

#825 Add a option to toggle PCC graphic scale(shrinked/full-scale)
  runtime/locale/en/config.hcl
  runtime/locale/jp/config.hcl
  runtime/mods/core/config/config_def.hcl
  src/cell_draw.cpp
  src/config.cpp
  src/config.hpp
Labels: enhancement

#831 Fix some wishing
  src/wish.cpp
Labels: bugfix

#832 Fix the current map name being displayed as the left map name
  src/elonacore.cpp
Labels: bugfix

#834 Fix overlap between hp bar and skill tracker
  src/draw.cpp
  src/ui.cpp
Labels: bugfix

#836 Fix overflow of harvest quest's reward
  src/quest.cpp
Labels: bugfix
