Repository elonafoobar/elonafoobar, pull requests merged in 2018-02, with the labels that each got.

#3 Add information to contribute
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
  README.md
Labels: enhancement

#5 Add How To Build and How To Play
  README.md
Labels: enhancement

#1 Refactor/some functions
  access_character_info.cpp
  calc.cpp
  calc.hpp
  ctrl_file.cpp
  ctrl_inventory.cpp
  elonacore.cpp
  god.cpp
  initialize_map.cpp
  item.cpp
  item.hpp
  lang/en/ui.lua
  lang/jp/ui.lua
  magic.cpp
  message.cpp
  proc_event.cpp
  random.hpp
  range.hpp
  snail/detail/sdl.cpp
  talk_npc.cpp
  talk_unique.cpp
  text.cpp
  variables.hpp
Labels: refactoring

#8 Feature/minimum attribute roll
  CHANGELOG.md
  init.cpp
Labels: enhancement

#11 Fix invalid signature
  message.cpp
Labels: bug

#14 Use font1 and font2 in config.json instead of hard-coded filename
  snail/font.hpp
  std.cpp
Labels: bug

#16 Feature/externalize buff text
  buff.cpp
  buff.hpp
  calc.cpp
  cat.hpp
  data/buff.lua
  i18n.cpp
  i18n.hpp
  init.cpp
  lang/en/buff.lua
  lang/jp/buff.lua
Labels: enhancement

#18 Feature/unify api of lua
  ability.cpp
  buff.cpp
  character.cpp
  class.cpp
  data/ability.lua
  data/buff.lua
  data/character.lua
  data/class.lua
  data/item.lua
  data/race.lua
  data/trait.lua
  i18n.cpp
  i18n.hpp
  item_db.cpp
  race.cpp
  trait.cpp
Labels: enhancement
