Repository elonafoobar/elonafoobar, pull requests merged in 2019-03, with the labels that each got.

#1203 Add JSON serialization/deserialization
  README-jp.md
  README.md
  src/elona/_putit/ability.cpp
  src/elona/_putit/buff.cpp
  src/elona/_putit/character.cpp
  src/elona/_putit/continuous_action.cpp
  src/elona/_putit/enchantment.cpp
  src/elona/_putit/foobar_data.cpp
  src/elona/_putit/item.cpp
  src/elona/_putit/position.cpp
  src/elona/lua_env/lua_console.cpp
  src/putit/archive/archive.hpp
  src/putit/archive/archive_base.hpp
  src/putit/archive/binary_archive.hpp
  src/putit/archive/detail/byte_swap.hpp
  src/putit/archive/json_archive.hpp
  src/putit/bin/putit.py
  src/putit/putit.hpp
  src/thirdparty/nlohmannjson/LICENSE.MIT
  src/thirdparty/nlohmannjson/json.hpp
Labels: enhancement

#1211 fix License & Credit texts extending outside
  src/elona/main_menu.cpp
Labels: bugfix

#1212 Autogenerate Android.mk from CMakeLists.txt
  .gitignore
  CMakeLists.txt
  Makefile
  src/elona/Android.mk
  src/elona/Android.mk.in
  src/elona/CMakeLists.txt
  src/snail/Android.mk.in
  src/snail/CMakeLists.txt
  src/util/Android.mk.in
  src/util/CMakeLists.txt
Labels: android, build

#1207 Add backtrace output on Linux
  CMakeLists.txt
  src/elona/filesystem.cpp
  src/main.cpp
  src/util/CMakeLists.txt
  src/util/backtrace.cpp
  src/util/backtrace.hpp
  src/util/filepathutil.cpp
  src/util/filepathutil.hpp
Labels: enhancement

#1215 Add mod dialog system
  CMakeLists.txt
  doc/api/chara.luadoc
  doc/api/classes/LuaCharacter.luadoc
  doc/api/enums.luadoc
  doc/api/gui.luadoc
  doc/api/input.luadoc
  runtime/profile/_/mod/core/data/chara.lua
  runtime/profile/_/mod/core/data/dialog.lua
  runtime/profile/_/mod/core/data/dialog/unique.lua
  runtime/profile/_/mod/core/exports/impl.lua
  runtime/profile/_/mod/core/exports/impl/shop_inventory.lua
  runtime/profile/_/mod/core/exports/impl/show_dialog.lua
  src/elona/CMakeLists.txt
  src/elona/character.hpp
  src/elona/dialog.cpp
  src/elona/dialog.hpp
  src/elona/dialog/dialog.cpp
  src/elona/dialog/dialog.hpp
  src/elona/dialog/dialog_data.cpp
  src/elona/dialog/dialog_data.hpp
  src/elona/dialog/dialog_decoder.cpp
  src/elona/dialog/dialog_decoder.hpp
  src/elona/lua_env/enums/enums.cpp
  src/elona/lua_env/lua_api/lua_api.cpp
  src/elona/lua_env/lua_api/lua_api.hpp
  src/elona/lua_env/lua_api/lua_api_chara.cpp
  src/elona/lua_env/lua_api/lua_api_chara.hpp
  src/elona/lua_env/lua_api/lua_api_common.hpp
  src/elona/lua_env/lua_api/lua_api_gui.cpp
  src/elona/lua_env/lua_api/lua_api_gui.hpp
  src/elona/lua_env/lua_api/lua_api_input.cpp
  src/elona/lua_env/lua_api/lua_api_input.hpp
  src/elona/lua_env/lua_api/lua_api_internal.cpp
  src/elona/lua_env/lua_api/lua_api_internal.hpp
  src/elona/lua_env/lua_class/lua_class_ability.cpp
  src/elona/lua_env/lua_class/lua_class_character.cpp
  src/elona/lua_env/lua_class/lua_class_character.hpp
  src/elona/lua_env/lua_class/lua_class_item.cpp
  src/elona/lua_env/lua_class/lua_class_position.cpp
  src/elona/lua_env/mod_manager.hpp
  src/elona/talk.cpp
  src/elona/talk.hpp
  src/elona/talk_unique.cpp
  src/elona/ui/ui_menu_dialog.cpp
  src/elona/ui/ui_menu_dialog.hpp
  src/elona/ui_menus.cpp
  src/tests/dialog.cpp
Labels: lua

#1216 Remove unused file, src/elona/spec_load.cpp
  src/elona/spec_load.cpp
Labels: refactoring

#1217 Remove profile/testing and profile/default before testing
  CMakeLists.txt
Labels: bugfix

#1218 Fix mojibake in error message if filepath contains multibyte characters
  src/elona/config/config.cpp
  src/elona/lua_env/mod_manifest.cpp
Labels: bugfix

#1230 Fix segmentation fault on launching
  runtime/profile/_/mod/core/data/asset.lua
  src/elona/config/config.cpp
Labels: bugfix

#1229 Fix being unable to run in a certain configuration
  src/elona/keybind/input_context.cpp
Labels: bugfix

#1233 Fix mojibake in error message if filepath contains multibyte characters
  src/elona/audio.cpp
  src/elona/ctrl_file.cpp
  src/elona/data/types/type_music.cpp
  src/elona/data/types/type_sound.cpp
  src/elona/i18n.cpp
  src/elona/lua_env/mod_manager.cpp
  src/elona/lua_env/mod_manifest.cpp
  src/elona/spec.cpp
Labels: bugfix

#1236 Fix .ldoc files not having a line break at the end of file
  Makefile
  tools/docgen/src/main.rs
Labels: bugfix

#1237 Load character.bmp in order to load growth buff icons
  doc/api/classes/LuaCharacter.luadoc
  runtime/profile/_/mod/core/data/asset.lua
  src/elona/lua_env/lua_class/lua_class_character.cpp
Labels: bugfix

#1240 Fix choices in talk with Erystia
  runtime/profile/_/mod/core/data/dialog/unique/erystia.lua
Labels: bugfix

#1238 Decreate resource usage of help screen
  src/elona/ui/ui_menu_game_help.cpp
  src/elona/ui/ui_menu_game_help.hpp
Labels: bugfix

#1234 Move tile data to Lua
  runtime/profile/_/mod/core/data.lua
  runtime/profile/_/mod/core/data/asset.lua
  runtime/profile/_/mod/core/data/map_chip.lua
  src/elona/CMakeLists.txt
  src/elona/activity.cpp
  src/elona/ai.cpp
  src/elona/building.cpp
  src/elona/casino.cpp
  src/elona/cell_draw.cpp
  src/elona/character.cpp
  src/elona/command.cpp
  src/elona/ctrl_inventory.cpp
  src/elona/data/init.cpp
  src/elona/data/types.cpp
  src/elona/data/types.hpp
  src/elona/data/types/type_asset.cpp
  src/elona/data/types/type_map_chip.cpp
  src/elona/data/types/type_map_chip.hpp
  src/elona/draw.cpp
  src/elona/draw.hpp
  src/elona/elona.hpp
  src/elona/elonacore.cpp
  src/elona/food.cpp
  src/elona/fov.cpp
  src/elona/initialize_map.cpp
  src/elona/initialize_map_types.cpp
  src/elona/itemgen.cpp
  src/elona/lua_env/lua_api/lua_api_map.cpp
  src/elona/magic.cpp
  src/elona/map.cpp
  src/elona/map.hpp
  src/elona/map_cell.cpp
  src/elona/mapgen.cpp
  src/elona/mef.cpp
  src/elona/menu.cpp
  src/elona/pic_loader/pic_loader.cpp
  src/elona/pic_loader/pic_loader.hpp
  src/elona/pic_loader/tinted_buffers.cpp
  src/elona/pic_loader/tinted_buffers.hpp
  src/elona/proc_event.cpp
  src/elona/turn_sequence_pc_actions.cpp
  src/elona/ui.cpp
  src/elona/ui/ui_menu_character_sheet.cpp
  src/elona/variables.hpp
Labels: lua, refactoring

#1232 Implement version-based mod dependencies
  CMakeLists.txt
  runtime/profile/_/mod/kiroku/mod.hcl
  src/elona/lua_env/mod_manager.cpp
  src/elona/lua_env/mod_manifest.cpp
  src/elona/lua_env/mod_manifest.hpp
  src/elona/semver.hpp
  src/tests/data/registry/chara/mod.hcl
  src/tests/data/registry/chara_defaults/mod.hcl
  src/tests/data/registry/chara_duplicate_key/mod.hcl
  src/tests/data/registry/chara_invalid_enum/mod.hcl
  src/tests/data/registry/chara_portrait/mod.hcl
  src/tests/data/registry/item/mod.hcl
  src/tests/lua_mods.cpp
  src/tests/semver.cpp
  src/util/either.hpp
  src/util/range.hpp
Labels: enhancement

#1243 Refactor event callbacks to take a table instead of varargs
  doc/api/classes/LuaCharacter.luadoc
  doc/api/core_event.luadoc
  doc/api/event.luadoc
  doc/api/event_eventkind.luadoc
  doc/examples/life.lua
  doc/topics/README.md
  runtime/data/script/kernel/event.lua
  runtime/data/script/kernel/event_tree.lua
  runtime/data/script/kernel/handle.lua
  runtime/data/script/kernel/init.lua
  runtime/profile/_/mod/core/data.lua
  runtime/profile/_/mod/core/data/event.lua
  runtime/profile/_/mod/kiroku/data.lua
  runtime/profile/_/mod/kiroku/data/item.lua
  runtime/profile/_/mod/kiroku/data/item_chip.lua
  runtime/profile/_/mod/kiroku/data/test.lua
  runtime/profile/_/mod/kiroku/graphic/item_counter.png
  runtime/profile/_/mod/kiroku/init.lua
  runtime/profile/_/mod/kiroku/locale/en/item.hcl
  runtime/profile/_/mod/kiroku/locale/en/kiroku.hcl
  runtime/profile/_/mod/kiroku/locale/jp/item.hcl
  runtime/profile/_/mod/kiroku/locale/jp/kiroku.hcl
  runtime/profile/_/mod/kiroku/mod.hcl
  src/elona/character.cpp
  src/elona/data/lua_lazy_cache.hpp
  src/elona/dmgheal.cpp
  src/elona/element.hpp
  src/elona/elonacore.cpp
  src/elona/init.cpp
  src/elona/initialize_map.cpp
  src/elona/item.hpp
  src/elona/lua_env/enums/enums.cpp
  src/elona/lua_env/event_manager.cpp
  src/elona/lua_env/event_manager.hpp
  src/elona/lua_env/handle_manager.cpp
  src/elona/lua_env/interface.hpp
  src/elona/lua_env/lua_class/lua_class_character.cpp
  src/elona/lua_env/lua_enums.hpp
  src/elona/lua_env/lua_event/base_event.hpp
  src/elona/lua_env/lua_event/character_instance_event.hpp
  src/elona/lua_env/lua_event/item_instance_event.hpp
  src/elona/lua_env/lua_event/lua_event.hpp
  src/elona/lua_env/lua_event/lua_event_calc_character_damage.hpp
  src/elona/lua_env/lua_event/lua_event_character_created.hpp
  src/elona/lua_env/lua_event/lua_event_character_damaged.hpp
  src/elona/lua_env/lua_event/lua_event_character_killed.hpp
  src/elona/lua_env/lua_event/lua_event_map_initialized.hpp
  src/elona/lua_env/mod_manager.cpp
  src/elona/magic.cpp
  src/elona/main.cpp
  src/elona/testing.cpp
  src/elona/turn_sequence.cpp
  src/elona/variables.hpp
  src/tests/lua_callbacks.cpp
  src/tests/lua_events.cpp
  src/tests/lua_mods.cpp
  src/tests/lua_serialization.cpp
Labels: lua, refactoring

#1247 Add Lua coroutine library
  runtime/data/script/kernel/init.lua
  src/elona/lua_env/lua_env.cpp
Labels: lua

#1220 Add macro API and related input/map APIs for pathfinding
  doc/examples/life.lua
  doc/topics/README.md
  src/elona/CMakeLists.txt
  src/elona/elonacore.cpp
  src/elona/keybind/input_context.cpp
  src/elona/keybind/input_context.hpp
  src/elona/keybind/macro_action_queue.cpp
  src/elona/keybind/macro_action_queue.hpp
  src/elona/lua_env/lua_api/lua_api_input.cpp
  src/elona/lua_env/lua_api/lua_api_input.hpp
  src/elona/lua_env/lua_api/lua_api_map.cpp
  src/elona/lua_env/lua_api/lua_api_map.hpp
  src/elona/lua_env/lua_class/lua_class_character.cpp
  src/elona/lua_env/lua_class/lua_class_character.hpp
  src/elona/mapgen.cpp
  src/elona/variables.hpp
  src/tests/lua/map.lua
Labels: lua

#1255 Fix flickering on house designing
  src/elona/elonacore.cpp
Labels: bugfix

#1241 Implement vanilla-like console
  doc/api/animation.luadoc
  doc/api/chara.luadoc
  doc/api/classes/LuaArea.luadoc
  doc/api/classes/LuaCharacter.luadoc
  doc/api/classes/LuaDateTime.luadoc
  doc/api/classes/LuaGameData.luadoc
  doc/api/classes/LuaItem.luadoc
  doc/api/classes/LuaMapData.luadoc
  doc/api/classes/LuaPosition.luadoc
  doc/api/config.luadoc
  doc/api/console.luadoc
  doc/api/data.luadoc
  doc/api/debug.luadoc
  doc/api/enums.luadoc
  doc/api/env.luadoc
  doc/api/fov.luadoc
  doc/api/gui.luadoc
  doc/api/i18n.luadoc
  doc/api/input.luadoc
  doc/api/item.luadoc
  doc/api/magic.luadoc
  doc/api/map.luadoc
  doc/api/math.luadoc
  doc/api/pos.luadoc
  doc/api/rand.luadoc
  doc/api/skill.luadoc
  doc/api/trait.luadoc
  doc/api/world.luadoc
  doc/config.ld
  doc/topics/console.md
  runtime/data/script/kernel/ush.lua
  runtime/data/script/kernel/ush/ast.lua
  runtime/data/script/kernel/ush/execute.lua
  runtime/data/script/kernel/ush/jarowinkler.lua
  runtime/data/script/kernel/ush/lex.lua
  runtime/data/script/kernel/ush/parse.lua
  src/elona/CMakeLists.txt
  src/elona/audio.cpp
  src/elona/casino_card.cpp
  src/elona/cell_draw.cpp
  src/elona/data/lua_lazy_cache.hpp
  src/elona/draw.cpp
  src/elona/draw.hpp
  src/elona/draw_asset.cpp
  src/elona/init.cpp
  src/elona/lua_env/console.cpp
  src/elona/lua_env/console.hpp
  src/elona/lua_env/lua_api/lua_api.cpp
  src/elona/lua_env/lua_api/lua_api.hpp
  src/elona/lua_env/lua_api/lua_api_common.hpp
  src/elona/lua_env/lua_api/lua_api_console.cpp
  src/elona/lua_env/lua_api/lua_api_console.hpp
  src/elona/lua_env/lua_env.cpp
  src/elona/lua_env/lua_env.hpp
  src/elona/optional.hpp
  src/elona/pic_loader/pic_loader.cpp
  src/elona/pic_loader/pic_loader.hpp
  src/elona/turn_sequence_pc_actions.cpp
  src/elona/ui.cpp
Labels: enhancement

#1239 Add map generation system in Lua
  doc/api/chara.luadoc
  doc/api/classes/LuaArea.luadoc
  doc/api/classes/LuaCharacter.luadoc
  doc/api/classes/LuaGameData.luadoc
  doc/api/classes/LuaItem.luadoc
  doc/api/classes/LuaMapData.luadoc
  doc/api/classes/LuaMapGenerator.luadoc
  doc/api/core_event.luadoc
  doc/api/item.luadoc
  doc/api/map.luadoc
  doc/api/world.luadoc
  runtime/profile/_/mod/core/data/event.lua
  runtime/profile/_/mod/core/data/map.lua
  runtime/profile/_/mod/core/data/map/static.lua
  src/elona/CMakeLists.txt
  src/elona/activity.cpp
  src/elona/area.cpp
  src/elona/area.hpp
  src/elona/building.cpp
  src/elona/data/lua_lazy_cache.hpp
  src/elona/data/types/type_map.cpp
  src/elona/data/types/type_map.hpp
  src/elona/elonacore.cpp
  src/elona/init.cpp
  src/elona/initialize_map.cpp
  src/elona/initialize_map_types.cpp
  src/elona/lua_env/lua_api/lua_api.cpp
  src/elona/lua_env/lua_api/lua_api.hpp
  src/elona/lua_env/lua_api/lua_api_calc.cpp
  src/elona/lua_env/lua_api/lua_api_calc.hpp
  src/elona/lua_env/lua_api/lua_api_chara.cpp
  src/elona/lua_env/lua_api/lua_api_chara.hpp
  src/elona/lua_env/lua_api/lua_api_item.cpp
  src/elona/lua_env/lua_api/lua_api_map.cpp
  src/elona/lua_env/lua_api/lua_api_map.hpp
  src/elona/lua_env/lua_api/lua_api_world.cpp
  src/elona/lua_env/lua_api/lua_api_world.hpp
  src/elona/lua_env/lua_class/lua_class.cpp
  src/elona/lua_env/lua_class/lua_class_area.cpp
  src/elona/lua_env/lua_class/lua_class_character.cpp
  src/elona/lua_env/lua_class/lua_class_game_data.cpp
  src/elona/lua_env/lua_class/lua_class_item.cpp
  src/elona/lua_env/lua_class/lua_class_map_data.cpp
  src/elona/lua_env/lua_class/lua_class_map_generator.cpp
  src/elona/lua_env/lua_class/lua_class_map_generator.hpp
  src/elona/lua_env/lua_event/lua_event_nefia_created.hpp
  src/elona/map.cpp
  src/elona/map.hpp
  src/elona/map_chara_filter.cpp
  src/elona/mapgen.cpp
  src/elona/mapgen.hpp
  src/elona/talk_npc.cpp
  src/elona/text.cpp
  src/elona/variables.hpp
  src/tests/lua/i18n.lua
  src/tests/lua/item.lua
Labels: lua

#1257 Fix type error of buff descriptions
  runtime/profile/_/mod/core/data/buff.lua
Labels: bugfix
