Repository elonafoobar/elonafoobar, pull requests merged in 2019-06, with the labels that each got.

#1341 Add missing space in buff spell description
  src/elona/menu.cpp
Labels: bugfix

#1339 Fix trivial typo in ja [ci skip]
  runtime/mod/core/locale/jp/item.hcl
  runtime/mod/core/locale/jp/lazy/board.txt
  runtime/mod/core/locale/jp/race.hcl
Labels: bugfix

#1338 Add README's filename variants in mod details menu
  src/elona/ui/ui_menu_mod_info.cpp
  src/elona/ui/ui_menu_mod_info.hpp
Labels: enhancement

#1343 Fix text color of damage popup of atomic bomb
  src/elona/dmgheal.cpp
Labels: bugfix

#1346 Delete gdatan.s1, no longer necessary
  src/elona/ctrl_file.cpp
  src/elona/init.cpp
  src/elona/initialize_map_types.cpp
  src/elona/variables.hpp
Labels: refactoring

#1345 Fix strange behavior when you present gift
  src/elona/ctrl_inventory.cpp
Labels: bugfix

#1340 Add Lua API: Wish module
  doc/api/enums.luadoc
  doc/api/wish.luadoc
  src/elona/lua_env/enums/enums.cpp
  src/elona/lua_env/enums/enums.hpp
  src/elona/lua_env/lua_api/lua_api.cpp
  src/elona/lua_env/lua_api/lua_api.hpp
  src/elona/lua_env/lua_api/lua_api_wish.cpp
  src/elona/lua_env/lua_api/lua_api_wish.hpp
  src/elona/wish.cpp
  src/elona/wish.hpp
  src/util/strutil.hpp
  tools/docgen/src/main.rs
Labels: customization, enhancement, lua

#1350 Fix ldoc: LuaCharacter.image [ci skip]
  doc/api/classes/LuaCharacter.luadoc
  src/elona/lua_env/lua_class/lua_class_character.cpp
Labels: bugfix, lua

#1347 Fix luacheck
  Makefile
  runtime/mod/core/data/buff.lua
  runtime/mod/core/data/dialog/unique/loyter.lua
  runtime/mod/core/data/dialog/unique/mia.lua
  runtime/mod/core/data/dialog/unique/shena.lua
  runtime/mod/core/data/dialog/unique/whom_dwell_in_the_vanity.lua
  runtime/mod/core/exports/eating_effect.lua
  runtime/mod/core/exports/impl/shop_inventory.lua
  runtime/mod/core/i18n/functions.lua
  src/tests/lua/chara.lua
Labels: bugfix, lua

#1348 Fix broken symbolic links
  tools/i18n_checker/src/hclua
  tools/i18n_checker/src/hclua.lua
Labels: I18N, bugfix

#1337 Add Mods menu and Mods>Develop submenu to create a new mod from template
  runtime/locale/en/main_menu.hcl
  runtime/locale/jp/main_menu.hcl
  runtime/mod/template_blank/init.lua
  runtime/mod/template_blank/mod.hcl
  src/elona/filesystem.cpp
  src/elona/init.cpp
  src/elona/lua_env/mod_manager.cpp
  src/elona/lua_env/mod_manager.hpp
  src/elona/main_menu.cpp
  src/elona/main_menu.hpp
  src/elona/ui/ui_menu_mod_info.cpp
  src/elona/ui/ui_menu_mods.cpp
Labels: enhancement

#1349 Refactor: Look up character DB for the name of character cards
  runtime/locale/en/card_info.hcl
  runtime/locale/jp/card_info.hcl
  src/elona/get_card_info.cpp
Labels: refactoring

#1351 Fix i18n error: undefined building
  src/elona/text.cpp
Labels: bugfix

#1353 Fix PC's birth year
  src/elona/init.cpp
Labels: bugfix

#1352 Add new options: initial_key_repeat_wait / key_repeat_wait
  runtime/mod/core/config_def.hcl
  runtime/mod/core/locale/en/config.hcl
  runtime/mod/core/locale/jp/config.hcl
  runtime/profile/default/config.hcl
  src/elona/config/config.cpp
  src/elona/config/config.hpp
  src/elona/keybind/input_context.cpp
Labels: enhancement

#1354 Fix and improve change appearance menu
  src/elona/blending.cpp
  src/elona/character_making.cpp
  src/elona/command.cpp
  src/elona/ctrl_inventory.cpp
  src/elona/draw.cpp
  src/elona/draw.hpp
  src/elona/elonacore.cpp
  src/elona/equipment.cpp
  src/elona/init.cpp
  src/elona/item.cpp
  src/elona/item.hpp
  src/elona/menu.cpp
  src/elona/menu.hpp
  src/elona/save.cpp
  src/elona/ui/ui_menu_character_sheet.cpp
  src/elona/ui/ui_menu_equipment.cpp
  src/elona/variables.hpp
Labels: bugfix, enhancement, refactoring

#1355 Show [F]eat menu keyhint based on keybinding settings
  src/elona/ui/ui_menu_feats.cpp
Labels: bugfix

#1324 Reduce calls of Inventory::operator[]()
  src/elona/access_item_db.cpp
  src/elona/activity.cpp
  src/elona/adventurer.cpp
  src/elona/ai.cpp
  src/elona/blending.cpp
  src/elona/building.cpp
  src/elona/calc.cpp
  src/elona/casino.cpp
  src/elona/character.cpp
  src/elona/command.cpp
  src/elona/ctrl_inventory.cpp
  src/elona/dmgheal.cpp
  src/elona/elonacore.cpp
  src/elona/enchantment.cpp
  src/elona/enchantment.hpp
  src/elona/equipment.cpp
  src/elona/food.cpp
  src/elona/initialize_map_types.cpp
  src/elona/item.cpp
  src/elona/item.hpp
  src/elona/item_load_desc.cpp
  src/elona/itemgen.cpp
  src/elona/itemgen.hpp
  src/elona/lua_env/lua_api/lua_api_debug.cpp
  src/elona/lua_env/lua_api/lua_api_internal.cpp
  src/elona/magic.cpp
  src/elona/map.cpp
  src/elona/map_cell.cpp
  src/elona/mapgen.cpp
  src/elona/mef.cpp
  src/elona/proc_event.cpp
  src/elona/quest.cpp
  src/elona/shop.cpp
  src/elona/talk_house_visitor.cpp
  src/elona/talk_npc.cpp
  src/elona/turn_sequence.cpp
  src/elona/turn_sequence_pc_actions.cpp
  src/elona/variables.hpp
  src/tests/i18n.cpp
  src/tests/item.cpp
  src/tests/lua_callbacks.cpp
  src/tests/lua_handles.cpp
  src/tests/serialization.cpp
  src/tests/util.cpp
Labels: refactoring

#1331 Add MenuCursorHistory to restore the previous cursor position
  src/elona/main_menu.cpp
  src/elona/ui/menu_cursor_history.hpp
Labels: enhancement, refactoring

#1356 Implement F11, dump player information
  src/elona/CMakeLists.txt
  src/elona/dump_player_info.cpp
  src/elona/elonacore.cpp
  src/elona/item.cpp
  src/elona/item_load_desc.cpp
Labels: enhancement

#1261 Simplify config menu hierarchy
  src/elona/config/create_config_screen.cpp
  src/elona/config/create_config_screen.hpp
Labels: enhancement

#1359 Fix Discord's invite link in README [ci skip]
  runtime/README (en).txt
  runtime/README (ja).txt
Labels: bugfix

#1358 Fix stack_height/offset_y of item chip of simple rack
  runtime/mod/core/data/item_chip.lua
Labels: bugfix

#1363 Fix mod template
  runtime/mod/template_blank/mod.hcl
  src/elona/lua_env/mod_manager.cpp
Labels: bugfix

#1364 Fix f11 mojibake
  src/elona/dump_player_info.cpp
Labels: bugfix

#1368 Fix main menu crash when an unavailable option was selected via keyboard
  src/elona/main_menu.cpp
Labels: bugfix

#1369 Check if moyer is alive before writing his dialog
  src/elona/command.cpp
Labels: bugfix

#1371 Add string id based chara_find and replace hardcoded legacy ids
  src/elona/character.cpp
  src/elona/character.hpp
  src/elona/command.cpp
  src/elona/elonacore.cpp
  src/elona/initialize_map.cpp
  src/elona/proc_event.cpp
  src/elona/talk.cpp
  src/elona/talk_npc.cpp
Labels: refactoring

#1374 Fix typo and i18n errors
  runtime/locale/en/quest.hcl
  runtime/locale/en/talk_unique.hcl
  runtime/locale/jp/magic.hcl
  runtime/locale/jp/quest.hcl
  runtime/locale/jp/talk_npc.hcl
  runtime/locale/jp/talk_unique.hcl
  runtime/mod/core/data/dialog/unique/icolle.lua
  runtime/mod/core/locale/en/lazy/book.txt
  src/elona/quest.cpp
  src/elona/talk_npc.cpp
Labels: I18N, bugfix

#1376 Add [[nodiscard]] attribute to i18n functions
  src/elona/command.cpp
  src/elona/elonacore.cpp
  src/elona/i18n.hpp
  src/elona/macro.hpp
Labels: bugfix, refactoring

#1377 Separate access_item_db() into some functions
  src/elona/CMakeLists.txt
  src/elona/access_item_db.cpp
  src/elona/calc.cpp
  src/elona/command.cpp
  src/elona/ctrl_inventory.cpp
  src/elona/elonacore.cpp
  src/elona/item.cpp
  src/elona/item.hpp
  src/elona/item_db.cpp
  src/elona/itemgen.cpp
  src/elona/magic.cpp
  src/elona/mef.cpp
  src/elona/turn_sequence.cpp
Labels: refactoring

#1379 Fix crash on charamaking
  src/elona/character_making.cpp
  src/elona/ui/ui_menu_charamake_class.cpp
  src/elona/ui/ui_menu_charamake_class.hpp
  src/elona/ui/ui_menu_charamake_race.cpp
Labels: bugfix

#1382 Fix build error: SSL_R_SHORT_READ is undefined in OpenSSL 1.1 or later
  src/spider/http/backends/boost_asio/request.cpp
Labels: bugfix, build

#1385 Improve error messages on failure to send/receive messages
  runtime/locale/en/net.hcl
  runtime/locale/jp/net.hcl
  src/elona/net.cpp
Labels: enhancement, network

#1386 Add Data API to get data object
  doc/api/data.luadoc
  doc/api/registry.luadoc
  runtime/mod/core/data/dialog/unique/doria.lua
  runtime/mod/core/data/shop_inventory.lua
  runtime/mod/core/exports/impl/chara_drop.lua
  runtime/mod/core/exports/impl/shop_inventory.lua
  runtime/mod/core/exports/impl/show_dialog.lua
  src/elona/lua_env/lua_api/lua_api_data.cpp
  src/elona/lua_env/lua_api/lua_api_data.hpp
Labels: lua, refactoring

#1390 Fix SSL error
  src/elona/lua_env/console.cpp
  src/elona/net.cpp
  src/elona/ui/ui_menu_voting_box.cpp
  src/spider/http/backends/boost_asio/request.cpp
Labels: bugfix, network

#1389 Support data-update.lua
  src/elona/lua_env/data_manager.cpp
  src/tests/data/registry/load_order/data-update.lua
  src/tests/data/registry/load_order/data.lua
  src/tests/data/registry/load_order/init.lua
  src/tests/data/registry/load_order/mod.hcl
  src/tests/lua_data.cpp
Labels: customization, enhancement, lua
