Repository elonafoobar/elonafoobar, pull requests merged in 2019-11, with the labels that each got.

#1451 Fix typo: 不振 -> 不審
  runtime/locale/jp/activity.hcl
  runtime/mod/core/locale/jp/lazy/scene.hsp
Labels: bugfix

#1449 Fix switch statement's fall-through
  src/elona/chara_db.cpp
Labels: bugfix

#1447 Fix for loop whose end changes at random in each loop
  src/elona/magic.cpp
  src/elona/mapgen.cpp
Labels: bugfix

#1448 Fix non-exhaustive switch cases / 3xx redirect handling
  src/spider/http/backends/boost_asio/request.cpp
  src/spider/http/error.hpp
Labels: bugfix, refactoring

#1453 Lua API: unify Config.get_{type} and Config.set_{type}
  doc/api/config.luadoc
  doc/topics/config.md
  src/elona/config/config.hpp
  src/elona/lua_env/lua_api/lua_api_config.cpp
  src/elona/lua_env/lua_api/lua_api_config.hpp
  src/tests/lua/config.lua
  src/tests/lua_api.cpp
Labels: enhancement, lua

#1452 Fix #1450: duplicated map exit bug
  runtime/locale/en/event.hcl
  runtime/locale/jp/event.hcl
  src/elona/proc_event.cpp
  src/elona/ui.cpp
  src/elona/ui.hpp
Labels: bugfix

#1456 Update 3rd-party library, sol2, from v2.20.2 to v2.20.6
  README.md
  src/thirdparty/sol2/LICENSE.txt
  src/thirdparty/sol2/sol.hpp
  src/thirdparty/sol2/sol_forward.hpp
Labels: 2: Improvement, 3: Development

#1455 Fix deferred event
  src/elona/CMakeLists.txt
  src/elona/ctrl_file.cpp
  src/elona/deferred_event.cpp
  src/elona/deferred_event.hpp
  src/elona/dmgheal.cpp
  src/elona/elona.hpp
  src/elona/elonacore.cpp
  src/elona/event.cpp
  src/elona/event.hpp
  src/elona/food.cpp
  src/elona/init.cpp
  src/elona/initialize_map.cpp
  src/elona/initialize_map_types.cpp
  src/elona/lua_env/lua_api/lua_api_world.cpp
  src/elona/mef.cpp
  src/elona/quest.cpp
  src/elona/random_event.cpp
  src/elona/std.cpp
  src/elona/talk.cpp
  src/elona/talk_npc.cpp
  src/elona/turn_sequence.cpp
  src/elona/variables.hpp
  src/elona/wish.cpp
  src/putit/archive/binary_archive.hpp
Labels: 1: Bug, 2: Refactoring, 8: Vanilla

#1458 Remove unused variables
  src/elona/activity.cpp
  src/elona/casino.cpp
  src/elona/command.cpp
  src/elona/ctrl_inventory.cpp
  src/elona/elonacore.cpp
  src/elona/init.cpp
  src/elona/menu.cpp
  src/elona/talk.cpp
  src/elona/ui.cpp
  src/elona/variables.hpp
Labels: 2: Refactoring

#1460 Change 'BreakStringLiterals' option in .clang-format to 'true'
  .clang-format
  src/elona/activity.cpp
  src/elona/ai.cpp
  src/elona/blending.cpp
  src/elona/casino.cpp
  src/elona/character_making.cpp
  src/elona/character_status.cpp
  src/elona/command.cpp
  src/elona/ctrl_inventory.cpp
  src/elona/dmgheal.cpp
  src/elona/elonacore.cpp
  src/elona/enchantment.cpp
  src/elona/food.cpp
  src/elona/item.cpp
  src/elona/lua_env/lua_api/lua_api_internal.cpp
  src/elona/lua_env/mod_serializer.hpp
  src/elona/magic.cpp
  src/elona/quest.cpp
  src/elona/talk.cpp
  src/elona/talk_house_visitor.cpp
  src/elona/talk_npc.cpp
  src/elona/turn_sequence.cpp
  src/elona/ui/ui_menu_ctrl_ally.cpp
Labels: 2: Refactoring

#1459 Refactor: avoid direct index access to inv, instead use Item&
  src/elona/adventurer.cpp
  src/elona/blending.cpp
  src/elona/blending.hpp
  src/elona/building.cpp
  src/elona/command.cpp
  src/elona/ctrl_inventory.cpp
  src/elona/elonacore.cpp
  src/elona/enchantment.cpp
  src/elona/enchantment.hpp
  src/elona/equipment.cpp
  src/elona/food.cpp
  src/elona/food.hpp
  src/elona/item.cpp
  src/elona/item.hpp
  src/elona/item_load_desc.cpp
  src/elona/itemgen.cpp
  src/elona/magic.cpp
  src/elona/menu.cpp
  src/elona/menu.hpp
  src/elona/turn_sequence.cpp
  src/elona/ui/ui_menu_equipment.cpp
  src/elona/variables.hpp
  src/tests/util.cpp
Labels: 2: Refactoring

#1457 Refactor character AI routines
  src/elona/_putit/character.cpp
  src/elona/ai.cpp
  src/elona/ai.hpp
  src/elona/character.hpp
  src/elona/elonacore.cpp
  src/elona/init.cpp
  src/elona/turn_sequence.cpp
  src/elona/variables.hpp
Labels: 2: Refactoring

#1461 Change txt() function's signature; taking only 1 text as argument
  runtime/locale/en/ai.hcl
  runtime/locale/en/magic.hcl
  runtime/locale/en/map.hcl
  runtime/locale/jp/ai.hcl
  runtime/locale/jp/magic.hcl
  runtime/locale/jp/map.hcl
  runtime/locale/jp/ui.hcl
  src/elona/ai.cpp
  src/elona/chara_db.cpp
  src/elona/magic.cpp
  src/elona/map_special_events.cpp
  src/elona/message.cpp
  src/elona/message.hpp
Labels: 2: Refactoring

#1464 Fixed a bug that the game does not start.
  src/elona/init.cpp
Labels: 1: Bug

#1462 Eliminate *all* goto statements
  runtime/locale/en/map.hcl
  runtime/locale/jp/map.hcl
  src/elona/blending.cpp
  src/elona/command.cpp
  src/elona/ctrl_inventory.cpp
  src/elona/dmgheal.cpp
  src/elona/elonacore.cpp
  src/elona/initialize_map.cpp
  src/elona/item.cpp
  src/elona/magic.cpp
  src/elona/main_menu.cpp
  src/elona/menu.cpp
  src/elona/text.cpp
  src/elona/turn_sequence.cpp
  src/elona/turn_sequence.hpp
  src/elona/variables.hpp
Labels: 2: Refactoring

#1466 Fix wrong forward declaration [ci skip]
  src/elona/ui/ui_menu_mod_info.hpp
Labels: 2: Refactoring

#1465 Add missing #pragma once directive [ci skip]
  src/elona/data/types/type_buff.hpp
Labels: 2: Refactoring

#1467 Hide config sections marked as hidden in Options menu
  runtime/data/script/kernel/config_dsl.lua
Labels: 1: Bug

#1470 Fix Travis CI build on macOS: brew upgrade wget
  .travis.yml
Labels: 1: Bug, 3: CI

#1468 Fix up #1455
  src/elona/deferred_event.cpp
  src/elona/init.cpp
Labels: 1: Bug

#1469 Refactor src/elona/activity.cpp
  src/elona/activity.cpp
  src/elona/activity.hpp
  src/elona/command.cpp
  src/elona/dmgheal.cpp
  src/elona/elonacore.cpp
  src/elona/item.cpp
  src/elona/magic.cpp
  src/elona/turn_sequence.cpp
  src/elona/turn_sequence_pc_actions.cpp
  src/elona/ui/ui_menu_journal.cpp
  src/elona/variables.hpp
Labels: 2: Refactoring

#1474 Fix various config error
  runtime/data/script/kernel/config.lua
  runtime/mod/core/config-schema.lua
  src/elona/config.cpp
  src/elona/config_menu.hpp
Labels: 1: Bug
