Repository elonafoobar/elonafoobar, pull requests merged in 2019-12, with the labels that each got.

#1477 add digital clock option in core->foobar
  runtime/locale/en/ui.hcl
  runtime/locale/jp/ui.hcl
  runtime/mod/core/config-schema.lua
  runtime/mod/core/locale/en/config.hcl
  runtime/mod/core/locale/jp/config.hcl
  runtime/profile/default/config.json
  src/elona/config.cpp
  src/elona/config.hpp
  src/elona/ui.cpp
Labels: 2: Improvement, 6: UI

#1471 Refactor: avoid index access of inv
  src/elona/activity.cpp
  src/elona/adventurer.cpp
  src/elona/ai.cpp
  src/elona/blending.cpp
  src/elona/building.cpp
  src/elona/calc.cpp
  src/elona/calc.hpp
  src/elona/casino.cpp
  src/elona/character.cpp
  src/elona/character.hpp
  src/elona/command.cpp
  src/elona/crafting.cpp
  src/elona/ctrl_inventory.cpp
  src/elona/deferred_event.cpp
  src/elona/elonacore.cpp
  src/elona/equipment.cpp
  src/elona/fish.cpp
  src/elona/fish.hpp
  src/elona/food.cpp
  src/elona/food.hpp
  src/elona/god.cpp
  src/elona/god.hpp
  src/elona/initialize_map.cpp
  src/elona/initialize_map_types.cpp
  src/elona/item.cpp
  src/elona/item.hpp
  src/elona/item_db.cpp
  src/elona/itemgen.cpp
  src/elona/itemgen.hpp
  src/elona/lua_env/handle_manager.cpp
  src/elona/lua_env/lua_api/lua_api_internal.cpp
  src/elona/lua_env/lua_api/lua_api_item.cpp
  src/elona/lua_env/lua_env.cpp
  src/elona/magic.cpp
  src/elona/map.cpp
  src/elona/mapgen.cpp
  src/elona/menu.cpp
  src/elona/quest.cpp
  src/elona/random_event.cpp
  src/elona/talk.cpp
  src/elona/talk.hpp
  src/elona/talk_house_visitor.cpp
  src/elona/talk_npc.cpp
  src/elona/turn_sequence.cpp
  src/elona/variables.hpp
  src/elona/wish.cpp
  src/tests/item.cpp
  src/tests/lua_callbacks.cpp
  src/tests/lua_handles.cpp
  src/tests/serialization.cpp
  src/tests/util.cpp
Labels: 2: Refactoring

#1483 Remove unnecessary assertion error which causes crash
  src/elona/quest.cpp
Labels: 1: Bug, 1: Crash / Freeze

#1482 Add party auto target option in core->foobar. It will only target ene…
  runtime/mod/core/config-schema.lua
  runtime/mod/core/locale/en/config.hcl
  runtime/mod/core/locale/jp/config.hcl
  runtime/profile/default/config.json
  src/elona/config.cpp
  src/elona/config.hpp
  src/elona/elonacore.cpp
  src/elona/turn_sequence_pc_actions.cpp
  src/elona/variables.hpp
Labels: 2: Improvement, 6: UI

#1486 Mention parallel build in README for developers [ci skip]
  README.md
Labels: 2: Improvement, 3: Development, 6: Documentation

#1485 Fix Elona crash related to config options
  runtime/data/script/kernel/config.lua
  src/elona/config.cpp
  src/elona/config_menu.cpp
Labels: 1: Bug, 1: Crash / Freeze

#1484 Limit some of rnd()'s range to emulate vanilla rnd() function.
  doc/api/config.luadoc
  doc/api/json5.luadoc
  doc/api/rand.luadoc
  runtime/mod/core/data/chara_drop.lua
  src/elona/activity.cpp
  src/elona/adventurer.cpp
  src/elona/buff.cpp
  src/elona/building.cpp
  src/elona/calc.cpp
  src/elona/casino.cpp
  src/elona/character.cpp
  src/elona/command.cpp
  src/elona/dmgheal.cpp
  src/elona/elonacore.cpp
  src/elona/food.cpp
  src/elona/item.cpp
  src/elona/itemgen.cpp
  src/elona/lua_env/lua_api/lua_api_rand.cpp
  src/elona/lua_env/lua_api/lua_api_rand.hpp
  src/elona/magic.cpp
  src/elona/map.cpp
  src/elona/mapgen.cpp
  src/elona/mef.cpp
  src/elona/quest.cpp
  src/elona/random.hpp
  src/elona/random_event.cpp
  src/elona/status_ailment.cpp
  src/elona/talk_npc.cpp
  src/elona/turn_sequence.cpp
Labels: 2: Improvement

#1487 Fix #1229; you cannot run/attack fast
  src/elona/keybind/input_context.cpp
Labels: 1: Bug
