Repository elonafoobar/elonafoobar, pull requests merged in 2019-01, with the labels that each got.

#1111 Fix log window
  CHANGELOG-jp.md
  CHANGELOG.md
  runtime/locale/en/ui.hcl
  runtime/locale/jp/ui.hcl
  src/elona/ui/ui_menu_chat_history.cpp
  src/elona/ui/ui_menu_message_log.cpp
Labels: bugfix, enhancement

#1110 Fix reference to undefined buff
  src/elona/magic.cpp
Labels: bugfix

#1112 Move src/elona/version.* to src/version.*
  .gitignore
  CMakeLists.txt
  src/elona/Android.mk
  src/elona/CMakeLists.txt
  src/elona/elonacore.cpp
  src/elona/gdata.hpp
  src/elona/init.cpp
  src/elona/main_menu.cpp
  src/elona/testing.cpp
  src/main.cpp
  src/version.cpp.in
  src/version.hpp
Labels: build, refactoring

#1114 Fix typo
  runtime/locale/en/death.hcl
  runtime/locale/en/mod.hcl
  runtime/locale/en/status_ailment.hcl
  runtime/mods/core/data/item.lua
  runtime/mods/core/locale/en/item.hcl
  runtime/mods/core/locale/jp/item.hcl
  src/elona/talk_npc.cpp
Labels: I18N, bugfix

#1115 Delete unused directories for deployment
  CMakeLists.txt
  appveyor.yml
  runtime/original/lastwords-e.txt
  runtime/original/lastwords.txt
Labels: build

#1116 Organize util module
  src/elona/ability.cpp
  src/elona/autopick.cpp
  src/elona/buff.cpp
  src/elona/building.cpp
  src/elona/character.cpp
  src/elona/character.hpp
  src/elona/config/config.cpp
  src/elona/ctrl_file.cpp
  src/elona/ctrl_inventory.cpp
  src/elona/dialog/dialog_decoder.cpp
  src/elona/elona.hpp
  src/elona/elonacore.cpp
  src/elona/filesystem.hpp
  src/elona/food.cpp
  src/elona/i18n.hpp
  src/elona/init.cpp
  src/elona/input.cpp
  src/elona/item.cpp
  src/elona/item.hpp
  src/elona/item_load_desc.cpp
  src/elona/keybind/input_context.cpp
  src/elona/keybind/key_names.cpp
  src/elona/keybind/keybind.cpp
  src/elona/keybind/keybind_manager.cpp
  src/elona/lua_env/lua_console.cpp
  src/elona/message.cpp
  src/elona/save_update.cpp
  src/elona/spec.hpp
  src/elona/std.cpp
  src/elona/talk_unique.cpp
  src/elona/text.cpp
  src/elona/trait.cpp
  src/elona/ui.cpp
  src/elona/ui/ui_menu_feats.cpp
  src/elona/ui/ui_menu_game_help.cpp
  src/elona/wish.cpp
  src/util/Android.mk
  src/util/CMakeLists.txt
  src/util/README.md
  src/util/fileutil.hpp
  src/util/profiler.cpp
  src/util/profiler.hpp
  src/util/range.hpp
  src/util/strutil.hpp
Labels: refactoring

#1113 Separate function magic() into each effect
  src/elona/ai.cpp
  src/elona/building.cpp
  src/elona/command.cpp
  src/elona/elonacore.cpp
  src/elona/god.cpp
  src/elona/lua_env/lua_api/lua_api_magic.cpp
  src/elona/magic.cpp
  src/elona/magic.hpp
  src/elona/menu.cpp
  src/elona/random_event.cpp
  src/elona/talk_house_visitor.cpp
  src/elona/talk_npc.cpp
  src/elona/turn_sequence.cpp
  src/elona/turn_sequence_pc_actions.cpp
  src/elona/variables.hpp
Labels: refactoring

#1120 Delete filter_creature and use CharaData::filter instead
  src/elona/character.cpp
  src/elona/character.hpp
  src/elona/get_random_npc_id.cpp
  src/elona/init.cpp
  src/elona/variables.hpp
Labels: refactoring

#1126 Fix number of enchantment stars in character sheet
  src/elona/ui/ui_menu_character_sheet.cpp
Labels: bugfix

#1127 Fix prompt with number not returning input number
  src/elona/blending.cpp
  src/elona/input.cpp
  src/elona/input.hpp
  src/elona/input_prompt.cpp
  src/elona/input_prompt.hpp
Labels: bugfix

#1121 Add experimental file dialog support
  CMakeLists.txt
  README-jp.md
  README.md
  src/snail/CMakeLists.txt
  src/snail/filedialog.cpp
  src/snail/filedialog.hpp
  src/snail/filedialog/headless.cpp
  src/snail/filedialog/sdl.cpp
  src/thirdparty/nfd/.gitattributes
  src/thirdparty/nfd/CMakeLists.txt
  src/thirdparty/nfd/LICENSE
  src/thirdparty/nfd/common.h
  src/thirdparty/nfd/include/nfd.h
  src/thirdparty/nfd/nfd_cocoa.m
  src/thirdparty/nfd/nfd_common.c
  src/thirdparty/nfd/nfd_common.h
  src/thirdparty/nfd/nfd_gtk.c
  src/thirdparty/nfd/nfd_win.cpp
  src/thirdparty/nfd/nfd_zenity.c
  src/thirdparty/nfd/simple_exec.h
Labels: enhancement

#1128 Refactor several UI functions
  src/elona/blending.cpp
  src/elona/building.cpp
  src/elona/card.cpp
  src/elona/character_making.cpp
  src/elona/command.cpp
  src/elona/ctrl_inventory.cpp
  src/elona/elonacore.cpp
  src/elona/main_menu.cpp
  src/elona/menu.cpp
  src/elona/turn_sequence_pc_actions.cpp
  src/elona/ui.cpp
  src/elona/ui.hpp
  src/elona/ui/ui_menu_adventurers.cpp
  src/elona/ui/ui_menu_alias.cpp
  src/elona/ui/ui_menu_character_sheet.cpp
  src/elona/ui/ui_menu_charamake_alias.cpp
  src/elona/ui/ui_menu_charamake_attributes.cpp
  src/elona/ui/ui_menu_charamake_class.cpp
  src/elona/ui/ui_menu_charamake_gender.cpp
  src/elona/ui/ui_menu_charamake_race.cpp
  src/elona/ui/ui_menu_config.cpp
  src/elona/ui/ui_menu_crafting.cpp
  src/elona/ui/ui_menu_ctrl_ally.cpp
  src/elona/ui/ui_menu_equipment.cpp
  src/elona/ui/ui_menu_feats.cpp
  src/elona/ui/ui_menu_game_help.cpp
  src/elona/ui/ui_menu_hire.cpp
  src/elona/ui/ui_menu_item_desc.cpp
  src/elona/ui/ui_menu_keybindings.cpp
  src/elona/ui/ui_menu_npc_tone.cpp
  src/elona/ui/ui_menu_skills.cpp
  src/elona/ui/ui_menu_spell_writer.cpp
  src/elona/ui/ui_menu_spells.cpp
  src/elona/ui/ui_menu_town_chart.cpp
  src/elona/variables.hpp
Labels: refactoring

#1130 Fix text color in list menu
  src/elona/blending.cpp
  src/elona/card.cpp
  src/elona/casino.cpp
  src/elona/ctrl_inventory.cpp
  src/elona/menu.cpp
  src/elona/talk.cpp
  src/elona/ui.cpp
  src/elona/ui.hpp
  src/elona/ui/ui_menu_config.cpp
  src/elona/ui/ui_menu_crafting.cpp
  src/elona/ui/ui_menu_ctrl_ally.cpp
  src/elona/ui/ui_menu_ctrl_ally.hpp
  src/elona/ui/ui_menu_dialog.cpp
  src/elona/ui/ui_menu_equipment.cpp
  src/elona/ui/ui_menu_feats.cpp
  src/elona/ui/ui_menu_game_help.cpp
  src/elona/ui/ui_menu_materials.cpp
  src/elona/ui/ui_menu_town_politics.cpp
  src/snail/filedialog/sdl.cpp
Labels: bugfix

#1135 Delete wrong assert() in Handle.relocate_handle()
  runtime/data/lua/handle.lua
Labels: bug

#1153 Fix LDoc
  .gitignore
  Makefile
  doc/api/classes/LuaCharacter.luadoc
  doc/api/input.luadoc
  doc/api/rand.luadoc
  doc/ldoc.css
  doc/ldoc.ltp
  doc/putit.png
  doc/red_putit.png
  docs/classes/LuaCharacter.html
  docs/classes/LuaItem.html
  docs/classes/LuaPosition.html
  docs/examples/examples/life.lua
  docs/examples/life.lua.html
  docs/index.html
  docs/ldoc.css
  docs/modules/Animation.html
  docs/modules/Chara.html
  docs/modules/Debug.html
  docs/modules/Enums.html
  docs/modules/Event.EventKind.html
  docs/modules/Event.html
  docs/modules/FOV.html
  docs/modules/GUI.html
  docs/modules/I18N.html
  docs/modules/Input.html
  docs/modules/Item.html
  docs/modules/Iter.html
  docs/modules/Magic.html
  docs/modules/Map.html
  docs/modules/Math.html
  docs/modules/Pos.html
  docs/modules/Rand.html
  docs/modules/Registry.html
  docs/modules/Skill.html
  docs/modules/Trait.html
  docs/modules/World.html
  docs/putit.png
  docs/red_putit.png
  docs/topics/i18n.md.html
  docs/topics/i18n_functions.md.html
  docs/topics/readme.md.html
Labels: bugfix, enhancement

#1152 Add missing key help in housing: ctrl+left click
  runtime/locale/en/building.hcl
  runtime/locale/jp/building.hcl
Labels: bugfix

#1150 Fix default key bindings of x and X
  src/elona/keybind/keybind_actions.cpp
Labels: bugfix

#1148 Fix *win* commnet not being shown in *win* window
  runtime/locale/en/scenario.hcl
  runtime/locale/jp/scenario.hcl
  src/elona/elonacore.cpp
  src/elona/random.hpp
  src/elona/text.cpp
  src/elona/variables.hpp
Labels: bugfix

#1147 Delete unnecessary files before deployment
  appveyor.yml
Labels: bugfix, build

#1146 Update ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: enhancement

#1144 Reverse heirloom ranking
  src/elona/building.cpp
Labels: enhancement

#1122 Change View Homepage in main menu to About
  runtime/locale/en/main_menu.hcl
  runtime/locale/jp/main_menu.hcl
  src/elona/Android.mk
  src/elona/CMakeLists.txt
  src/elona/browser.cpp
  src/elona/browser.hpp
  src/elona/elona.hpp
  src/elona/main_menu.cpp
  src/elona/main_menu.hpp
  src/elona/menu.cpp
  src/elona/std.cpp
  src/elona/variables.hpp
Labels: enhancement

#1145 Add utility to increment foobar's version
  tools/incver.py
Labels: enhancement

#1154 Fix broken links in READMEs
  README-jp.md
  README.md
  src/elona/index.html
Labels: bugfix

#1155 Support GitHub's multiple issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#1157 Organize Makefiles
  .travis.yml
  CMakeLists.txt
  Makefile
  Makefile.win
  README-jp.md
  README.md
  appveyor.yml
  cmake/lua/CMakeLists.txt
  src/elona/CMakeLists.txt
  src/snail/CMakeLists.txt
  src/snail/filedialog/sdl.cpp
  src/thirdparty/nfd/CMakeLists.txt
  src/thirdparty/nfd/nfd.h
  src/thirdparty/nfd/nfd_zenity.c
Labels: build

#1158 Fix crash when you Return
  runtime/mods/core/data/map.lua
  src/elona/area.cpp
  src/elona/data/types/type_map.cpp
  src/elona/data/types/type_map.hpp
Labels: bugfix

#1156 Restore default environment of Lua console
  src/elona/lua_env/lua_console.cpp
  src/elona/lua_env/lua_console.hpp
Labels: bugfix

#1160 Do not define "DEBUG" in release build
  CMakeLists.txt
Labels: bugfix, build

#1165 Fix quick menu not shining
  src/elona/menu_quick_menu.cpp
Labels: bugfix

#1168 Delete unused map files
  README-jp.md
  README.md
  runtime/map/Juerefarm1.idx
  runtime/map/Juerefarm1.map
  runtime/map/Juerefarm1.obj
  runtime/map/Juerefarm2.idx
  runtime/map/Juerefarm2.map
  runtime/map/Juerefarm2.obj
  runtime/map/Maincamp.idx
  runtime/map/Maincamp.map
  runtime/map/Maincamp.obj
  runtime/map/Outpost1.idx
  runtime/map/Outpost1.map
  runtime/map/Outpost1.obj
  runtime/map/Wizardtower.idx
  runtime/map/Wizardtower.map
  runtime/map/Wizardtower.obj
  runtime/map/black.idx
  runtime/map/black.map
  runtime/map/black.obj
  runtime/map/file.idx
  runtime/map/file.map
  runtime/map/i.idx
  runtime/map/i.map
  runtime/map/i.obj
  runtime/map/n.idx
  runtime/map/n.map
  runtime/map/n.obj
  runtime/map/ntyris2.idx
  runtime/map/ntyris2.map
  runtime/map/ntyris2.obj
  runtime/map/outpost2.idx
  runtime/map/outpost2.map
  runtime/map/outpost2.obj
  runtime/map/outpost3.idx
  runtime/map/outpost3.map
  runtime/map/outpost3.obj
  runtime/map/s.idx
  runtime/map/s.map
  runtime/map/s.obj
  runtime/map/shadyjueretown.idx
  runtime/map/shadyjueretown.map
  runtime/map/shadyjueretown.obj
  runtime/map/stati.idx
  runtime/map/stati.map
  runtime/map/stati.obj
  runtime/map/statio.idx
  runtime/map/statio.map
  runtime/map/statio.obj
  runtime/map/t.idx
  runtime/map/t.map
  runtime/map/t.obj
  runtime/map/unfinishedkeep.idx
  runtime/map/unfinishedkeep.map
  runtime/map/unfinishedkeep.obj
Labels: enhancement

#1167 Improve ELONA_LOG() macro and output well-formatted logs
  src/elona/audio.cpp
  src/elona/config/config.cpp
  src/elona/config/config.hpp
  src/elona/ctrl_file.cpp
  src/elona/data/lua_lazy_cache.hpp
  src/elona/i18n.hpp
  src/elona/keybind/keybind.cpp
  src/elona/log.cpp
  src/elona/log.hpp
  src/elona/lua_env/api_manager.cpp
  src/elona/lua_env/event_manager.cpp
  src/elona/lua_env/lua_api/lua_api_debug.cpp
  src/elona/lua_env/lua_enums.hpp
  src/elona/lua_env/mod_manager.cpp
  src/elona/save.cpp
  src/elona/save_update.cpp
  src/elona/std.cpp
  src/elona/testing.cpp
  src/main.cpp
  src/tests/serialization.cpp
Labels: enhancement

#1170 Fix glitch of crossbow animation
  src/elona/animation.cpp
Labels: bugfix

#1171 Fix {sex} tag being always substituted by male
  src/elona/text.cpp
Labels: bugfix

#1172 Remove some config options
  Makefile
  runtime/config.hcl
  runtime/locale/en/config.hcl
  runtime/locale/jp/config.hcl
  runtime/mods/core/config/config_def.hcl
  src/elona/activity.cpp
  src/elona/animation.cpp
  src/elona/audio.cpp
  src/elona/blending.cpp
  src/elona/building.cpp
  src/elona/cell_draw.cpp
  src/elona/config/config.cpp
  src/elona/config/config.hpp
  src/elona/dmgheal.cpp
  src/elona/elonacore.cpp
  src/elona/god.cpp
  src/elona/init.cpp
  src/elona/input.cpp
  src/elona/keybind/input_context.cpp
  src/elona/lua_env/lua_console.cpp
  src/elona/magic.cpp
  src/elona/main_menu.cpp
  src/elona/menu.cpp
  src/elona/message.cpp
  src/elona/proc_event.cpp
  src/elona/random_event.cpp
  src/elona/std.cpp
  src/elona/talk.cpp
  src/elona/talk_house_visitor.cpp
  src/elona/turn_sequence.cpp
  src/elona/ui.cpp
  src/elona/ui/ui_menu_charamake_class.cpp
  src/elona/ui/ui_menu_charamake_race.cpp
  src/elona/ui/ui_menu_config.cpp
  src/elona/ui/ui_menu_keybindings.cpp
  src/elona/ui/ui_menu_message_log.cpp
  src/elona/variables.hpp
Labels: enhancement

#1175 Fix message text's color in TCG
  src/elona/tcg.cpp
Labels: bugfix

#1176 Fix game help text being blurred
  src/elona/ui.cpp
  src/elona/ui/ui_menu_game_help.cpp
  src/elona/ui/ui_menu_game_help.hpp
Labels: bugfix
