Repository elonafoobar/elonafoobar, pull requests merged in 2019-05, with the labels that each got.

#1262 Add default_choice option to all unique NPCs
  runtime/profile/_/mod/core/data/dialog.lua
  runtime/profile/_/mod/core/data/dialog/unique.lua
  runtime/profile/_/mod/core/data/dialog/unique/ainc.lua
  runtime/profile/_/mod/core/data/dialog/unique/arnord.lua
  runtime/profile/_/mod/core/data/dialog/unique/balzak.lua
  runtime/profile/_/mod/core/data/dialog/unique/conery.lua
  runtime/profile/_/mod/core/data/dialog/unique/erystia.lua
  runtime/profile/_/mod/core/data/dialog/unique/gilbert.lua
  runtime/profile/_/mod/core/data/dialog/unique/icolle.lua
  runtime/profile/_/mod/core/data/dialog/unique/kaneda_bike.lua
  runtime/profile/_/mod/core/data/dialog/unique/lily.lua
  runtime/profile/_/mod/core/data/dialog/unique/loyter.lua
  runtime/profile/_/mod/core/data/dialog/unique/marks.lua
  runtime/profile/_/mod/core/data/dialog/unique/mia.lua
  runtime/profile/_/mod/core/data/dialog/unique/miches.lua
  runtime/profile/_/mod/core/data/dialog/unique/noel.lua
  runtime/profile/_/mod/core/data/dialog/unique/part_time_worker.lua
  runtime/profile/_/mod/core/data/dialog/unique/raphael.lua
  runtime/profile/_/mod/core/data/dialog/unique/rilian.lua
  runtime/profile/_/mod/core/data/dialog/unique/shena.lua
  runtime/profile/_/mod/core/data/dialog/unique/tam.lua
  runtime/profile/_/mod/core/exports/impl/show_dialog.lua
  src/elona/lua_env/lua_api/lua_api_input.cpp
  src/elona/talk.cpp
Labels: bugfix

#1268 Fix up #1263
  CMakeLists.txt
  runtime/mod/core/graphic/enchantment_icons.png
Labels: bugfix

#1270 Fix prompt not clearing key repeat state
  src/elona/input_prompt.cpp
Labels: bugfix

#1269 Fix strange item's subcategory
  runtime/mod/core/data/item.hcl
Labels: bugfix

#1272 Fix playing card's characters being colored
  src/elona/casino_card.cpp
Labels: bugfix

#1273 Fix typo
  runtime/locale/en/ai.hcl
  runtime/locale/en/class.hcl
  runtime/locale/en/ctrl_inventory.hcl
  runtime/locale/en/event.hcl
  runtime/locale/en/misc.hcl
  runtime/locale/en/quest_journal.hcl
  runtime/locale/en/wish.hcl
  runtime/locale/jp/class.hcl
  runtime/locale/jp/misc.hcl
  runtime/mod/core/locale/jp/item.hcl
  src/elona/casino.cpp
  src/elona/class.cpp
  src/elona/ui/ui_menu_charamake_class.cpp
Labels: bugfix

#1276 Fix various typo in item's flavor text
  runtime/mod/core/locale/jp/item.hcl
Labels: bugfix

#1275 Add @noluadoc directive to suppress unnecessary document generation
  doc/api/chara.luadoc
  doc/api/classes/LuaMapGenerator.luadoc
  doc/api/item.luadoc
  doc/api/registry.luadoc
  src/elona/lua_env/lua_api/lua_api.cpp
  src/elona/lua_env/lua_class/lua_class.cpp
  tools/docgen/src/main.rs
Labels: bugfix

#1277 Improve performance of text rendering with shadow
  CMakeLists.txt
  src/elona/draw.cpp
  src/snail/Android.mk.in
  src/snail/CMakeLists.txt
  src/snail/Makefile
  src/snail/application.cpp
  src/snail/audio.cpp
  src/snail/backends/headless/application.cpp
  src/snail/backends/headless/audio.cpp
  src/snail/backends/headless/detail.cpp
  src/snail/backends/headless/filedialog.cpp
  src/snail/backends/headless/hsp.cpp
  src/snail/backends/headless/messagebox.cpp
  src/snail/backends/headless/renderer.cpp
  src/snail/backends/headless/touch_input.cpp
  src/snail/backends/headless/window.cpp
  src/snail/backends/sdl/application.cpp
  src/snail/backends/sdl/audio.cpp
  src/snail/backends/sdl/detail.cpp
  src/snail/backends/sdl/filedialog.cpp
  src/snail/backends/sdl/hsp.cpp
  src/snail/backends/sdl/messagebox.cpp
  src/snail/backends/sdl/renderer.cpp
  src/snail/backends/sdl/touch_input.cpp
  src/snail/backends/sdl/window.cpp
  src/snail/detail/sdl.cpp
  src/snail/filedialog.cpp
  src/snail/hsp.cpp
  src/snail/messagebox.cpp
  src/snail/messagebox.hpp
  src/snail/renderer.cpp
  src/snail/touch_input.cpp
  src/snail/window.cpp
Labels: enhancement, refactoring

#1280 Fix release date of v0.4.0
  CHANGELOG-jp.md
  CHANGELOG.md
Labels: bugfix

#1292 Hotfix/0.4.1
  CHANGELOG-jp.md
  CHANGELOG.md
  CMakeLists.txt
  src/elona/init.cpp
  src/elona/save_update.cpp
  src/version.cpp.in
Labels: bugfix

#1290 Delete unused constants
  src/snail/backends/sdl/audio.cpp
Labels: refactoring

#1289 Don't render weather effect's particle at (0, 0)
  src/elona/ui.cpp
Labels: bugfix

#1288 Fix casino card glitch
  runtime/mod/core/data/asset.lua
  src/elona/casino_card.cpp
Labels: bugfix

#1287 Change the time when the story begins: 01:10 -> 16:10
  src/elona/init.cpp
Labels: bugfix

#1293 Fix failure to get Git commit hash on Appveyor
  CMakeLists.txt
Labels: bugfix

#1299 Fix Stersha's portrait ID: core.starsha -> core.stersha
  src/elona/save_update.cpp
  src/version.cpp.in
Labels: bugfix

#1300 Fix bug that ghost of monster ball appears
  src/elona/command.cpp
Labels: bugfix

#1301 Don't render particles of rain and hard rain's effect at (0, 0)
  src/elona/ui.cpp
Labels: bugfix

#1298 Fix Input.prompt_dialog's overloads
  src/elona/lua_env/lua_api/lua_api_input.cpp
Labels: bugfix

#1304 Avoid unnecessary migration
  src/elona/save_update.cpp
Labels: bugfix

#1302 Move additional information in [w]ear menu right by 30 px
  src/elona/ui/ui_menu_equipment.cpp
Labels: bugfix

#1307 Replace core.item#kiroku.counter in all inventories with core.gold_piece
  src/elona/save_update.cpp
  src/version.cpp.in
Labels: bugfix

#1308 Fix snow field not generated
  src/elona/initialize_map_types.cpp
  src/elona/mapgen.cpp
  src/elona/mapgen.hpp
Labels: bugfix

#1309 Improve console output
  runtime/data/script/kernel/ush.lua
  runtime/data/script/kernel/ush/execute.lua
  src/elona/lua_env/console.cpp
Labels: bugfix, enhancement

#1310 Implement water ripple effect in title menu
  runtime/graphic/LICENSE.txt
  runtime/graphic/water_ripple.png
  runtime/mod/core/config_def.hcl
  runtime/mod/core/locale/en/config.hcl
  runtime/mod/core/locale/jp/config.hcl
  runtime/profile/default/config.hcl
  src/elona/main_menu.cpp
Labels: enhancement

#1317 Fix that you fail to search material spot if there are growing plants
  src/elona/activity.cpp
Labels: bugfix

#1314 Move routine for creation of Poppy to Lua side
  runtime/mod/core/data/map/static.lua
  src/elona/initialize_map_types.cpp
Labels: bugfix

#1316 Don't autosave when NPC drinks potion of potential
  src/elona/magic.cpp
Labels: enhancement

#1322 Fix various text error
  src/elona/activity.cpp
  src/elona/elonacore.cpp
Labels: I18N, bugfix

#1332 Check whether user/talk direcotry exists or not to avoid crash
  src/elona/ui/ui_menu_npc_tone.cpp
Labels: bugfix

#1330 Fix being able to talk to neutral NPCs
  src/elona/lua_env/lua_api/lua_api_input.cpp
  src/elona/talk.cpp
Labels: bugfix

#1329 Fix that stacked wells dry out at the same time
  src/elona/elonacore.cpp
Labels: bugfix

#1326 Fix get_executable_path() on Windows
  src/util/filepathutil.cpp
  src/util/filepathutil.hpp
Labels: bugfix

#1328 Fix "core.all_mods_loaded" event not being fired
  src/elona/lua_env/mod_manager.cpp
Labels: bugfix

#1320 Refactor autosaving: remove global flag, instead call function
  src/elona/activity.cpp
  src/elona/casino.cpp
  src/elona/command.cpp
  src/elona/elonacore.cpp
  src/elona/magic.cpp
  src/elona/proc_event.cpp
  src/elona/quest.cpp
  src/elona/save.cpp
  src/elona/save.hpp
  src/elona/turn_sequence.cpp
  src/elona/variables.hpp
  src/elona/wish.cpp
Labels: refactoring

#1319 Add lock picking skill to developer class
  runtime/mod/core/data/class.lua
Labels: enhancement

#1333 Fix strange random nefia
  runtime/mod/core/data/map.lua
  src/elona/map.cpp
  src/elona/save_update.cpp
  src/version.cpp.in
Labels: bugfix

#1323 Refactor: reduce goto statements
  src/elona/blending.cpp
  src/elona/building.cpp
  src/elona/casino.cpp
  src/elona/casino.hpp
  src/elona/command.cpp
  src/elona/elonacore.cpp
  src/elona/menu.cpp
  src/elona/ui.cpp
Labels: refactoring

#1334 Fix up #1323
  src/elona/building.cpp
  src/elona/casino.cpp
Labels: bugfix
