Repository elonafoobar/elonafoobar, pull requests merged in 2019-07, with the labels that each got.

#1388 Feature/refactor card info
  src/elona/casino.cpp
  src/elona/get_card_info.cpp
  src/elona/tcg.cpp
  src/elona/tcg.hpp
  src/elona/turn_sequence_pc_actions.cpp
  src/elona/variables.hpp
Labels: refactoring

#1391 Add network options and implement Palmia Times
  README.md
  runtime/locale/en/net.hcl
  runtime/locale/jp/net.hcl
  runtime/mod/core/config_def.hcl
  runtime/mod/core/locale/en/config.hcl
  runtime/mod/core/locale/jp/config.hcl
  runtime/profile/default/config.hcl
  src/elona/command.cpp
  src/elona/config/config.cpp
  src/elona/config/config.hpp
  src/elona/net.cpp
  src/elona/net.hpp
  src/elona/proc_event.cpp
  src/elona/random_event.cpp
  src/elona/ui/ui_menu_voting_box.cpp
  src/thirdparty/xxHash/LICENSE
  src/thirdparty/xxHash/xxh3.h
  src/thirdparty/xxHash/xxhash.c
  src/thirdparty/xxHash/xxhash.h
  src/thirdparty/xxHash/xxhashcpp.hpp
Labels: enhancement, network

#1392 Rename item name and data ID
  runtime/locale/en/talk_unique.hcl
  runtime/locale/jp/talk_unique.hcl
  runtime/mod/core/data/chara.lua
  runtime/mod/core/data/chara_chip.lua
  runtime/mod/core/data/dialog/unique.lua
  runtime/mod/core/data/dialog/unique/garok.lua
  runtime/mod/core/data/item.hcl
  runtime/mod/core/data/item.lua
  runtime/mod/core/data/item_chip.lua
  runtime/mod/core/locale/en/chara.hcl
  runtime/mod/core/locale/en/item.hcl
  runtime/mod/core/locale/jp/chara.hcl
  runtime/mod/core/locale/jp/item.hcl
  src/elona/command.cpp
  src/elona/item.cpp
Labels: I18N, bugfix, enhancement

#1394 Remove global variable tname
  src/elona/draw.cpp
  src/elona/elonacore.cpp
  src/elona/variables.hpp
Labels: refactoring

#1399 Remove exports: prefix
  runtime/data/script/kernel/private/scan_exports.lua
  runtime/mod/core/data/chara.lua
  src/elona/dialog.cpp
  src/elona/elonacore.cpp
  src/elona/lua_env/export_manager.hpp
  src/elona/shop.cpp
  src/tests/lua_data.cpp
  src/tests/lua_exports.cpp
Labels: enhancement

#1400 Don't save volatile data in Store object
  runtime/data/script/kernel/serial.lua
  src/tests/lua_serialization.cpp
Labels: enhancement

#1404 Partial mouse support
  src/elona/elona.hpp
  src/elona/std.cpp
  src/elona/turn_sequence.cpp
  src/elona/turn_sequence_pc_actions.cpp
Labels: enhancement

#1401 Add zlib/zstr/minizip as new dependencies
  CMakeLists.txt
  README.md
  android/app/src/main/java/xyz/ki/elonafoobar/ElonaFoobarActivity.java
  android/external/Android.mk
  appveyor.yml
  deps/install.bat
  src/elona/Android.mk.in
  src/snail/Android.mk.in
  src/spider/Android.mk.in
  src/thirdparty/minizip/CMakeLists.txt
  src/thirdparty/minizip/LICENSE
  src/thirdparty/minizip/minigzip.c
  src/thirdparty/minizip/minizip.c
  src/thirdparty/minizip/mz.h
  src/thirdparty/minizip/mz_compat.c
  src/thirdparty/minizip/mz_compat.h
  src/thirdparty/minizip/mz_crypt.c
  src/thirdparty/minizip/mz_crypt.h
  src/thirdparty/minizip/mz_crypt_apple.c
  src/thirdparty/minizip/mz_crypt_brg.c
  src/thirdparty/minizip/mz_crypt_openssl.c
  src/thirdparty/minizip/mz_crypt_win32.c
  src/thirdparty/minizip/mz_os.c
  src/thirdparty/minizip/mz_os.h
  src/thirdparty/minizip/mz_os_posix.c
  src/thirdparty/minizip/mz_os_win32.c
  src/thirdparty/minizip/mz_strm.c
  src/thirdparty/minizip/mz_strm.h
  src/thirdparty/minizip/mz_strm_buf.c
  src/thirdparty/minizip/mz_strm_buf.h
  src/thirdparty/minizip/mz_strm_bzip.c
  src/thirdparty/minizip/mz_strm_bzip.h
  src/thirdparty/minizip/mz_strm_libcomp.c
  src/thirdparty/minizip/mz_strm_libcomp.h
  src/thirdparty/minizip/mz_strm_lzma.c
  src/thirdparty/minizip/mz_strm_lzma.h
  src/thirdparty/minizip/mz_strm_mem.c
  src/thirdparty/minizip/mz_strm_mem.h
  src/thirdparty/minizip/mz_strm_os.h
  src/thirdparty/minizip/mz_strm_os_posix.c
  src/thirdparty/minizip/mz_strm_os_win32.c
  src/thirdparty/minizip/mz_strm_pkcrypt.c
  src/thirdparty/minizip/mz_strm_pkcrypt.h
  src/thirdparty/minizip/mz_strm_split.c
  src/thirdparty/minizip/mz_strm_split.h
  src/thirdparty/minizip/mz_strm_wzaes.c
  src/thirdparty/minizip/mz_strm_wzaes.h
  src/thirdparty/minizip/mz_strm_zlib.c
  src/thirdparty/minizip/mz_strm_zlib.h
  src/thirdparty/minizip/mz_zip.c
  src/thirdparty/minizip/mz_zip.h
  src/thirdparty/minizip/mz_zip_rw.c
  src/thirdparty/minizip/mz_zip_rw.h
  src/thirdparty/zstr/.gitignore
  src/thirdparty/zstr/.travis.Dockerfile.in
  src/thirdparty/zstr/.travis.yml
  src/thirdparty/zstr/LICENSE
  src/thirdparty/zstr/strict_fstream.hpp
  src/thirdparty/zstr/zstr.hpp
  src/util/Android.mk.in
Labels: build, enhancement

#1406 Circle CI
  .circleci/config.yml
  .travis.yml
Labels: build

#1407 Remove Boost.Locale from foobar dependencies
  .travis/before_install.sh
  CMakeLists.txt
  runtime/mod/core/locale/jp/config.hcl
  src/util/filepathutil.cpp
  src/util/unicode.hpp
  src/util/unicode_utf16.hpp
Labels: build

#1408 Refactor/rename identify state
  src/elona/_putit/item.cpp
  src/elona/activity.cpp
  src/elona/adventurer.cpp
  src/elona/autopick.cpp
  src/elona/blending.cpp
  src/elona/calc.cpp
  src/elona/command.cpp
  src/elona/ctrl_inventory.cpp
  src/elona/elonacore.cpp
  src/elona/enums.hpp
  src/elona/equipment.cpp
  src/elona/item.cpp
  src/elona/item.hpp
  src/elona/item_load_desc.cpp
  src/elona/itemgen.cpp
  src/elona/lua_env/enums/enums.cpp
  src/elona/lua_env/lua_api/lua_api_debug.cpp
  src/elona/lua_env/lua_class/lua_class_item.cpp
  src/elona/save_update.cpp
  src/elona/talk_npc.cpp
  src/elona/ui.cpp
  src/elona/wish.cpp
  src/tests/util.cpp
Labels: refactoring

#1409 Change RNG from mt19937 to xorshift's variant
  src/elona/gdata.cpp
  src/elona/gdata.hpp
  src/elona/init.cpp
  src/elona/random.cpp
  src/elona/random.hpp
  src/thirdparty/xoshiro256/splitmix64.hpp
  src/thirdparty/xoshiro256/xoshiro256.hpp
Labels: enhancement

#1410 Change notation to refer to other mod's directory
  runtime/mod/core/data/asset.lua
  runtime/mod/core/data/music.lua
  runtime/mod/core/data/sound.lua
  src/elona/filesystem.cpp
  src/tests/filesystem.cpp
Labels: customization, enhancement

#1411 Fix deck bug
  runtime/data/deck/deck_0.s2
  runtime/data/deck/deck_1.s2
  runtime/data/deck_0.s2
  runtime/data/deck_1.s2
  runtime/data/deck_2.s2
  src/elona/ctrl_file.cpp
  src/elona/tcg.cpp
Labels: bugfix, refactoring

#1412 Reduce execution time to run all tests, especially on Appveyor
  src/tests/i18n.cpp
  src/tests/i18n_builtins.cpp
  src/tests/lua/chara.lua
  src/tests/lua/exports/eating_effect.lua
  src/tests/lua/item.lua
  src/tests/lua/map.lua
  src/tests/lua/trait.lua
Labels: build

#1415 Update CONTRIBUTING.md [ci skip]
  .github/CONTRIBUTING.md
Labels: enhancement

#1413 Fix tile shadow rendering
  runtime/mod/core/data/asset.lua
  runtime/mod/core/graphic/interface_ex1.png
  runtime/mod/core/graphic/interface_ex2.png
  runtime/mod/core/graphic/interface_ex3.png
  src/elona/cell_draw.cpp
Labels: bugfix

#1414 Expand <LANGUAGE> in path string to current language
  src/elona/filesystem.cpp
  src/tests/filesystem.cpp
Labels: enhancement
