Repository elonafoobar/elonafoobar, pull requests merged in 2020-05, with the labels that each got.

#1619 Refactor: remove unused options
  runtime/graphic/LICENSE.txt
  runtime/graphic/quick_action.png
  src/elona/config.hpp
Labels: 2: Refactoring

#1618 Update README.md [ci skip]
  README.md
  resources/logo.png
Labels: 2: Improvement, 6: Documentation

#1617 Fix typos and position of log message
  runtime/mod/core/locale/jp/item.lua
  src/elona/command.cpp
  src/elona/scene.cpp
Labels: 1: Bug, 6: Graphics, 6: Text, 8: Vanilla

#1616 Performance improvement: reduce texture copying in draw_npc_chara_chip()
  src/elona/cell_draw.cpp
Labels: 2: Optimization, 6: Graphics

#1624 Fix golem's getting dimmed
  src/elona/status_ailment.cpp
Labels: 1: Bug

#1620 Make it possible to assign shortcut on cargo items
  runtime/mod/core/locale/en/ctrl_inventory.lua
  runtime/mod/core/locale/jp/ctrl_inventory.lua
  src/elona/ctrl_inventory.cpp
Labels: 2: New Feature, 6: UI

#1621 Improve i18n for data instances
  runtime/data/script/kernel/i18n.lua
  runtime/mod/core/locale/en/ability.lua
  runtime/mod/core/locale/en/chara.lua
  runtime/mod/core/locale/en/class.lua
  runtime/mod/core/locale/en/fish.lua
  runtime/mod/core/locale/en/god.lua
  runtime/mod/core/locale/en/item_material.lua
  runtime/mod/core/locale/en/race.lua
  runtime/mod/core/locale/jp/ability.lua
  runtime/mod/core/locale/jp/chara.lua
  runtime/mod/core/locale/jp/class.lua
  runtime/mod/core/locale/jp/fish.lua
  runtime/mod/core/locale/jp/god.lua
  runtime/mod/core/locale/jp/item_material.lua
  runtime/mod/core/locale/jp/race.lua
  src/elona/ability.cpp
  src/elona/activity.cpp
  src/elona/blending.cpp
  src/elona/chara_db.cpp
  src/elona/character_making.cpp
  src/elona/class.cpp
  src/elona/command.cpp
  src/elona/data/base_database.hpp
  src/elona/dump_player_info.cpp
  src/elona/enchantment.cpp
  src/elona/food.cpp
  src/elona/get_card_info.cpp
  src/elona/god.cpp
  src/elona/i18n.hpp
  src/elona/item.cpp
  src/elona/item_load_desc.cpp
  src/elona/lua_env/i18n_manager.cpp
  src/elona/lua_env/i18n_manager.hpp
  src/elona/magic.cpp
  src/elona/menu.cpp
  src/elona/talk_house_visitor.cpp
  src/elona/talk_npc.cpp
  src/elona/text.cpp
  src/elona/ui.cpp
  src/elona/ui/ui_menu_character_sheet.cpp
  src/elona/ui/ui_menu_charamake_attributes.cpp
  src/elona/ui/ui_menu_charamake_class.cpp
  src/elona/ui/ui_menu_charamake_race.cpp
  src/elona/ui/ui_menu_ctrl_ally.cpp
  src/elona/ui/ui_menu_skills.cpp
  src/elona/ui/ui_menu_spells.cpp
  src/elona/wish.cpp
Labels: 2: New Feature, 4: Modding, 6: I18N / L10N

#1627 Improve enchantment generate using WeightedRandomSampler
  src/elona/enchantment.cpp
Labels: 2: Refactoring

#1629 Run clang-format
  .circleci/config.yml
  src/elona/autopick.cpp
  src/elona/calc.cpp
  src/elona/character.cpp
  src/elona/data/base_database.hpp
  src/elona/data/types/type_map.cpp
  src/elona/death.cpp
  src/elona/enchantment.cpp
  src/elona/item.cpp
  src/elona/item.hpp
  src/elona/keybind/keybind_deserializer.cpp
  src/elona/lua_env/api_manager.cpp
  src/elona/lua_env/config_manager.cpp
  src/elona/lua_env/lua_api/lua_api_map.cpp
  src/elona/lua_env/mod_manager.cpp
  src/elona/lua_env/mod_manifest.cpp
  src/elona/lua_env/mod_version_resolver.cpp
  src/elona/main_menu.cpp
  src/elona/menu.cpp
  src/elona/message.cpp
  src/elona/net.cpp
  src/elona/save.cpp
  src/elona/scene.cpp
  src/elona/semver.hpp
  src/elona/set_item_info.cpp
  src/elona/status_ailment.cpp
  src/elona/ui.cpp
  src/elona/ui/ui_menu_keybindings.cpp
  src/elona/ui/ui_menu_mods.cpp
  src/launcher_main.cpp
  src/snail/backends/sdl/filedialog.cpp
  src/snail/backends/sdl/surface.cpp
  src/tests/keybind_serializer.cpp
  src/util/unicode.hpp
Labels: 2: Refactoring, 3: CI

#1628 Remove 'toggle_console' action
  runtime/mod/core/locale/en/keybindings.lua
  runtime/mod/core/locale/jp/keybindings.lua
  src/elona/keybind/keybind_actions.cpp
  src/elona/lua_env/console.cpp
  src/elona/lua_env/console.hpp
  src/elona/turn_sequence_pc_actions.cpp
Labels: 2: Improvement, 3: Development

#1632 Hotfix/0.7.2
  CHANGELOG-ja.md
  CHANGELOG.md
  CMakeLists.txt
  runtime/mod/core/i18n/functions.lua
  src/elona/command.cpp
  src/elona/command.hpp
  src/tests/i18n.cpp
Labels: 1: Bug, 1: Crash / Freeze, 3: Release

#1633 Hotfix/0.7.2
  CHANGELOG-ja.md
  CHANGELOG.md
  CMakeLists.txt
  runtime/mod/core/i18n/functions.lua
  src/elona/command.cpp
  src/elona/command.hpp
  src/tests/i18n.cpp
Labels: 1: Bug, 1: Crash / Freeze, 3: Release

#1638 Reduce use of Item::index
  src/elona/cell_draw.cpp
  src/elona/command.cpp
  src/elona/ctrl_inventory.cpp
  src/elona/map_cell.cpp
  src/elona/map_cell.hpp
  src/elona/text.cpp
  src/elona/turn_sequence.cpp
  src/elona/turn_sequence_pc_actions.cpp
  src/elona/variables.hpp
Labels: 2: Refactoring

#1637 Change save directory's naming convention
  runtime/mod/core/locale/en/chara_making.lua
  runtime/mod/core/locale/jp/chara_making.lua
  src/elona/character_making.cpp
Labels: 2: Improvement

#1636 Refactor fov_los()
  src/elona/activity.cpp
  src/elona/ai.cpp
  src/elona/animation.cpp
  src/elona/attack.cpp
  src/elona/command.cpp
  src/elona/fov.cpp
  src/elona/fov.hpp
  src/elona/lua_env/lua_api/lua_api_fov.cpp
  src/elona/magic.cpp
  src/elona/text.cpp
  src/elona/turn_sequence.cpp
  src/elona/ui.cpp
Labels: 2: Refactoring

#1635 Unite `cdata` and `cdatan`
  doc/api/classes/LuaCharacter.luadoc
  src/elona/adventurer.cpp
  src/elona/ai.cpp
  src/elona/building.cpp
  src/elona/chara_db.cpp
  src/elona/character.cpp
  src/elona/character.hpp
  src/elona/character_making.cpp
  src/elona/character_status.cpp
  src/elona/class.cpp
  src/elona/command.cpp
  src/elona/ctrl_file.cpp
  src/elona/death.cpp
  src/elona/deferred_event.cpp
  src/elona/dmgheal.cpp
  src/elona/draw.cpp
  src/elona/dump_player_info.cpp
  src/elona/equipment.cpp
  src/elona/god.cpp
  src/elona/init.cpp
  src/elona/initialize_map_types.cpp
  src/elona/lua_env/console.cpp
  src/elona/lua_env/lua_class/lua_class_character.cpp
  src/elona/magic.cpp
  src/elona/map.cpp
  src/elona/mef.cpp
  src/elona/menu.cpp
  src/elona/net.cpp
  src/elona/quest.cpp
  src/elona/race.cpp
  src/elona/save.cpp
  src/elona/scene.cpp
  src/elona/status_ailment.cpp
  src/elona/talk.cpp
  src/elona/talk_npc.cpp
  src/elona/text.cpp
  src/elona/turn_sequence.cpp
  src/elona/ui/ui_menu_adventurers.cpp
  src/elona/ui/ui_menu_character_sheet.cpp
  src/elona/ui/ui_menu_ctrl_ally.cpp
  src/elona/ui/ui_menu_feats.cpp
  src/elona/ui/ui_menu_hire.cpp
  src/elona/ui/ui_menu_quest_board.cpp
  src/elona/variables.hpp
  src/elona/wish.cpp
  src/tests/i18n_builtins.cpp
  src/tests/serialization.cpp
Labels: 2: Refactoring

#1634 Refactor blending
  doc/api/classes/LuaGameData.luadoc
  doc/api/classes/LuaItem.luadoc
  doc/api/enchantment.luadoc
  doc/api/i18n.luadoc
  doc/api/item.luadoc
  runtime/mod/core/api/impl.lua
  runtime/mod/core/api/impl/blending.lua
  runtime/mod/core/data.lua
  runtime/mod/core/data/blending_recipe.lua
  runtime/mod/core/locale/en/blending.lua
  runtime/mod/core/locale/en/blending_recipe.lua
  runtime/mod/core/locale/en/i18n.lua
  runtime/mod/core/locale/jp/blending.lua
  runtime/mod/core/locale/jp/blending_recipe.lua
  runtime/mod/core/locale/jp/i18n.lua
  src/elona/blending.cpp
  src/elona/blending.hpp
  src/elona/cell_draw.hpp
  src/elona/data/init.cpp
  src/elona/data/types.cpp
  src/elona/data/types.hpp
  src/elona/data/types/type_blending_recipe.cpp
  src/elona/data/types/type_blending_recipe.hpp
  src/elona/init.cpp
  src/elona/item.cpp
  src/elona/lua_env/lua_api/lua_api.cpp
  src/elona/lua_env/lua_api/lua_api.hpp
  src/elona/lua_env/lua_api/lua_api_enchantment.cpp
  src/elona/lua_env/lua_api/lua_api_enchantment.hpp
  src/elona/lua_env/lua_api/lua_api_i18n.cpp
  src/elona/lua_env/lua_api/lua_api_i18n.hpp
  src/elona/lua_env/lua_api/lua_api_item.cpp
  src/elona/lua_env/lua_api/lua_api_item.hpp
  src/elona/lua_env/lua_class/lua_class_game_data.cpp
  src/elona/lua_env/lua_class/lua_class_item.cpp
Labels: 2: Refactoring, 5: Lua API
