Repository elonafoobar/elonafoobar, pull requests merged in 2020-03, with the labels that each got.

#1541 Define enum class ItemCategory
  src/elona/adventurer.cpp
  src/elona/ai.cpp
  src/elona/autopick.cpp
  src/elona/blending.cpp
  src/elona/building.cpp
  src/elona/calc.cpp
  src/elona/character.cpp
  src/elona/command.cpp
  src/elona/ctrl_inventory.cpp
  src/elona/data/types/type_item.cpp
  src/elona/data/types/type_item.hpp
  src/elona/elonacore.cpp
  src/elona/enchantment.cpp
  src/elona/enchantment.hpp
  src/elona/enums.hpp
  src/elona/equipment.cpp
  src/elona/food.cpp
  src/elona/item.cpp
  src/elona/item_db.cpp
  src/elona/item_load_desc.cpp
  src/elona/itemgen.cpp
  src/elona/lua_env/lua_api/lua_api_item.cpp
  src/elona/magic.cpp
  src/elona/map.cpp
  src/elona/menu.cpp
  src/elona/talk_npc.cpp
  src/elona/turn_sequence.cpp
  src/elona/turn_sequence_pc_actions.cpp
  src/elona/ui/ui_menu_feats.cpp
  src/elona/wish.cpp
Labels: 2: Refactoring

#1542 Add missing Japanese double quotation in scene file [ci skip]
  runtime/mod/core/locale/jp/lazy/scene.hsp
Labels: 1: Bug, 6: Text, 8: Vanilla

#1543 Fix chara drop: rich person/noble child/tourist
  runtime/mod/core/data/chara.lua
  runtime/mod/core/data/chara_drop.lua
Labels: 1: Bug

#1544 Fix i18n error on map name
  runtime/locale/en/map.lua
  runtime/locale/jp/map.lua
Labels: 1: Bug, 6: Text

#1545 Unidentified item's name is different from its color
  src/elona/set_item_info.cpp
Labels: 1: Bug

#1546 Refactor serialization routines
  .circleci/config.yml
  Makefile
  Makefile.win
  src/bench/serialization.cpp
  src/elona/_putit/ability.cpp
  src/elona/_putit/activity.cpp
  src/elona/_putit/buff.cpp
  src/elona/_putit/character.cpp
  src/elona/_putit/enchantment.cpp
  src/elona/_putit/foobar_data.cpp
  src/elona/_putit/item.cpp
  src/elona/_putit/position.cpp
  src/elona/_putit/version.hpp
  src/elona/ability.hpp
  src/elona/character.hpp
  src/elona/ctrl_file.cpp
  src/elona/deferred_event.cpp
  src/elona/gdata.hpp
  src/elona/item.hpp
  src/elona/lua_env/console.cpp
  src/elona/position.hpp
  src/elona/putit.hpp
  src/elona/save.cpp
  src/elona/save_update.cpp
  src/elona/semver.hpp
  src/elona/serialization/binary.hpp
  src/elona/serialization/binary/detail/byte_swap.hpp
  src/elona/serialization/binary/iarchive.hpp
  src/elona/serialization/binary/oarchive.hpp
  src/elona/serialization/concepts.hpp
  src/elona/serialization/json.hpp
  src/elona/serialization/json/oarchive.hpp
  src/elona/serialization/macros.hpp
  src/elona/serialization/serialization.hpp
  src/elona/serialization/serialize.hpp
  src/elona/serialization/std.hpp
  src/elona/serialization/std/bitset.hpp
  src/elona/serialization/std/deque.hpp
  src/elona/serialization/std/string.hpp
  src/elona/serialization/std/vector.hpp
  src/putit/README.md
  src/putit/archive/archive.hpp
  src/putit/archive/archive_base.hpp
  src/putit/archive/binary_archive.hpp
  src/putit/archive/detail/byte_swap.hpp
  src/putit/archive/json_archive.hpp
  src/putit/bin/putit.py
  src/putit/putit.hpp
  src/version.hpp
Labels: 2: Refactoring

#1548 `tools/docgen` fails to generate some functions' documentation
  doc/api/map.luadoc
  src/elona/lua_env/lua_api/lua_api_chara.cpp
  src/elona/lua_env/lua_api/lua_api_chara.hpp
  src/elona/lua_env/lua_api/lua_api_item.cpp
  src/elona/lua_env/lua_api/lua_api_map.cpp
  tools/docgen/src/main.rs
Labels: 1: Bug, 6: Documentation

#1547 Rename all Lua enums from `PascalCase` to `lower_snake_case`
  doc/api/classes/LuaCharacter.luadoc
  doc/api/classes/LuaMapGenerator.luadoc
  doc/api/enums.luadoc
  runtime/mod/core/data/asset.lua
  runtime/mod/core/data/buff.lua
  runtime/mod/core/data/chara.lua
  runtime/mod/core/data/chara_drop.lua
  runtime/mod/core/data/dialog/unique/abyss.lua
  runtime/mod/core/data/dialog/unique/doria.lua
  runtime/mod/core/data/dialog/unique/erystia.lua
  runtime/mod/core/data/dialog/unique/kaneda_bike.lua
  runtime/mod/core/data/dialog/unique/karam.lua
  runtime/mod/core/data/dialog/unique/lexus.lua
  runtime/mod/core/data/dialog/unique/lily.lua
  runtime/mod/core/data/dialog/unique/lomias.lua
  runtime/mod/core/data/dialog/unique/mia.lua
  runtime/mod/core/data/dialog/unique/miches.lua
  runtime/mod/core/data/dialog/unique/miral.lua
  runtime/mod/core/data/dialog/unique/orphe.lua
  runtime/mod/core/data/dialog/unique/pael.lua
  runtime/mod/core/data/dialog/unique/poppy.lua
  runtime/mod/core/data/dialog/unique/raphael.lua
  runtime/mod/core/data/dialog/unique/renton.lua
  runtime/mod/core/data/dialog/unique/rilian.lua
  runtime/mod/core/data/dialog/unique/rogue_boss.lua
  runtime/mod/core/data/dialog/unique/slan.lua
  runtime/mod/core/data/dialog/unique/strange_scientist.lua
  runtime/mod/core/data/item.lua
  runtime/mod/core/data/map.lua
  runtime/mod/core/data/map/static.lua
  runtime/mod/core/data/shop_inventory.lua
  runtime/mod/core/data/trait.lua
  runtime/mod/core/exports/eating_effect.lua
  runtime/mod/core/exports/impl/shop_inventory.lua
  runtime/mod/core/exports/impl/show_dialog.lua
  runtime/mod/core/i18n/functions.lua
  runtime/mod/core/i18n/jp_endings.lua
  src/elona/data/types/type_asset.cpp
  src/elona/lua_env/api_manager.cpp
  src/elona/lua_env/enums/enums.cpp
  src/elona/lua_env/enums/enums.hpp
  src/elona/lua_env/lua_api/lua_api_input.cpp
  src/elona/lua_env/lua_api/lua_api_world.cpp
  src/elona/lua_env/lua_class/lua_class_character.cpp
  src/elona/lua_env/lua_enums.hpp
  src/elona/wish.hpp
  src/tests/data/registry/chara/data.lua
  src/tests/data/registry/item/data.lua
  src/tests/lua/classes/LuaCharacter.lua
  src/tests/lua/fov.lua
  src/tests/lua/map.lua
  tools/docgen/src/main.rs
Labels: 10: Breaking Change, 2: Improvement, 4: Modding

#1550 Make require() take relative paths from callers
  runtime/mod/core/data.lua
  runtime/mod/core/data/dialog.lua
  runtime/mod/core/data/dialog/unique.lua
  runtime/mod/core/data/dialog/unique/abyss.lua
  runtime/mod/core/data/dialog/unique/ainc.lua
  runtime/mod/core/data/dialog/unique/arnord.lua
  runtime/mod/core/data/dialog/unique/balzak.lua
  runtime/mod/core/data/dialog/unique/conery.lua
  runtime/mod/core/data/dialog/unique/doria.lua
  runtime/mod/core/data/dialog/unique/erystia.lua
  runtime/mod/core/data/dialog/unique/gilbert.lua
  runtime/mod/core/data/dialog/unique/icolle.lua
  runtime/mod/core/data/dialog/unique/lexus.lua
  runtime/mod/core/data/dialog/unique/lily.lua
  runtime/mod/core/data/dialog/unique/lomias.lua
  runtime/mod/core/data/dialog/unique/loyter.lua
  runtime/mod/core/data/dialog/unique/marks.lua
  runtime/mod/core/data/dialog/unique/mia.lua
  runtime/mod/core/data/dialog/unique/miches.lua
  runtime/mod/core/data/dialog/unique/noel.lua
  runtime/mod/core/data/dialog/unique/pael.lua
  runtime/mod/core/data/dialog/unique/renton.lua
  runtime/mod/core/data/dialog/unique/rilian.lua
  runtime/mod/core/data/dialog/unique/rogue_boss.lua
  runtime/mod/core/data/dialog/unique/shena.lua
  runtime/mod/core/data/dialog/unique/tam.lua
  runtime/mod/core/data/dialog/unique/xabi.lua
  runtime/mod/core/data/map.lua
  runtime/mod/core/exports/impl.lua
  runtime/mod/core/i18n/init.lua
  runtime/mod/core/init.lua
  src/elona/lua_env/loaded_chunk_cache.hpp
  src/tests/data/mods/test_require_chunks/data/script2.lua
  src/tests/data/mods/test_require_chunks/data/script3.lua
  src/tests/data/mods/test_require_chunks/data/script4.lua
  src/tests/data/mods/test_require_chunks/init.lua
  src/tests/lua_mods.cpp
Labels: 10: Breaking Change, 2: New Feature, 5: Lua API

#1551 Add missing LDoc documentation about Animation
  doc/api/animation.luadoc
  doc/api/console.luadoc
  doc/api/enums.luadoc
  src/elona/lua_env/lua_api/lua_api_animation.cpp
  src/elona/lua_env/lua_api/lua_api_console.cpp
Labels: 2: Improvement, 6: Documentation

#1553 Remove unused variable in Makefile
  Makefile
Labels: 2: Refactoring

#1554 Remove src/elona/elonacore.cpp
  src/elona/elonacore.cpp
Labels: 2: Refactoring

#1558 Release/0.7.0
  CHANGELOG-jp.md
  CHANGELOG.md
  CMakeLists.txt
  CREDITS.txt
Labels: 3: Release
