Repository elonafoobar/elonafoobar, pull requests merged in 2020-02, with the labels that each got.

#1518 Remove debug function EventTree:print(), used nowhere
  runtime/data/script/kernel/event_tree.lua
Labels: 2: Refactoring

#1521 Enable SOL_CHECK_ARGUMENTS in debug build for detecting potential bugs
  CMakeLists.txt
  runtime/data/script/kernel/config.lua
  runtime/mod/core/exports/eating_effect.lua
  src/elona/data/types/type_item_material.cpp
  src/elona/lua_env/api_manager.cpp
Labels: 1: Bug

#1523 Fix tools/docgen's warnings [ci skip]
  tools/docgen/src/main.rs
Labels: 2: Refactoring

#1522 Add application icon (Windows only so far)
  CMakeLists.txt
  resources/atcat-128x128.png
  resources/atcat-16x16.png
  resources/atcat-192x192.png
  resources/atcat-256x256.png
  resources/atcat-32x32.png
  resources/atcat-48x48.png
  resources/atcat-64x64.png
  resources/atcat-96x96.png
  resources/icon.ico
  resources/icon_windows.rc
Labels: 2: New Feature

#1524 Add missing LDoc documentation's icon
  doc/ldoc.ltp
  doc/static/atcat.png
Labels: 2: New Feature, 6: Documentation

#1526 Hotfix/0.6.1: Disable network feature temporarily until the bug is resolved
  src/elona/config.cpp
Labels: 1: Crash / Freeze, 3: Release, 6: Network

#1527 Hotfix/0.6.1 to develop
  src/elona/config.cpp
Labels: 1: Crash / Freeze, 6: Network

#1530 Fix some sound effects not played
  src/elona/data/init.cpp
Labels: 1: Bug, 6: Audio

#1531 Fix type mismatch in Lua scripts
  runtime/data/script/kernel/config.lua
  runtime/mod/core/exports/impl/shop_inventory.lua
Labels: 1: Bug, 5: Lua API

#1534 Lua: Fix expressions containing '/', division for float
  runtime/mod/core/data/dialog/unique/abyss.lua
  runtime/mod/core/data/dialog/unique/doria.lua
  runtime/mod/core/data/dialog/unique/lexus.lua
  runtime/mod/core/data/dialog/unique/miral.lua
  runtime/mod/core/data/dialog/unique/rogue_boss.lua
  runtime/mod/core/data/shop_inventory.lua
  runtime/mod/core/exports/impl/shop_inventory.lua
Labels: 1: Bug

#1532 Add prelude module
  doc/api/math.luadoc
  runtime/data/script/kernel/init.lua
  runtime/data/script/kernel/math_ext.lua
  runtime/data/script/kernel/serial.lua
  runtime/data/script/prelude/coroutine_ext.lua
  runtime/data/script/prelude/init.lua
  runtime/data/script/prelude/inspect.lua
  runtime/data/script/prelude/math_ext.lua
  runtime/data/script/prelude/string_ext.lua
  runtime/data/script/prelude/table_ext.lua
  runtime/data/script/prelude/utf8_ext.lua
  runtime/mod/core/data/buff.lua
  runtime/mod/core/data/dialog/unique/abyss.lua
  runtime/mod/core/data/dialog/unique/doria.lua
  runtime/mod/core/data/dialog/unique/erystia.lua
  runtime/mod/core/data/dialog/unique/lexus.lua
  runtime/mod/core/data/dialog/unique/lily.lua
  runtime/mod/core/data/dialog/unique/marks.lua
  runtime/mod/core/data/dialog/unique/miral.lua
  runtime/mod/core/data/dialog/unique/noel.lua
  runtime/mod/core/data/dialog/unique/poppy.lua
  runtime/mod/core/data/dialog/unique/raphael.lua
  runtime/mod/core/data/dialog/unique/strange_scientist.lua
  runtime/mod/core/data/map.lua
  runtime/mod/core/data/shop_inventory.lua
  runtime/mod/core/exports/eating_effect.lua
  runtime/mod/core/exports/impl/shop_inventory.lua
  runtime/mod/core/exports/impl/show_dialog.lua
  runtime/mod/core/i18n/functions.lua
  src/elona/lua_env/api_manager.cpp
  src/elona/lua_env/api_manager.hpp
  src/elona/lua_env/console.cpp
  src/elona/lua_env/lua_api/lua_api.cpp
  src/elona/lua_env/lua_api/lua_api_math.cpp
  src/elona/lua_env/lua_api/lua_api_math.hpp
  src/elona/lua_env/lua_env.cpp
  src/elona/lua_env/mod_manager.cpp
Labels: 2: New Feature, 5: Lua API

#1496 Update C++ version from C++14 to C++17
  .github/workflows/build.yml
  .travis.yml
  CMakeLists.txt
  README.md
  src/elona/building.cpp
  src/elona/character_making.cpp
  src/elona/crafting.cpp
  src/elona/crafting.hpp
  src/elona/dmgheal.cpp
  src/elona/elona.hpp
  src/elona/enchantment.cpp
  src/elona/fish.cpp
  src/elona/god.cpp
  src/elona/i18n.hpp
  src/elona/lua_env/lua_api/lua_api_common.hpp
  src/elona/lua_env/lua_api/lua_api_map.cpp
  src/elona/lua_env/lua_api/lua_api_world.cpp
  src/elona/lua_env/lua_class/lua_class_ability.cpp
  src/elona/lua_env/lua_class/lua_class_area.cpp
  src/elona/lua_env/lua_class/lua_class_character.cpp
  src/elona/lua_env/lua_class/lua_class_date_time.cpp
  src/elona/lua_env/lua_class/lua_class_game_data.cpp
  src/elona/lua_env/lua_class/lua_class_item.cpp
  src/elona/lua_env/lua_class/lua_class_map_data.cpp
  src/elona/lua_env/lua_class/lua_class_map_generator.cpp
  src/elona/lua_env/lua_class/lua_class_position.cpp
  src/elona/macro.hpp
  src/elona/menu.cpp
  src/elona/optional.hpp
  src/elona/position.hpp
  src/elona/random.hpp
  src/elona/talk.cpp
  src/elona/talk.hpp
  src/elona/turn_sequence.hpp
  src/elona/ui.cpp
  src/elona/ui/ui_menu_character_sheet.cpp
  src/elona/ui/ui_menu_charamake_attributes.cpp
  src/elona/ui/ui_menu_charamake_attributes.hpp
  src/elona/ui/ui_menu_charamake_class.cpp
  src/elona/ui/ui_menu_charamake_race.cpp
  src/elona/ui/ui_menu_composite_character.hpp
  src/elona/ui/ui_menu_composite_skills.hpp
  src/elona/wish.cpp
  src/putit/archive/binary_archive.hpp
  src/putit/archive/json_archive.hpp
  src/snail/backends/sdl/filedialog.cpp
  src/spider/http/backends/boost_asio/request.cpp
  src/tests/lua/tostring.lua
  src/tests/tests.hpp
  src/thirdparty/minizip/CMakeLists.txt
  src/thirdparty/sol2/LICENSE.txt
  src/thirdparty/sol2/forward.hpp
  src/thirdparty/sol2/sol.hpp
  src/util/either.hpp
  src/util/filepathutil.cpp
  src/util/filepathutil.hpp
  src/util/fileutil.hpp
Labels: 2: Improvement, 3: Development

#1535 Support undo/redo in house design mode
  src/elona/CMakeLists.txt
  src/elona/building.cpp
  src/elona/building.hpp
  src/elona/elonacore.cpp
  src/elona/mapeditor/command.cpp
  src/elona/mapeditor/command.hpp
  src/elona/mapeditor/design_mode.cpp
  src/elona/mapeditor/design_mode.hpp
  src/elona/mapeditor/undo_history.cpp
  src/elona/mapeditor/undo_history.hpp
Labels: 2: New Feature, 6: UI

#1539 Fix the drops parameter of Vesda
  runtime/mod/core/data/chara.lua
Labels: 1: Bug
